### ISSUE TITLE
Extending incremental parsing to data structures derived from tree

### ISSUE THREAD

**Issue by invrainbow** [tree-sitter/tree-sitter#1011]
I'm building a text editor that maintains an up-to-date tree as the user edits the file. I'm using that tree to derive other data structures. For this question, say I'm walking the tree and generating a Toplevel

```c
struct Toplevel {
  int type;
  cur2 pos;
  cur2 decl_start;
  cur2 spec_start;
  cur2 name_start;
  Gotype *inferred_type;
};
```

for each decl node I see. 

I want this list of toplevels to also be kept up-to-date on each keystroke. The problem is, I have to re-derive this list from the entire tree on every keystroke, because my data structure isn't plugged into the "incremental parsing" system. This cancels out the core advantage of using Tree-sitter, incremental processing.

Can I leverage Tree-sitter's incremental parsing facilities to update my data structures incrementally along with the tree? I'm imagining I'd define a function converting nodes to data structures and pass that to Tree-sitter. If not, is there a good starting point to "rip out" Tree-sitter's incremental logic for my own use?

**Comment by stephe-ada-guru** [comment]
invrainbow ***@***.***> writes:

> Say I'm building a text editor. As the user edits the file, I maintain
> an up-to-date tree. I'm then using this tree to derive other data
> structures.

I have a similar situation in Emacs ada-mode, where I'm using a
different incremental parser.

The solution I'm using is to walk the tree after parsing is done as you
do, but only process nodes that overlap an "active byte region". This
works because Emacs always wants information about the code in a certain
region; the visible region for colorizing, the selected region or
current line for indent.

-- 
-- Stephe

**Comment by maxbrunsfeld** [comment]
Currently, the only facility for updating derived data structures is the [`ts_tree_get_changed_ranges`](https://github.com/tree-sitter/tree-sitter/blob/6192d2961096bda537e8ecb20de9c9dbd506cad8/lib/include/tree_sitter/api.h#L383-L401) function.
