### ISSUE TITLE
Agda treesitter is dead

### ISSUE THREAD

**Issue by AusCyberman** [tree-sitter/tree-sitter#1206]
Agda treesitter is a incomplete and hasn't been worked on for two years. But is still needed to be developed on

**Comment by googleson78** [comment]
I'm not sure how realistic this is, because of at least two things:

* mixfix operators - users can define operators with **arbitrary** operand counts, meaning parsing is dependent on definitions
* Agda highlighting is expected to differ based on the **types/"kinds"** of things - types and terms are highlighted in different ways (and this is immensely helpful for a lot of Agda programmers)

Both of these are solvable by running agda first, which afaik, for the first uses a lexer and parser generator, and for the second generates highlighting files which the text editor uses afterwards.

Can `tree-sitter` somehow call out to agda and then use the info it produces?

Also I'm not sure, because of how well integrated/integrateable agda is with editors, if there is much of a use case of making a `tree-sitter` grammar for it - do you have something concrete in mind?

**Comment by AusCyberman** [comment]
> 
> 
> I'm not sure how realistic this is, because of at least two things:
> 
>     * mixfix operators - users can define operators with **arbitrary** operand counts, meaning parsing is dependent on definitions
> 
>     * Agda highlighting is expected to differ based on the **types/"kinds"** of things - types and terms are highlighted in different ways (and this is immensely helpful for a lot of Agda programmers)
> 
> 
> Both of these are solvable by running agda first, which afaik, for the first uses a lexer and parser generator, and for the second generates highlighting files which the text editor uses afterwards.
> 
> Can `tree-sitter` somehow call out to agda and then use the info it produces?
> 
> Also I'm not sure, because of how well integrated/integrateable agda is with editors, if there is much of a use case of making a `tree-sitter` grammar for it - do you have something concrete in mind?

Calling out to agda could be an option, or building into the parser, recoginisation of terms and mixfix operators.

A use case for this would be nvim-treesitter and unifying the agda highlighting system under the treesitter implementation

**Comment by dundargoc** [comment]
Damn, that sucks. Good luck with that.
