### ISSUE TITLE
Rust bindings: Should Node be Send and Sync?

### ISSUE THREAD

**Issue by wiseman** [tree-sitter/tree-sitter#1241]
In the Rust bindings, I see that `Tree` is both `Send` and `Sync`, but `Node` isn't. Is that intentional?

**Comment by maxbrunsfeld** [comment]
Yeah, I think that `Node`  should indeed be send and sync.

**Comment by ahlinc** [comment]
I'm not sure that it may be _Sync_ and _Send_. If to look to the `TSNode` struct and its constructor function:
https://github.com/tree-sitter/tree-sitter/blob/c7998d93d0d180e0c11924e3f1543e1b0e4487be/lib/include/tree_sitter/api.h#L92-L96
https://github.com/tree-sitter/tree-sitter/blob/c7998d93d0d180e0c11924e3f1543e1b0e4487be/lib/src/node.c#L17-L28
And their counterparts in the Rust binding:
https://github.com/tree-sitter/tree-sitter/blob/c7998d93d0d180e0c11924e3f1543e1b0e4487be/lib/binding_rust/lib.rs#L78-L81
https://github.com/tree-sitter/tree-sitter/blob/c7998d93d0d180e0c11924e3f1543e1b0e4487be/lib/binding_rust/lib.rs#L716-L723
And the `Node:new()` caller place:
https://github.com/tree-sitter/tree-sitter/blob/c7998d93d0d180e0c11924e3f1543e1b0e4487be/lib/binding_rust/lib.rs#L652-L656

I see two pointers in the `TSNode` and no protection against that the referenced `TSTree` may be deleted in some other thread.
Such protection with reference counting exists only for the `TSTree` structure:
https://github.com/tree-sitter/tree-sitter/blob/c7998d93d0d180e0c11924e3f1543e1b0e4487be/lib/src/tree.c#L21-L24
https://github.com/tree-sitter/tree-sitter/blob/ad8bd3c3f50e41062db4e751532ae6115f05abd2/lib/src/subtree.c#L568-L573

---
**To be continued...**

**Comment by maxbrunsfeld** [comment]
A `Node` has a lifetime parameter that ties it to its `Tree`, so that lifetime will already statically forbid you from using the Node after the Tree is deleted. It will also forbid you from capturing a node in a closure passed to `thread::spawn` or similar, so I'm actually not sure what new patterns would be unlocked by making `Node` `Sync` and `Send`.

**Comment by dcreager** [comment]
`thread::spawn` has a `'static` bound like you say, but [`rayon::scope`](https://docs.rs/rayon/1.5.1/rayon/fn.scope.html) is an example of something similar that works with references to stack-allocated data.  We'd have to mark `Node` as `Send` to be able to use it in a fork/join model like that.  (Note that it _doesn't_ need to be `Sync`, since the `scope` call blocks until the forked tasks are done, so there's no concurrent access tot he `Node`.)

**Comment by maxbrunsfeld** [comment]
Yeah, that's a good example for why `Send` is useful. I think that it would be fine to make Node `Sync`, since it's an immutable object. Does that make sense?

**Comment by dcreager** [comment]
I think that's right.  It would be `!Sync` if you could use the `Node` instance to mutate tree-sitter's internal state, but that's not allowed.  Because of the atomic reference counting down in the C bits `Node` is equivalent to `Arc<internals>`, which would be `Sync`.
