### ISSUE TITLE
tree-sitter-cli does not allow C++11 language features in external scanners on macOS

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#1246]
See [this CI run](https://github.com/tlaplus-community/tree-sitter-tlaplus/actions/runs/1012002111) where the same grammar is built & tested in windows, ubuntu, and macOS. The build itself (via `npm install`) is fine; however, when `tree-sitter test` is run, it [fails on macOS](https://github.com/tlaplus-community/tree-sitter-tlaplus/runs/3020175648?check_suite_focus=true) with multiple errors of the following type:
```
/Users/runner/work/tree-sitter-tlaplus/tree-sitter-tlaplus/src/scanner.cc:144:37: error: non-aggregate type 'const std::vector<int32_t>' (aka 'const vector<int>') cannot be initialized with an initializer list
  static const std::vector<int32_t> THEN_TOKEN = {'T', 'H', 'E', 'N'};
```
Initializer lists are a C++11 feature that would be quite useful to have. Is the C++ standard version restricted on macOS somehow?

https://github.com/nvim-treesitter/nvim-treesitter/issues/1515 possibly related

**Comment by ahlinc** [comment]
Compilation flags and the whole building process currently is hard coded:
https://github.com/tree-sitter/tree-sitter/blob/0926fad1e2fdcd86d395934b55b7c4c8112c013b/cli/loader/src/lib.rs#L384-L401
And seems it should fail not only on macos.

**Comment by ahlinc** [comment]
As solution I'd suggest to support specifing flags in `package.json` in the `tree-sitter` scope key and use such flags for compilation by CLI and populating the `binding.gyp` file.

**Comment by alaviss** [comment]
Given that you're already hard-coding C99 mode into parser compilation, how about just hardcoding `-std=c++11` or `-std=c++14` for C++?

`-std=c++14` has been the default for all compilers but Xcode for quite a long time.

**Comment by clason** [comment]
Because you cannot hardcode a C++ standard in a mixed-language compiler invocation; I explained this to you before. There's a reason why scanners are being rewritten in C left and right. (All scanners? Well, not entirely... One indomitable scanner is holding out.)

**Comment by alaviss** [comment]
It is not an issue for tree-sitter-cli, is it? They do staged compilation so they are not burdened with this mixed language problem.

Same with how Helix, a tree-sitter empowered editor perform the compilation.

**Comment by alaviss** [comment]
@clason 

I'm fine with your personal decisions with regards to nvim-treesitter, but I would like to know how this upstream project and the ecosystem as a whole approach the C++ scanner issue.

Unless they really don't want to support C++ scanners, I don't see any reason to bend over backwards for one downstream user.

**Comment by amaanq** [comment]
There's a lack of understanding of upstream's goals, one of the main selling points of tree-sitter is portability, you might argue C99 is not really portable compared to ansi C/C89, but I think we can all agree no one's necessitating using that today.

Initially, writing logic for scanners seemed to be easier in C++ compared to C, which is why Max decided to use it for upstream parsers, and it very well still is easier, but this definitely kills portability in baremetal/wasm/other weird environments. As such, I've rewritten many scanners in C, array and string logic is not that difficult to achieve in C and if you genuinely *cannot* accomplish your scanner's logic in C rather than C++ I think you ought to not write a grammar, of course no hate to those currently in C++. 

Upstream will eventually even move towards removing the libc dependency to be even more portable (though this is a huge task), and will provide additional helper structs for string and vector logic, and helper functions similar to iswspace, isalpha, etc as that seems to be the *most commonly used* tools in a scanner (again to remove libc deps). It is a non-goal to introduce more runtime dependencies like libc++ and a c++ compiler (as well as a c++14 dependency, bleh)

There's just no need for C++ when it can be done in C

**Comment by alaviss** [comment]
I understand how you planned to handle this. And I do believe you should add something to the docs/CLI to discourage new parsers from writing in C++.

Are you planning to support something safer than C in the future? Right now C++ is the only *safer* choice (stricter types, range checked vectors and automatic memory management) when it comes to writing an external scanner, which is why I used it. Of course, the richer standard library is also a contributing factor.

> will provide additional helper structs for string and vector logic, and helper functions similar to iswspace, isalpha, etc as that seems to be the _most commonly used_ tools in a scanner (again to remove libc deps).

Is there an issue or PR that I can follow for this?

**Comment by ahlinc** [comment]
> Is there an issue or PR that I can follow for this?

It isn't exist yet, I'll write a proposal and let you know.

**Comment by ahelwer** [comment]
Seems that things here are moving away from C++ (which is fine, I rewrote my scanner in C for similar reasons to those posted elsewhere in this thread) so this can be closed.
