### ISSUE TITLE
QUESTION: Which libcompiler.a should I use?

### ISSUE THREAD

**Issue by campoy** [tree-sitter/tree-sitter#129]
Hi,

I'm getting started with tree-sitter and I've been running on a couple issues while trying to build bindings for Go.

In order to build the library I created a Docker image with the next `Dockerfile`:

```Dockerfile
FROM ubuntu

RUN apt-get update && apt-get install -y git python make build-essential
ADD . /usr/local/tree-sitter
WORKDIR /usr/local/tree-sitter
RUN script/configure && make
```

Once I have this, following the instructions on `README.md` to create a parser fails because there's more than one `libcompiler.a` file under `out`:

```bash
$ find out/Release -name libruntime.a
out/Release/libruntime.a
out/Release/obj.target/libruntime.a
```

Which one is the correct one? Is this expected?

Thanks!

**Comment by maxbrunsfeld** [comment]
Hmm, sorry that the docs aren't quite right. It seems that the build system that I'm using, `gyp`, behaves differently on different platforms in this regard. That `find` call was added because [someone reported](https://github.com/tree-sitter/tree-sitter/pull/110) that on Linux, the static library was getting put in `Release/obj.target` instead of `Release`. This is the first I've heard of it being put into *both* places. 

Do the two files differ? I would pick the one that's in the `Release` folder; on Mac, it always gets put there.

Also, in order to use the parsers from Go, you should only need `libruntime.a` (whose interface is defined in `runtime.h`), but not `libcompiler.a`, since the latter is only used for generating new parsers.
