### ISSUE TITLE
assert ranges in corpus tests ?

### ISSUE THREAD

**Issue by clojj** [tree-sitter/tree-sitter#134]
Is there a way to print or assert the ranges of rule-elements ?
If not, I think this might be a useful test feature.

**Comment by maxbrunsfeld** [comment]
Yeah, I've thought about this in the past. The hard part is coming up with a good interface for it that is simple enough. Right now, I think the tests are very simple to understand. *Usually* you don't need to assert about the ranges (because they are taken care of by the library). It's only really relevant for languages that use external scanners (because you must manually supply the boolean `skip` argument to `lexer->advance` to indicate whether characters are included or not).

My thinking right now is that people should simply write tests in JavaScript for the cases where the ranges matter. Do you have thoughts on a specific interface that would be useful and worth its complexity?

**Comment by CareyJWilliams** [comment]
Thought I'd post here as this is 6 years old and I wonder if things might have changed in this area.

I had a situation recently where a change to an **extra** rule caused a change only in whitespace. 
Corpus tests didn't pick this up as the node tree was still "correct".

However a diff comparing the output of a before/after change with `tree-sitter parse` (which does output ranges) picked it up:

```
<     (A [0, 3] - [0, 13]
<       (B [0, 3] - [0, 9]
<         (C [0, 3] - [0, 9]))
<       (B [0, 10] - [0, 13]
<         (C [0, 10] - [0, 13]))))
---
>     (A [0, 7] - [0, 13]
>       (B [0, 7] - [0, 9]
>         (C [0, 7] - [0, 9]))
>       (B [0, 11] - [0, 13]
>         (C [0, 11] - [0, 13]))))
```

I could manually wire up a test suite using parse and diff, but I was wondering if it might now be feasible to provide a `--ranges` option for `tree-sitter test` sort of inverse to `tree-sitter parse`'s [--no-ranges](https://github.com/tree-sitter/tree-sitter/pull/3687)? And whether there would be any appetite for this in the wider community?

This would be something I'd be happy to look at contributing.
