### ISSUE TITLE
Presumed Homomorphic Expectations Violated; Document or Change

### ISSUE THREAD

**Issue by byteit101** [tree-sitter/tree-sitter#1343]
From a theoretical point of view, I would expect `seq("a", "b")` to be the same as `/ab/`, and `repeat("a")` to be the same as `/a*/`, however the test case below shows that they are not homomorphisms in reality (probably due to lookahead?). This should either be changed so they are the same, give warnings if this would overlap and cause confusion, or, documented as being different. My thoughts reading the documentation prior to this discovery was that of rule atomicity, but that clearly isn't the case.

```js
module.exports = grammar({
    name: 'identifiers',
    extras: $ => [
    ],
    rules: {
        file: $ => choice( $.ident, $.multi_ident),
        multi_ident: $ => seq(repeat(/[a-zA-Z]/), '::', repeat1(/[a-zA-Z0-9]/)),

        //ident: $ => seq(/[a-zA-Z]/, repeat(/[a-zA-Z0-9]/)), // errors
        ident: $ => /[a-zA-Z][a-zA-Z0-9]*/, // works 
    }
});
```
Parsing any simple identifier works or always leads to errors, depending on which version is selected

Edit: Found another pair: `'$'` vs `/[\$]/`

**Comment by maxbrunsfeld** [comment]
This is the expected behavior. Tree-sitter generates a GLR parser and a lever. The grammar author is in explicit control over the boundary between the parser and the lever. By default, every string or regex is a token. If you want to delegate a larger rule to the scanner, you can wrap it in a call to ‘token()’, to indicate that it should be matched as a single token. The docs discuss this, in the section about the grammar DSL.

**Comment by byteit101** [comment]
> the section about the grammar DSL.

Ok, now that I have that context, I can see what those docs are implying, but it's non-obvious on first glance. Could a word about being atomic or such be added to make it more explicit for those without prior context?

Also, I'm struggling to see how that explains `'$'` vs `/[\$]/`?

**Comment by ahelwer** [comment]
I agree the documentation about external tokens vs. lexical precedence vs. global static precedence vs. partially-ordered static precedence vs. dynamic precedence could be better-fleshed-out, as could the documentation on how `extras` interact with all that - for me I've learned much tree-sitter behavior from looking at issues and discussions in this repo, and experimenting myself while watching the parser debug output. What happens with your `$` case?

**Comment by byteit101** [comment]
Same as above, one parses, one doesn't:

```js
module.exports = grammar({
    name: 'dollar',
    extras: $ => [ ],
    rules: {
        entry: $ => choice($.alpha, $.numeric),
        alpha: $ => seq('$', /[a-zA-Z][a-zA-Z0-9_]*/),
        //numeric: $ => seq(/[$]/, /[0-9]+/), // fails to parse
        numeric: $ => seq(/[\$]/, /[0-9]+/), // fails to parse
        // numeric: $ => seq('$', /[0-9]+/), // parse successful
    }
});
```
With input `$1234` it fails as commented, despite being unambiguous. It only parses correctly if both `$` tokens are of the same `[string, regex]` type. Mismatched, and only the string one will parse (make numeric a string and alpha a regex, and now `$abcd` fails to parse, but `$1234` parses)

**Comment by ahelwer** [comment]
Oh, I see. This is because of tree-sitter's ever-useful [conflicting tokens](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens) rules, specifically rule 4. So the `'$'` takes lexical precedence over `/[\$]/` or `/\$/`, and the parser is committed to that sequence of tokens.
