### ISSUE TITLE
Hangs in retrieving query results; Tree traversing degradation on nodes with enormous amount of children

### ISSUE THREAD

**Issue by gregnis** [tree-sitter/tree-sitter#1356]
I wrote a small app in C++ to test query functionality, specifically using C and C++ parsers. The query is:

**(function_definition) @functionScope
(class_specifier) @classScope
(struct_specifier) @structScope**

While it works for most test files, the test program hangs while querying one of TreeSitter language files, pascalabcnet-parser.c (it's a third-party file from (https://github.com/Lereena/tree-sitter-pascalabcnet which happened to be one of my test files; attached here: [pascalabcnet-parser.zip](https://github.com/tree-sitter/tree-sitter/files/7042714/pascalabcnet-parser.zip)). 

Specifically, the call

while (ts_query_cursor_next_match(cursor, &match))

hangs after finding some number of nodes, with either tree_sitter_cpp or tree_sitter_c parsers. I looked at the code but it's not easy to understand.

Thanks.

**Comment by gregnis** [comment]
Just wanted to check if there has been any progress on this. Thanks.

**Comment by maxbrunsfeld** [comment]
No, I still plan to debug this at some point, but haven't had time yet.

My suspicion is that something about this file is causing Tree-sitter's internal tree-balancing procedure to fail, so that the Tree becomes very deep and unbalanced, which makes it very slow to traverse.

I think the first step might be to get some visibility into the internal structure of the offending parse tree. We have a `--debug-graph` flag to `tree-sitter parse`, which will render the tree as a DOT graph, but unfortunately, that flag also renders every single parse stack configuration, so it is prohibitively slow to use on a large file like this.

I think we need to add some other CLI flag to `tree-sitter parse` that shows the *internal* structure of the parse tree (not just the visible nodes). Maybe a separate flag that *just* renders the final tree as DOT (not the parse stack diagrams during the parsing process).

**Comment by gregnis** [comment]
I did some testing in the Playground for the file in question, and while it's slow, it doesn't hang with the same queries I use in my code:

(namespace_definition) @namespaceScope
(class_specifier) @classScope
(struct_specifier) @structScope
(function_definition) @functionScope
(function_definition (operator_cast)) @operatorCastScope

(namespace_definition name : (_) @scopeName)
(class_specifier name : (_) @scopeName)
(struct_specifier name : (_) @scopeName)
(function_declarator declarator : (_) @scopeName)
(operator_cast) @scopeName

As I said earlier, for me it hangs in ts_query_cursor__advance called from ts_query_cursor_next_match called from my code. Is there something that is done in the Playground differently to get query results? That would be a good workaround for me.

**Comment by gregnis** [comment]
Any progress on this?

**Comment by dgutov** [comment]
You might want to try the latest master.

**Comment by gregnis** [comment]
Much better, thank you! No longer hanging on the files mentioned in the original post.

**Comment by maxbrunsfeld** [comment]
Thanks for the update @gregnis. I'm going to close this one out. Let me know if you hit other situations where query performance doesn't scale acceptably.
