### ISSUE TITLE
ts_node_child_by_field_* problematic in combination with anonymous nodes

### ISSUE THREAD

**Issue by Cu3PO42** [tree-sitter/tree-sitter#1526]
I have produced a grammar and corresponding input for which `ts_node_child_by_field_{name,id}` works *incorrectly*. I derive my understanding of the expected behavior not only from intuition, but also from the output of `tree-sitter parse`.

In order to investigate this issue, I have created a fairly minimal grammar with which the behavior can be observed. It is as follows:
 ```js
module.exports = grammar({
    name: 'expressions',
    rules: {
        source_file: $ => $._expr,
        _whitespace: $ => /\s+/,

        _expr: $ => choice(
            $.and,
            $.identifier,
            $._brackets,
        ),

        and: $ => prec.left(seq(field("left", $._expr), "AND", field("right", $._expr))),
        identifier: $ => /[_\w][\w_\d]*/,

        _brackets: $ => seq("(", $._expr, ")"),
    },

    extras: $ => [$._whitespace],
})
```

On the input `( (FOO) AND BAR )`, the output of `tree-sitter parse` is
```
(source_file [0, 0] - [0, 17]
  (and [0, 2] - [0, 15]
    left: (identifier [0, 3] - [0, 6])
    right: (identifier [0, 12] - [0, 15])))
```

This also corresponds to my intuition on the expected behavior. However, when programmatically querying for the child labeled `left` of the `and` node, I get the token corresponding to the second opening bracket, i.e., the first child of the hidden  `_brackets` node rather than its only named child.

I believe that I have tracked down the incorrect code to [a snipped in `node.c`](https://github.com/tree-sitter/tree-sitter/blob/master/lib/src/node.c#L551-L559). My understanding is that since `_brackets` is anonymous, it is not *relevant*. Therefore the code returns the first child, I believe this code should be changed to return the first non-anonymous child instead.

I have compiled a [demo repo](https://github.com/Cu3PO42/tree-sitter-issue-demo) including all necessary parts to observe this behavior.

* The Tree-Sitter parser lives in the `parser` subdirectory.
* `parser/examples/foo` contains the input I used
* The main directory includes minimal Rust code accessing the node in question and logging its start and end position.

**Comment by maxbrunsfeld** [comment]
This is the current expected behavior: you're allowed to put fields on anonymous nodes, and you're also allowed to put a the same field on multiple children. So if you apply a field to a hidden node (e.g. `_brackets`), that behaves as if you'd applied to the field on *all* of that node's children. The anonymous `"("` and `")"` nodes don't show up in the output of `tree-sitter parse`, but they both have the `left` field applied to them.

Originally I considered making it a compile-time error to put a field name on a hidden node with multiple children, but it seemed like  you might sometimes do that intentionally.

I think in this case, the fix would be to make the `_brackets` node visible. That will make your syntax tree have a more stable schema, because an `and` will  always have three children (instead of its child count changing if one operand is parenthesized).

**Comment by Cu3PO42** [comment]
Thank you for the reply. It was my understanding that field names on anonymous nodes were essentially a no-op, hence the confusion.

Indeed, I fixed the problem by making `_brackets` visible and adjusting code on my end accordingly.
