### ISSUE TITLE
Why the length of string in Tree-sitter is uint32_t size?

### ISSUE THREAD

**Issue by cireu** [tree-sitter/tree-sitter#1609]
Many C library assume that the length of string should be a `size_t` type. e.g. `strlen` `strncmp` `strncpy`.

Use a `uint32_t` type for the length of string in tree-sitter is quite cumbersome, the caller of tree-sitter should check their length and make sure it doesn't overflow before passing an argument to tree sitter function.

Is there any techincal prevent us from using `size_t` for the length of string in `ts_parse_input` `ts_parse_string` function?

**Comment by alemuller** [comment]
It is pretty safe to assume overflow won't happen. A length greater than `UINT32_MAX` is likely a bug elsewhere on the code.

I had a look at the tree-sitter code on past, so I speculate this was done to improve 1) cache alignment and 2) cache locality.

1) With fixed size types you have control on the size of the data structure, and therefore, can define structure that will fit in the cache line boundary.
2) Using larger type, less data would fit into lower levels of caches, and since it doesn't make sense for lengths to be greater than `UINT32_MAX`, a lot of spaces would be wasted just storing zeros.

There are some benefits (and setbacks) on portability.

There are some others constraint that would likely stop your code before hitting the limit of `uint32_t` for instance the size of the buffer.

I don't think there will be a performance hit on doing overflow check at every conversion (I find hard to believe the bottleneck is on the CPU backend).

If you really care about overflow check, there is likely a flag/attribute/directive/something for the compiler to instrument your code without the need to write code for it manually.

**Comment by maxbrunsfeld** [comment]
Yeah, Tree-sitter isn't designed to operate on source files > 4 gigabytes in size. For such a large file, the syntax tree would have an extremely large memory footprint. And as @alemuller said, there are real performance benefits to using a smaller integer representation, since every node in the syntax tree stores multiple of these lengths. The speed and memory savings are very significant.
