### ISSUE TITLE
tree_sitter::QueryMatches appears to mutate the match

### ISSUE THREAD

**Issue by BrianHicks** [tree-sitter/tree-sitter#1656]
As of tree-sitter 0.20.4, if I have code like this:

```rust
let mut cursor = QueryCursor::new();
let matches = cursor
    .matches(&some_query, some_node, some_source_bytes)
    .collect::<Vec<QueryMatch>>();
```

… then if I have multiple distinct matches, all the matches in `matches` will be identical. This makes me think that the `QueryMatch` is being mutated somewhere. I'm not surprised that the `QueryCursor` is mutated here, but I'd like to get a list of distinct matches and select one randomly (I'm building a mutation testing tool.)

Is this a bug or intended behavior? If it's intended, I'd love some suggestions for how to get around needing a list of matches. (I don't particularly care if they're overlapping, just distinct.)

**Comment by BrianHicks** [comment]
mm, found my own workaround:

```rust
let matches = cursor
    .matches(&some_query, some_node, some_source_bytes)
    .map(|m| (m.pattern_index, m.captures.to_owned()))
    .collect::<Vec<(usize, Vec<QueryCapture>)>>();
```

Not as nice as I'd like, but I suppose it's basically what I'm asking for the crate implementation to do in terms of allocation. 🤷

**Comment by maxbrunsfeld** [comment]
Yeah, sorry about this bug. We have an open issue about it: https://github.com/tree-sitter/tree-sitter/issues/608

The problem is that the `QueryMatch` objects borrow from the cursor, so the lifetime is technically not correct. The solution I think would be to remove the `Iterator` implementation for `QueryMatches`, and instead implement some similar trait like [`streaming_iterator`](https://docs.rs/streaming-iterator/latest/streaming_iterator). It would just be a bit less convenient to use.

In the long term, after [GATs are added to Rust](https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html#so-what-are-gats), I hope some trait like `LendingIterator` will be added to `std`, and we can switch to that.

**Comment by BrianHicks** [comment]
ahh, ok. I thought I had searched around enough but didn't find that one! Will close this.

I'm not 100% confident about lifetime logic yet. It seems like what I'm doing should be safe based on what I know, but does it strike you as being potentially unsafe?
