### ISSUE TITLE
How to publish tree-sitter-xxx to npm

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter#174]
During the development, I had [tree-sitter-agda](https://github.com/banacorn/tree-sitter-agda)  listed as a dependecy of [language-agda](https://github.com/banacorn/language-agda) with `package.json` like this, so that I can test it on my machine:
```
  "dependencies": {
    "tree-sitter-agda": "~/PATH/TO/tree-sitter-agda"
  },
```

As I think it's about time to make it available to everyone, I published `tree-sitter-agda` to npm, so the `package.json` of `language-agda` now look like this:

```
  "dependencies": {
    "tree-sitter-agda": "^1.0.3"
  },
```

It worked out fine, but as I open Atom, this good old version compatibility error message popped up:
```
The module '.../github/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). in .../.atom/dev/packages/language-agda/grammars/tree-sitter-agda.cson
```

I know I should run `apm rebuild` on `language-agda` to make it compatible, but it makes me wonder, am I doing it right? 
How can I enforce `apm rebuild` every time after people have installed `language-agda`?

**Comment by maxbrunsfeld** [comment]
Users who install `language-agda` shouldn't need to run `apm rebuild`. That's only necessary in a couple of cases:

1. You switch from testing the parser with `node` to using it in Atom
2. You upgrade to a new version of Atom that uses a newer version of Electron.

One exciting development: Atom 1.28 will use the same version of V8 as node v8.4, so if you use Atom 1.28 and node 8.4, you can avoid having to recompile native modules when switching between testing in node and Atom. It has been really nice for my workflow recently.

Also, very nice work on tree-sitter-agda 👏 ! If you're ever interested, you're welcome to put that repo into the Tree-sitter org in GitHub in order to help others find it and potentially collaborate on it.

I'm going to close this out, but let me know if you have any more questions about this.

**Comment by banacorn** [comment]
That's great! Can't wait to give Atom 1.28 a try!

Also, I'll transfer the repo to the tree-sitter org! 😉

**Comment by banacorn** [comment]
```
You don’t have the permission to create repositories on tree-sitter
```
I think I'm having some trouble transferring it...

**Comment by maxbrunsfeld** [comment]
Ok, I sent you an invite to the org. I think that will let you do the transfer.
