### ISSUE TITLE
Incremental parsing on git history

### ISSUE THREAD

**Issue by szabta89** [tree-sitter/tree-sitter#1792]
This is more of an inquiry about additional info or docs on the topic, rather than an actual bug. 

I am experimenting with the incremental parsing functionality of tree sitter. My goal is to extract AST differences when taking two versions of the same file, e.g. from consecutive pairs of commits from a git history. I am having trouble with communicating the textual edits to tree sitter. 

I have looked at the API, and I found that I would need to provide the changes both in terms of the byte stream and the character positions. Imagine that I have added two new lines (L1, L2) in the new commit (NC) compared to the parent/old commit (OC) in some far away parts of the source file. Let's call the rows where the insertions happened L1R and L2R. When I describe the edit to tree sitter for L1, I can compute the new positions. However, it is not clear to me if I need to specify the addition of L2 with coordinates that are relative to the state of the file in OC or relative to a version of the file in OC that also has now L1 in it (as communicated by the previous edit). This can get even more complicated if there are multiple edits and other kind of changes (deletions, modifications). In general, I fear that this kind of use case is not really supported by the current API. I guess the envisioned use case is really about text editors where the changes are immediately communicated after every keystroke. Is this really the case? 

Apart from the specific question above, I would be curious to see some example usages of the incremental parsing API. Could you please point me to something? Are there maybe concrete scenarios/tests that demonstrate the use of the API? 

Thanks a lot for the help.

**Comment by ahelwer** [comment]
I think the API only allows one section to be added or removed for any given edit, so you would have to calculate the offset with the prior edits in the file included.

**Comment by szabta89** [comment]
Yeah, that is my thinking too. Probably for my purposes, it will be actually better to just construct the two ASTs and then do the diffing on my own.

**Comment by ahelwer** [comment]
Actually I did some experimenting and I think you can actually add multiple edits to the same tree all using the offsets of the original tree; see the example here: https://github.com/tlaplus-community/tlaplus-tool-dev-examples/blob/rust-edit/tree-sitter/rust/src/main.rs

However it's a bit tricky to figure out whether this is really the case because if you provide the wrong edit location to the API it doesn't fail or anything, it just doesn't re-parse outside of that area.

**Comment by maxbrunsfeld** [comment]
When analyzing at a git history, I don't think incremental parsing would be useful. Incremental parsing is for when you know the exact changes that took place between two documents. With git history, all you know are the old and new documents: `git diff` **derives** the edits by doing a comparison between the documents.

Like you said, I think it for this use case it would make more sense to parse the old and new documents separately and compare the two trees.

**Comment by maxbrunsfeld** [comment]
Regarding the mechanics of providing multiple edits though: I'd like to add an optimized API for applying a batch of edits, but right now you can only apply one at a time, sequentially. So given a diff containing multiple edits which are conceptually indepenedent, you'd probably want to iterate over the edits in *reverse* and apply them to the syntax tree one by one (so that a given edit does not affect the coordinate space of the following edits).

**Comment by szabta89** [comment]
Regarding incrementality vs git history: I would argue that incrementalization in general can bring performance improvements if we can compute precise/small enough deltas. Even in the case of commit-style changes, typically the program change is small compared to the entire size of the code base. In my use case, I employ a static analysis on top of the AST computed by tree sitter, so incrementalization would be useful. 

Nevertheless, I acknowledge that, at least for now, I am better off with just diffing the two ASTs. Thanks for all the inputs.
