### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by anp** [tree-sitter/tree-sitter#182]
Hi! Looks super cool. Just wanted to point out this mismatch between the README description of the project and GitHub's rendering of the languages included:

![readme_screenshot](https://cl.ly/221e1I0P1C1w/Screen%20Shot%202018-06-21%20at%205.30.25%20PM.png)

**Comment by maxbrunsfeld** [comment]
Yeah, I can see how that would seem odd. It's not a typo, but maybe I should qualify it.

The C++ code is used in the `libcompiler` library which is a build tool for *generating* parsers. The only time you'd need to compile or run this code is when you are creating a new parser.

In order to actually *use* the parsers, you don't need this library; you only need the `libruntime` library. This library is written in pure C which makes it very easy to embed in any application.

**Comment by maxbrunsfeld** [comment]
Maybe I should change it to:

* **Dependency-free** with a runtime written in pure C so that it can be embedded in any application

**Comment by anp** [comment]
Ah, that makes so much more sense. From a quick read I actually didn't catch on to the fact that tree-sitter is a build-time parser generator + a runtime library. Maybe clarifying that central bit of architecture would be the least confusing path?

**Comment by maxbrunsfeld** [comment]
Ok, updated the README and docs site to indicate right at the beginning that there are two parts to Tree-sitter. Thanks for the suggestion!
