### ISSUE TITLE
How to get the representation of the current node?

### ISSUE THREAD

**Issue by wongjiahau** [tree-sitter/tree-sitter#186]
Based on the [API documentation](http://tree-sitter.github.io/tree-sitter/using-parsers#querying-the-syntax-tree), one can only query the following things from a tree:

1. Child count of a node
2. Type of the node
3. Token location of the current node
4. Print the syntax tree as S-Expression

But, how do I access the representation of the current node?

For example, the only thing I get from a node is something like the following: 
```js
TreeCursor {
  nodeIsNamed: true,
  nodeType: 'number',
  endIndex: 1,
  startIndex: 0,
  repr: "99" // <-- This one is missing
}
```
So, is there any function that can access that?

**Comment by maxbrunsfeld** [comment]
There currently is not a built-in API for getting a node's text, but it is trivial to get the text since you have the node's `startIndex`, `endIndex`, `startPosition` and `endPosition`.

Tree-sitter does not retain a copy of the text itself; it just provides you with the syntax tree. For efficiency/flexibility reasons, in case where you are parsing large files, I don't assume that you want to retain a copy of the text as a string. For example, you might have the text stored in some other data structure and it would be undesirable for Tree-sitter to maintain its own copy of the text as a string.

If you want to do add a `text` accessor to the `SyntaxNode` class though, you can do it in whatever way fits your app. For example, if you have the text stored in a simple string, you can do this:

```js
const Parser = require('tree-sitter');

Object.defineProperty(Parser.SyntaxNode.prototype, 'text', {
  get () {
    return this.tree._text.substring(this.startIndex, this.endIndex);
  }
});

// when parsing:
const newTree = parser.parse(sourceCode, oldTree)
newTree._text = sourceCode
```

**Comment by wongjiahau** [comment]
@maxbrunsfeld Noted, is there a possibility that this feature will be included in the future? Because to get the node representation using `substring` might have a performance hit on code generation, of course to have the text embedded within the syntax tree might hurt memory.

**Comment by maxbrunsfeld** [comment]
Actually, we've decided to make this functionality built-in. Subscribe to this PR for updates: https://github.com/tree-sitter/node-tree-sitter/pull/20.
