### ISSUE TITLE
Markdown code block start and end line is concealed.

### ISSUE THREAD

**Issue by pteroctopus** [tree-sitter/tree-sitter#1933]
Markdown code block start and end line is concealed.

so:
```
```language # not visible has @conceal highlight group
# visible
``` # not visible
```

Features like this should be opt-in not opt-out.

"Feature" was added here: https://github.com/nvim-treesitter/nvim-treesitter/issues/2663

Markdown file is a text file. To edit it we must see the text.
If somebody wants to see it rendered there are other ways of doing it.

For me it is a problem to edit lines I can't even see. I don't see the point of hiding that text :)

Please make it opt-in. This doesn't make any sense.

![Alas, I cannot see](https://user-images.githubusercontent.com/16186848/198032199-8792204b-089b-491b-a301-615444028200.png)

**Comment by gennaro-tedesco** [comment]
I agree: the majority of users will unawarely spend a lot of time trying to understand why they do not see the text: the text being concealed isn't the first thing that comes to mind.

**Comment by pteroctopus** [comment]
Yes. It took me a few hours to get to the bottom of this. First I thought it was a bug on neovim or parser. Updated everything etc.... Tried to disable conceal and in the end filed a bug here.

**Comment by MDeiml** [comment]
Haha, I'm really sorry, but as I said it's a issue with [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) (not tree-sitter). But I agree that the naming around the whole of tree-sitter is confusing since everything has almost the same name.

Basically tree-sitter is the library to write parsers, Repos like tree-sitter-markdown then contain the specific parsers for languages and nvim-treesitter is the integration of those parsers into neovim. You want the last one :wink:

**Comment by pteroctopus** [comment]
:-) I'll report it to nvim-treesitter tommorow and post a link here. Currently don't have access to my neovim to generate additional data they need to be able to submit the issue.

Please if you think text shouldn't be concealed by default put you comment of agreeing there so that concealing of text doesn't become the new fashion.

**Comment by pteroctopus** [comment]
I have reported this bug to nvim-treesitter as pointed out by @MDeiml . This one will be closed.
If any one stumbles upon this issue please submit your opinion on: https://github.com/nvim-treesitter/nvim-treesitter/issues/3723
