### ISSUE TITLE
Simple whitespace regex behaves differently than string

### ISSUE THREAD

**Issue by JWalker1995** [tree-sitter/tree-sitter#194]
I really like tree-sitter so far, but I can't figure out why this isn't working:

```js
module.exports = grammar({
  name: 'test',

  extras: $ => [],

  rules: {
    source_file: $ => seq(/\s*/, $._expression, /\s*/),

    _expression: $ => choice(
      $.ident,
      $.function_call,
    ),

    ident: $ => prec.left(0, token(/[a-zA-Z_][a-zA-Z0-9_]*/)),

    function_call: $ => prec.left(1, seq($._expression, /\s+/, $._expression)),
  }
});
```

```
==================
Function call
==================

func arg

---

(source_file
  (function_call (ident) (ident))
)
```

```
  source_files
    ✗ Function call
        »
        actual expected

        (source_file (function_call (ident) (ERROR (ident)))
         // macros.js:14

✗ Broken » 1 broken (0.006s)
```

This is the actual: `(source_file (ident) (ERROR (ident)))`

When I replace the `/\s+/` in `function_call` with a literal string (`' '`), it works fine.

**Comment by maxbrunsfeld** [comment]
Hey @JWalker1995,

I think the problem is that there are two different tokens in your grammar that both match whitespace and are both valid after the first identifier: the `/\s*/` token in `source_file`, and the `/\s+/` token in `function_call`.

Even though the grammar is written in one unified place, it helps to keep in mind the division between the parser and the lexer. After the word `func`, the lexer sees some whitespace and it has to decide which of those two tokens to return. If there are two tokens that both match with the same length, the lexer will prefer the string token over the regex token. Otherwise, it has to arbitrarily decide based on the order of the rules in the grammar.

I *think* that you don't want the lexer to have to make this decision; instead, you want there to be only one token that represents whitespace, so that the lexer can omit that token, and the parser can decide how to interpret it once the parser has seen the *next* token.

I'd suggest that you rewrite `source_file` to use the same whitespace token as `function_call`:

```js
source_file: $ => seq(
  optional(/\s+/),
  $._expression,
  optional(/\s+/)
)
```

It may seem like a meaningless change, but to Tree-sitter, the way that a rule is broken down into strings and regexes affects how the grammar is divided between the parser and the lexer, which can affect the user-facing behavior.

Hope this makes sense!

**Comment by JWalker1995** [comment]
Thank you, that's very helpful!
