### ISSUE TITLE
Switch to jsonnet instead of javascript for grammar writing

### ISSUE THREAD

**Issue by aryx** [tree-sitter/tree-sitter#1988]
@maxbrunsfeld have you considered using jsonnet instead of javascript to write the grammar.js files?
I like the flexibility a programming language offers to define a grammar (you can defined helper functions
on the grammar, e.g., emulating EBNF with regular functions), but javascript imposes a big dependency on
how to compile/package tree-sitter grammars.
There is now a jsonnet interpreter written in Rust https://github.com/CertainLach/jrsonnet
so we could switch to jsonnet which is a very nice sandboxed powerful programming language.

**Comment by aryx** [comment]
cc @mjambon

**Comment by maxbrunsfeld** [comment]
Personally, I'd be in favor of keeping JavaScript, but removing the Node.js dependency by using the now-standard `import/export` syntax for importing and exporting grammars, instead of using Node's `require` and `module.exports`. Then we could use any standard JavaScript runtime, like Node.js or Deno if they are installed, or QuickJS, which has a very small footprint.
