### ISSUE TITLE
vendored webbrowser is affected by CVE-2022-45299

### ISSUE THREAD

**Issue by mcepl** [tree-sitter/tree-sitter#2042]
See https://github.com/offalltn/CVE-2022-45299:

> Affected library: webbrowser.rs before version 0.8.3

tree-sitter uses 0.5.5.

**Comment by sogaiu** [comment]
I think may be that text meant "up to and including 0.8.3", at least according to: https://github.com/amodm/webbrowser-rs/issues/60#issuecomment-1368285283.

So if a change is going to be made, may be choosing at least `0.8.4` makes sense?

I tried changing `cli/Cargo.toml` so that:
```
diff --git a/cli/Cargo.toml b/cli/Cargo.toml
index 5403075d..7e463475 100644
--- a/cli/Cargo.toml
+++ b/cli/Cargo.toml
@@ -37,7 +37,7 @@ serde = { version = "1.0.130", features = ["derive"] }
 smallbitvec = "2.5.1"
 tiny_http = "0.12.0"
 walkdir = "2.3"
-webbrowser = "0.5.1"
+webbrowser = "0.8.4"
 which = "4.1.0"
 
 [dependencies.tree-sitter]
```
and rebuilt.

Then I tried the `playground` subcommand.  It seemed to work ok.

AFAICT, that's the only place `webbrowser` seems to be used:
```
$ rg webbrowser
src/playground.rs
11:use webbrowser;
64:        if let Err(_) = webbrowser::open(&url) {

Cargo.toml
40:webbrowser = "0.8.4"
```

@ahlinc What do you think?

**Comment by ahlinc** [comment]
It's worth to updated this dependency in any case, but tree-sitter isn't actually affected by this CVE as there is no possibility to pass random string to the affected `open` method and so no reason to release a new version for the CLI.

**Comment by ahlinc** [comment]
It was updated.
