### ISSUE TITLE
ts_tree_edit: can I use only TSPosition and no bytes?

### ISSUE THREAD

**Issue by bfredl** [tree-sitter/tree-sitter#210]
The documentation for editing says:
>In applications like text editors, you often need to re-parse a file after its source code has changed. Tree-sitter is designed to support this use case efficiently. There are two steps required. First, you must edit the syntax tree, which adjusts the ranges of its nodes so that they stay in sync with the code.

```
typedef struct {
  uint32_t start_byte;
  uint32_t old_end_byte;
  uint32_t new_end_byte;
  TSPoint start_point;
  TSPoint old_end_point;
  TSPoint new_end_point;
} TSInputEdit;

void ts_node_edit(TSNode *, const TSInputEdit *);
```

Say that I'm only interested in TSPoint values for nodes (and will only use the TSPoint argument to TSInput), can I supply only `start_point` et al and leave the byte values to zero? Or will this make TS internal state inconsistent somehow?  In my usecase I already have the `(row,col)` values for free, but calculating the byte offset would require looping over all lines (or adding an extra data structure only for it).

Also I assume `ts_tree_edit()` is equivalent to editing the top node? I e tree-sitter will figure out the relevant nodes itself.

**Comment by maxbrunsfeld** [comment]
I have never tested what would happen if you just didn't specify the byte offsets (e.g. left them at zero, or at arbitrary values). I'm guessing that currently, there would be problems, because Tree-sitter currently uses nodes' byte offsets for comparing positions.

What editor are you using? Is it vim? I would think that a text editor would already need to have an efficient way of converting between row/column coordinates and raw bytes. Like vim has a built-in `line2byte` function I believe.

**Comment by maxbrunsfeld** [comment]
It's also possible that we could update Tree-sitter to make the byte offsets optional. I'm not sure how much work it would be. If you're interested in testing and investigating that, that'd be great.

**Comment by bfredl** [comment]
> What editor are you using? Is it vim? I would think that a text editor would already need to have an efficient way of converting between row/column coordinates and raw bytes. Like vim has a built-in line2byte function I believe.

Good question. From `line2byte`, I took a peak into vim:s `memline.c` and it seems it stores byte size of blocks in its tree based datastructure. So it is probably more line `O(log N)` than `O(N)` which I first thought, but the code is too complex for me to give a quick definite answer :P

> It's also possible that we could update Tree-sitter to make the byte offsets optional. I'm not sure how much work it would be. If you're interested in testing and investigating that, that'd be great.

I'll be happy to take a look. As documentation still is a bit scarce, I guess reading the source of the runtime library is helpful anyway to figure out the details of usage.

**Comment by maxbrunsfeld** [comment]
> So it is probably more like `O(log N)` than `O(N)`

That matches my understanding, and is similar to the performance of line <-> byte conversions in Atom. AFAICT, the cost of these conversions are pretty insignificant in our case.

**Comment by maxbrunsfeld** [comment]
> I'll be happy to take a look. As documentation still is a bit scarce, I guess reading the source of the runtime library is helpful anyway to figure out the details of usage.

Yeah, apologies for the scarcity. I would very much like to improve the docs, and I'd be happy to answer any questions you have.

If you *are* developing a vim plugin though, I would probably recommend starting out by computing the byte offsets. I think that only one `line2byte` call should be needed per edit, assuming that you have access to the deleted text and inserted text when the buffer changes.

**Comment by bfredl** [comment]
> If you are developing a vim plugin though, I would probably recommend starting out by computing the byte offsets. I think that only one line2byte call should be needed per edit, assuming that you have access to the deleted text and inserted text when the buffer changes.

Yes, or rather I will use neovim's buffer change events (currently RPC only, but adding internal lua callbacks shouldn't be that much work), which unfortunately only have line resolution so far, but I can ad-hoc calculate the shared prefix and suffix for now, and proper column-resolution information is planned for later (https://github.com/neovim/neovim/pull/5031).

**Comment by maxbrunsfeld** [comment]
Awesome. Great to hear that you're working on Neovim integration.

**Comment by bfredl** [comment]
Still mostly on the idea stage, but I hope to find time to work on it soon. I've gotten so far as importing the library into the luajit runtime :P I guess this can be closed for now, as byte indexing will be no problem.

**Comment by bfredl** [comment]
@maxbrunsfeld I think I've got edit positioning kind of working now.  There is a slight remaining issue though: in a nvim buffer edit event, only the byte size of the new text is known, not the byte size of the replaced text (only the number of changed lines). The information _should_ be available in the internal vim undo storage, but might not be as trivial as "just look into the last undo snapshot" to get it, as a single vim undo item will likely correspond to multiple edit events.

I'm currently using the following hack: look up the first node in the old TS tree _after_ the end of the edited region, and ask for its byte position, and also ask nvim for the byte size of this extra region after the real edit region. Now I can compute self-consistent ranges for this extended region (edit + padding to next node), which I think should be semantically equivalent as there is no nodes in the extra area?

I'm wondering if `ts_node_descendant_for_point_range` has its arguments logically reversed? It seems to work if I set `min` to a very large value, and `max` to the start position, but not the other way which I would expect.

Also IIUC it uses linear search for the children at every level, would it be feasible to implement binary search? I would be happy to give it a try, but maybe it is difficult with the current data structure (if positions are sibling-relative and not parent-relative).

**Comment by maxbrunsfeld** [comment]
> I'm wondering if `ts_node_descendant_for_point_range` has its arguments logically reversed?

The intended behavior of the function is to find the smallest possible syntax node that *fully contains* the given range; so I'm not sure that function is what you need for the workaround you're describing.

> Also IIUC it uses linear search for the children at every level, would it be feasible to implement binary search?

It does use linear search, but I don't think that should be a problem, because in order to enable incremental parsing, long sequences of child nodes are already stored in a balanced binary tree. For example, this is how the syntax tree is structured for a ruby file containing one big array literal with 30 elements:

![balanced-syntax-tree](https://user-images.githubusercontent.com/326587/47805057-959c1d00-dcf3-11e8-93dc-73fc3a5303c1.png)

So in cases like these, where there are long sequences, there are only two child nodes at most levels.

**Comment by maxbrunsfeld** [comment]
It sounds like we should add methods like `ts_node_last_token_before_point` and `ts_node_first_token_after_point`. Is that the functionality that you need?

**Comment by bfredl** [comment]
> It does use linear search, but I don't think that should be a problem, because in order to enable incremental parsing, long sequences of child nodes are already stored in a balanced binary tree. For example, this is how the syntax tree is structured for a ruby file containing one big array literal with 20 elements

I kind-of suspected something like this was done, but didn't dig deep enough to find it, thanks for clarifying.

**Comment by bfredl** [comment]
> ts_node_first_token_after_point

Yes, I  think that would be it, I guess my abuse of the `descendant_for_byte_range` function emulates that. We could of course also cache the latest such used node on the nvim side, as the most common event will be yet an edit on a line that just was is edited.

**Comment by bfredl** [comment]
>  if you're interested in adding them via PR, that would be great too.

I might give it a try, soon.

**Comment by TheBB** [comment]
> Also I assume `ts_tree_edit()` is equivalent to editing the top node? I e tree-sitter will figure out the relevant nodes itself.

Did this get answered? I'm curious myself. `ts_tree_edit` looks like it does a *lot* more than `ts_node_edit` does.

**Comment by Pyromuffin** [comment]
sorry to bring up an old issue.
I'm writing a tree-sitter based language server and the language server protocol only gives row/column edit information, so this issue is relevant to me. I'm currently going to somewhat great lengths to calculate the byte-offset of a change from a row/column edit. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didChange only gives range information (which is row/col) for a document change notification.
 
It would be very handy to have a ts_tree_edit that worked with only row/column information, or a call to calculate the byte offset for a certain TSPoint.
