### ISSUE TITLE
Tree sitter precedence doesn't work as expected

### ISSUE THREAD

**Issue by ilevyor** [tree-sitter/tree-sitter#2152]
In the following simplified grammar:
```js
  module.exports = grammar({
    name: 'foo',
    rules: {
      source_file: ($) => // $._block,
        seq(field('root', seq($._block, repeat(seq($._sep, $._block)), optional($._sep)))),
      _block: ($) => choice($.if_clause, $.name),
      if_clause: ($) =>
          seq(
            'if',
            field('if', seq('(', $.bool, ')')),
            field('then', $.name),
            field('else', optional(seq('else', $.name))),
          ),
      bool: ($) => 'true',
      name: ($) => /[A-Za-z]+/,
      _sep: ($) => token(choice(',', '\n')),
    },
  });
  ```
  parsing 
  ```
if (true)
    Bar
else
    Bar
 ```
 results in 
 ```
root: (if_clause [0, 0] - [1, 5]
  if: (bool [0, 4] - [0, 8])
  then: (name [1, 2] - [1, 5]))
root: (name [2, 0] - [2, 4])
root: (name [3, 2] - [3, 5]))
```
instead of
```
(source_file [0, 0] - [3, 5]
  (if_clause [0, 0] - [3, 5]
    if: (bool [0, 4] - [0, 8])
    then: (name [1, 2] - [1, 5])
    else: (name [3, 2] - [3, 5])))
```
which you can get by replacing the source file definition with the commented out block.
referring to the [conflicting tokens](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens) section of the docs I would think that match specificity would prefer the keyword, but maybe earliest starting position is dominating? I'm not sure how I understand this differentiator.

**Comment by sogaiu** [comment]
Possibly there's something going on with the newline in `_sep`.

I found this about `extras`:

> extras - an array of tokens that may appear anywhere in the language. This is often used for whitespace and comments. The default value of extras is to accept whitespace. To control whitespace explicitly, specify extras: $ => [] in your grammar.

IIUC, by default whitespace includes newlines in the context of tree-sitter.  I reached this conclusion by looking at: https://github.com/tree-sitter/tree-sitter/blob/1b1c3974f789a9bfaa31f493e6eaa212f13bdfb9/cli/src/generate/dsl.js#L221 and thinking that `\s` includes newlines [1].

Perhaps there is some interaction going on here between the `extras` value (since not specified, presumably the default value(s) apply).

I tried changing the `_sep` definition to just be `token(',')` and got the following result for the `parse` subcommand:
```
$ tree-sitter.0.20.7 parse sample 
(source_file [0, 0] - [4, 0]
  root: (if_clause [0, 0] - [3, 5]
    if: (bool [0, 4] - [0, 8])
    then: (name [1, 2] - [1, 5])
    else: (name [3, 2] - [3, 5])))
```

---

[1] For example, via MDN:

> Matches a single white space character, including space, tab, form feed, line feed, and other Unicode spaces. Equivalent to [\f\n\r\t\v\u0020\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]. For example, /\s\w*/ matches " bar" in "foo bar".

**Comment by ObserverOfTime** [comment]
I don't see how this is an issue. Different implementations result in different trees.
