### ISSUE TITLE
Gmrightkenja

### ISSUE THREAD

**Issue by GeorgeMAKULU** [tree-sitter/tree-sitter#218]
How to write code in the languages I want it to run on and how to bring something dead to live

**Comment by rsese** [comment]
Thanks for reaching out!  If you're having a specific problem with Tree-sitter, please let us know and share as much detail as you can.

Otherwise for most questions about Atom and Tree-sitter there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
