### ISSUE TITLE
Builtin support for white space sensitive languages

### ISSUE THREAD

**Issue by maxnordlund** [tree-sitter/tree-sitter#219]
Hi, first let me say that this is super exciting to see and I hope this will spread to other editors and beyond.

I noticed that the recommended way to support white space sensitive languages is to [bring your own lexer](https://github.com/tree-sitter/tree-sitter-python/blob/master/src/scanner.cc).

I know indentation isn't parsable by GLR, or any context-*free* grammar, as it's fundamentally context dependent even though this special case is fairly beign. But this seems to be a fairly common scenario, not just for python, ruby and haskell (that I deduced have custom lexers).

I also think there's the potential to use indentation for error recovery. If you know that your parsing a block/statement you can look at the indentation to figure out where the closing bracket/`end`/... should go:

```js
function filter(iterable, fn) {
  let i = 0, result = []

  for (let value of iterable) {
    if (fn(value, index++, iterable)) {
      result.push(value)
    }
  
// ^ Missing curly bracket here, (clearly) visible by looking at the indentation
}
```

Anyway that's just a thought. What do you think about adding support for parsing indentation to tree-sitter?

---

## List of indentation based languages:

- Python
- Haskell
- YAML
- CoffeeScript
- LiveScript

**Comment by maxbrunsfeld** [comment]
Thanks!

> I noticed that the recommended way to support white space sensitive languages is to bring your own lexer.

Exactly. But note that the external lexer's only job is to handle the context-sensitive tokens. All of the normal tokens still get handled by the normal lexer.

> But this seems to be a fairly common scenario, not just for python, ruby and haskell (that I deduced have custom lexers).

I've considered building-in some kind of support for indentation in the past, but so far, there hasn't been any generic logic to share in any of the languages that we've built parsers for. Haskell and Python both *use* indentation, but they use it completely differently. And ruby has its own irregular lexing constructs, but doesn't share anything with other languages.

Maybe in the future, we'll discover more logic that can be shared. Like maybe python and coffee-script might have some common logic. Even then though, the amount of code we'd be saving is pretty small, so I tend to favor relying on the existing, more-general feature (external scanners) instead of adding a new less-general feature (built-in indentation support).

**Comment by maxnordlund** [comment]
Hm, if I'm writing a parser in JavaScript I'm pretty hesitant to start coding in C. At least for me it feels like I'm mucking around internals and not using the provided interface (grammar.js).

Maybe the best way forward would be to identify languages with indentation sensitive syntax, and sort of rank them based on usage. The latter should be fairly straight forward by using GitHub as a corpus.

I'll start by editing the OP.

**Comment by maxnordlund** [comment]
I've been thinking about this and think I know a way forward. All indention based languages need some sort of indent/dedent symbol on top of which you can build a normal grammar. So if tree-sitter has optional support for adding these then we're golden. Kinda like how the current python grammar works, the custom lexer adds indent/dedent but then it's "just" a normal grammar.

One thing though is some configuration for handling of tabs, are you allowed to mix tabs and spaces? If so, how many spaces does one tab equal? In python it's 8, but I don't believe that to be an universal truth.

Thoughts?

**Comment by kghenderson** [comment]
Hi Guys, 
This thread was helpful, and please bear with me I'm a beginner at this. I've been pulling my hair out trying to create a token for comments that matches the beginning of a line, optional whitespace, hash mark and text to the end of the line, i.e. to exclude line end comments. Am I correct in assuming that this could be a similar lexing issue or am I just missing something? (Also, yes, I too am very excited about this project)

**Comment by maxbrunsfeld** [comment]
There are now more complete docs for writing external scanners: http://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners. I don't think we're going to add built in support for the whitespace rules used by Python or similar, as they would not be reusable for more than one language, since every language works differently in this regard.

**Comment by tmccombs** [comment]
It seems to me like having a token for "increase indent" and "decrease indent" would be useful across multiple languages.

**Comment by travis-leith** [comment]
Having explicit support for indentation is also useful if you want your parser to have some sort of linting capabilities, regardless of whether your language cares much about whitespace.

**Comment by tmccombs** [comment]
As some examples of other languages besides python that uses indent/dedent for syntax (in no particular order):
- [just](https://github.com/casey/just)
- Haskell
- Yaml
- sass
- nim

**Comment by razzeee** [comment]
- Elm

**Comment by maxbrunsfeld** [comment]
Yeah, those languages use indentation differently. For example, it is defined completely differently in Haskell vs Python. That’s why it just wouldn’t work to have it built in.

**Comment by travis-leith** [comment]
@maxbrunsfeld , to put your words differently: you believe it is not possible to abstract all the different usages to a generic model. Or at least not in a simple enough way to be useful. Is that right?

**Comment by tmccombs** [comment]
As far as I understand it, the main difference is in how tabs are handled in the indentations. The  way it could work are:

1. Tabs aren't allowed (must use spaces for indentation. applies to yaml, nim, and elm. Strongly recommended style for python.
2. Tabs are required for indentation. Kind of applies to Makefiles, but the grammar doesn't actually need something special for indentation, and can just use a token for the tab character directly.
3. Tabs are equivalent to a certain number of spaces. Applies to python2
4. Tabs and spaces can't be mixed. Applies to python3 and just
5. Tabs expand to the next tabstop. afiak, only haskell does this.

I'm not sure how sass treats tabs.

I think 1 and 4 would probably be sufficient for most cases.

**Comment by maxbrunsfeld** [comment]
No, Haskell has a different notion of indent, in which there must be enough white space to exceed the column position of a certain keyword on the previous line, such as the word ‘if’, or ‘do’. Unlike Python, it has nothing to do with the previous line’s indentation.

**Comment by tmccombs** [comment]
Ok, so haskell is a special case. But there are still quite a few languages that treat indent pretty similarly.

**Comment by Lucretiel** [comment]
I'd like to throw in a note for languages that aren't *indentation* sensitive but which nonetheless are *whitespace* sensitive or otherwise not amenable to traditional context-unaware lexing. The example that comes most readily to mind is Javascript template literals and python f-strings; these aren't tokens (since they contain recursive grammars internally), but aren't really amenable to tokenization (especially whitespace-insensitive tokenization). Stuff like recursive `/* */` comments in Rust and KDL also come to mind, though (being comments) they're a bit less problematic.

**Comment by cmcl** [comment]
> I know indentation isn't parsable by GLR, or any context-_free_ grammar, as it's fundamentally context dependent even though this special case is fairly beign. But this seems to be a fairly common scenario, not just for python, ruby and haskell (that I deduced have custom lexers).

Sorry to drudge up an old issue (and be a [duty caller](https://xkcd.com/386/)) but [Michael Adams](https://michaeldadams.org/papers/layout_parsing/) has a [paper](http://dx.doi.org/10.1145/2429069.2429129) where he shows how to extend LR(k) parsing algorithms to support principled indentation-sensitive parsing which handles Haskell, Python and [Frank](https://github.com/frank-lang/frank).

Someone else mentioned this work in (an unanswered) discussion (#2861) around this time last year.
