### ISSUE TITLE
Navigating syntax trees

### ISSUE THREAD

**Issue by marijnh** [tree-sitter/tree-sitter#223]
If I understand the syntax tree data structure correctly, the following holds:

 - A node's child nodes are an unstructured sequence containing the corresponding rule's content, with nested sequences/choices/hidden rules/etc flattened into a single sequence

 - Error nodes might show up pretty much everywhere

 - Nodes have a type, but that type doesn't necessarily encode the role it has in its parent node (there might be multiple nodes of a given type in a given parent)

Given this, what's the recommended way to access a specific sub-node when you have the parent node? (Say, the consequent of a conditional, or the body of a function.)

There's an example in the Strange Loop talk that assumes the last node of a function node is its body, but I can imagine languages/grammar where that's not the case, and wouldn't it be possible for an error node to end up as last child of a function node?

**Comment by maxbrunsfeld** [comment]
> Error nodes might show up pretty much everywhere

Basically, yeah. And not just error nodes, but also comments, or any other tokens that are specified as `extras` in the grammar.

> and wouldn't it be possible for an error node to end up as last child of a function node?

That *specific* case is not possible, because errors and extras are always located as "high" (aka close to the root) in the tree as possible, given their source position. So they'll never be the first or last child of a node other than the root. They'd be positioned as a *sibling* instead.

They do make navigating the tree slightly more complex.

> There's an example in the Strange Loop talk that assumes the last node of a function node is its body, but I can imagine languages/grammar where that's not the case.

Yeah. In general, since languages have such wildly different syntax, I think the problem of generalizing source code analysis across multiple languages is inherently pretty complex, and Tree-sitter isn't trying to fully abstract that away. The trees that it provides are intentionally language-specific, embracing the terminology of each language.

So far, I've approached code analysis with Tree-sitter in two ways:

1. **Domain-specific, language-specific, ad-hoc code** - For some types of code analysis, like autocomplete, we're just going to have to write custom JavaScript code for each language. [Here's](https://github.com/atom/autocomplete-html/blob/master/lib/tree-sitter-provider.js) one simple example of HTML autocompletion in Atom. This code does have to deal with comments and errors, but this isn't too hard.

1. **Domain-specific, declarative configuration** - For syntax highlighting, each language has a configuration file in Atom that uses CSS selectors to declaratively specify which nodes should receive which colors. [Example](https://github.com/atom/language-javascript/blob/fdd1aac5533e5b1e1348f9a701472b88f8c29fbc/grammars/tree-sitter-javascript.cson#L49-L229). [Docs](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#syntax-highlighting).

    I think this declarative approach is applicable to more than just syntax highlighting. I have started work on [a more general, optimal system](https://github.com/tree-sitter/tree-sitter/pull/204) for assigning domain-specific properties to syntax nodes using CSS, and I have a prototype of a [ctags-style code navigation system](https://github.com/maxbrunsfeld/tree-tags) that uses Tree-sitter parsers in combination with [these CSS files](https://github.com/tree-sitter/tree-sitter-javascript/pull/84).

Overall, my feeling is that because of the popularity of the DOM, people are pretty good at writing scripts and stylesheets that deal with these loosely structured ordered trees. I have high hopes that the declarative approach is applicable to a good number of problems (code indexing / go-to-definition, outline view, breadcrumbs, code folding, syntax highlighting). We'll see how it goes.

**Comment by marijnh** [comment]
Interesting approach. Thanks for the response and the links!

**Comment by maxbrunsfeld** [comment]
[This PR](https://github.com/tree-sitter/tree-sitter/pull/271) adds another way of navigating syntax trees.
