### ISSUE TITLE
Error-recovery strategy

### ISSUE THREAD

**Issue by marijnh** [tree-sitter/tree-sitter#224]
The Strange Loop talk has some remarks about the error-recovery using the GLR nondeterministic parsing mechanism. This is very intriguing, and I'm curious how it works. Is there anything written up on it? Or does it come from a specific paper? (I kind of gave up on the "Error Recovery for LR Parsers" paper because of the scan quality and the fact that it didn't seem to match what you described, but let me know if I should dig deeper there.)

**Comment by maxbrunsfeld** [comment]
The basic idea is that the parser accepts any string. If the string does not match the grammar, the parser *corrects* it to match the grammar. Currently, there are two types of corrections:

1. *Skip* some number of tokens or subtrees
2. Insert one *missing* token

Obviously, for a given syntax error, there are multiple combinations of corrections that would work. The parser handles this decision similarly to how ambiguities are handled by the classic GLR algorithm: the parse stack forks into multiple branches, and tries a different possibility on each branch.

We maintain two quantities associated with each branch of the parse stack:
* `error_cost` - an integer measure of the number of subtrees skipped, the total *size* of the subtrees skipped, and the number of *missing* tokens inserted. 
* `node_count` - the number of valid syntax tree nodes that have been added, since the last error.

There is some heuristic logic for deciding when to discard branches of the parse stack based on their error cost and their node count. When the node count is small, it means that we've just recently encountered an error, so we want to allow a fairly large number of different branches to "compete", to see which one will turn out the best. When the node count is large, it means we have progressed far past the error, so we should allow very *few* different branches, in order to restore good parsing performance.

**Comment by marijnh** [comment]
Sounds nicely simple! How do you decide which branches to prune when the node count gets bigger? And to which degree do branches "prune themselves" by running into further errors? (I'd guess additional errors on an error-recovery branch usually mean it's a dead end, no?)

**Comment by maxbrunsfeld** [comment]
> How do you decide which branches to prune when the node count gets bigger?

Basically, we keep branches with a lower error cost, and discard branches with a higher error cost. And the threshold for discarding branches becomes tighter and tighter as the node count increases, so after we parse for a little while, we end up with only one branch again.

> I'd guess additional errors on an error-recovery branch usually mean it's a dead end, no?

Yeah, this ends up falling out of our strategy, because additional errors add to a branch's error cost.

**Comment by marijnh** [comment]
Clever stuff. Thanks for clarifying.

**Comment by marijnh** [comment]
(Did you invent this? I'm writing a blog post and I'm wondering who to credit for it. The error-recovery papers linked from the website don't really seem to describe this.)

**Comment by maxbrunsfeld** [comment]
I'd say that I invented the parts about using the GLR-style multi-headed parse stack to pursue different recovery strategies, and the method of discarding different stack versions based on the error cost comparison.

Some of the more fundamental concepts about error recovery (like skipping tokens, inserting tokens, and defining a cost metric) came from the linked papers. In particular, the the `forward move` section of [Error Detection and Recovery in LR Parsers](http://what-when-how.com/compiler-writing/bottom-up-parsing-compiler-writing-part-13/) presents some useful ideas:

> The correction phase attempts to find all possible repairs and returns the one which is associated with the minimum cost.

Without GLR though, the methods for finding and applying different repairs is much more complex (and worse). In earlier versions, Tree-sitter used techniques closer to what the papers described, and I found it much less effective.

**Comment by glyh** [comment]
Seems like the error-recovery strategy does not always work:
![image](https://user-images.githubusercontent.com/12870742/150931984-edacc20a-1b60-417c-a225-7fbac3f2e143.png)
Here's some lisp code, on line 15 I have some reader macros, which is valid syntax(defined by user), but not part of the language. 
I expect the false positive to be limited with in some range but clearly it's not.
