### ISSUE TITLE
Implement Clone for more public types

### ISSUE THREAD

**Issue by RubixDev** [tree-sitter/tree-sitter#2283]
I now already noticed multiple times that the `Clone` trait is not implemented for some public types like `tree_sitter::Query`, `tree_sitter::QueryPredicate`, and also `tree_sitter_highlight::HighlightConfiguration` (which depends on the other two). Is there any good reason for this? In a local copy of the repo I tried just annotating these types with `#[derive(Clone)]` and that satisfied the Rust compiler, but considering the `Clone` implementations for `Tree` and `TreeCursor` (see below) I doubt that this would suffice.

https://github.com/tree-sitter/tree-sitter/blob/be79158f7ed916190524348bebef252dcfe15d44/lib/binding_rust/lib.rs#L1329-L1333

If it really is as simple deriving `Clone` on those types though, I would be happy to create a PR for that.

**Comment by juli1** [comment]
+1 on this request. It would be really useful to have `Clone` implemented on these types.

**Comment by amaanq** [comment]
PR Welcome!

**Comment by RubixDev** [comment]
The question is whether a manual clone implementation in C for `TSQuery` is required (just like with `Tree` and `TreeCursor`) or whether it is enough to simply derive clone? I assume the former is true and I believe that would be out of my skill set.

**Comment by amaanq** [comment]
It would probably need to be a manual implementation since the underlying data is C pointers, but I would think ts_tree_cursor_copy suffices

**Comment by juli1** [comment]
We have a use-case today when we have one query that we want to execute on different trees. Each tree is built in a separate thread. So the use-case is parallel/concurrent use of query objects.

What I wanted to do is to build the query in the main thread and then, clone it for each thread. Instead, what we do today is that we are building the query in each thread, which is expensive to do.

Having `Clone` support for the query would definitely speed up the execution of our program since we are executing 70 queries on thousands of file. If we can close, we will building 70 queries object (and clone them). Without this, we are building x0,000 query objects.

**Comment by ahlinc** [comment]
@juli1 thanks for describing your situation, I think that query structures need not just do blind coping of underling structures but also consolidate all immutable parts under `Arc` wrappers. Like instead of `capture_names: Vec<String>` use `Arc<[Box<str>]>` or event more specialized structs for strings interning.

Also I think the cloning implementation have relation to #2374 and may be would be able to share some logic.

**Comment by maxbrunsfeld** [comment]
Queries should be able to be used from multiple threads. You shouldn’t need to clone them. Am I missing something?

**Comment by ahlinc** [comment]
@maxbrunsfeld Thanks for the note, exactly I forget that it has `Sync`.

@juli1 if you use Rust did you tried to use a query by a shared reference `&Query` or by wrapping it into an `Arc` like `Arc<Query>` if you need to avoid keeping references?

**Comment by ahlinc** [comment]
@juli1 The bellow snippet with a shared query instance works as expected:
```rust
use serde_json;
use std::sync::Arc;
use tree_sitter::{self, Parser, Query, QueryCursor};
use tree_sitter_json;

fn main() {
    let language = unsafe { std::mem::transmute(tree_sitter_json::language()) };
    let query = Arc::new(Query::new(language, "(string_content) @s").unwrap());
    let text = Arc::new(serde_json::json!({ "key": null }).to_string());
    let mut parser = Parser::new();
    parser.set_language(language).unwrap();
    let tree = parser.parse(text.as_bytes(), None).unwrap();
    eprintln!("{}", tree.root_node().to_sexp());

    let mut handles = Vec::new();

    for n in 1..10 {
        handles.push(std::thread::spawn({
            let tree = tree.clone();
            let text = text.clone();
            let query = query.clone();
            move || {
                let mut cursor = QueryCursor::new();
                for (m, capture_idx) in
                    cursor.captures(query.as_ref(), tree.root_node(), text.as_bytes())
                {
                    let capture = m.captures[capture_idx];
                    eprintln!("{n}: {capture:?}")
                }
            }
        }));
    }

    while let Some(handle) = handles.pop() {
        handle.join().unwrap();
    }
}
```

**Comment by maxbrunsfeld** [comment]
Great. Can we close this out?

**Comment by RubixDev** [comment]
I guess so, I actually forgot my original use cases by now, I always managed to find some other way. I guess I'm just used to most public structs in Rust crates implementing `Clone` and a few other basic traits.

And with #2374 (which I am really looking forward to) it would sort of be possible for users to "clone" a query, although not in the most optimal way.
