### ISSUE TITLE
document tags: @local.(scope|definition|reference)

### ISSUE THREAD

**Issue by avodonosov** [tree-sitter/tree-sitter#2313]
When an invalid capture name is used in queries/tags.scm, the `tree-sitter tags` command line invocation prints:
```
Invalid capture @abc. Expected one of: @definition.*, @reference.*, @doc, @name, @local.(scope|definition|reference).

```
Document the `@local.(scope|definition|reference)`

There is no mention of them in https://tree-sitter.github.io/tree-sitter/code-navigation-systems

**Comment by JenJenJay35** [comment]
Hi

**Comment by Tc69Cabusog** [comment]
Hello

**Comment by clason** [comment]
These look like `locals.scm` captures, not tags. There's some [documentation in nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#locals); maybe that can serve as a starting point.

Absolutely agreed that the standard list of captures (also for highlights since @patrickt's PR!) should be documented so downstream users do not diverge needlessly.

**Comment by ObserverOfTime** [comment]
They are documented in the [local variables](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables) section. Don't ask why they're also used in tags.
