### ISSUE TITLE
Please tag library releases

### ISSUE THREAD

**Issue by polyzen** [tree-sitter/tree-sitter#2387]
Would help downstream packagers so we don't have to pin a specific commit or source from crates.io.

Edit: In order to more easily package the CLI and lib at their own respective versions.
Edit2: Also would make it so library releases can be tracked via https://github.com/tree-sitter/tree-sitter/releases and its Atom feed.

**Comment by ahlinc** [comment]
I also thought about this, I'll try to setup a version policy between Tree-sitter components (CLI, library, crates) and separate tags.

Would it be enough for your case to have a main tag like for now that would correspond for the CLI version (because it's always released to include any changes) and an additional **library** tag like `lib: v0.21.0`?

**Comment by polyzen** [comment]
That should work. A simpler tag like `lib-v0.21.0` might be even better.

**Comment by clason** [comment]
Note that some downstream packagers don't accept tags and require a full release (since tags may be moved, as we learned a while ago ;)). I'm a bit worried about confusion if a project declares "tree-sitter@v0.21.0" as a dependency, and downstream interpret this varyingly as "CLI tag", "lib tag", or "full release"...

**Comment by ahlinc** [comment]
> (since tags may be moved, as we learned a while ago ;))

Tags wouldn't be moved anymore :smiley: There were a lot of work done to avoid disasters in the release process.

> I'm a bit worried about confusion if a project declares "tree-sitter@v0.21.0" as a dependency, and downstream interpret this varyingly as "CLI tag", "lib tag", or "full release"...

I'm open to hear about a schema of tags. Also I plan to open an issue about components version policy (how versions should grow and would be related between components and what would be guarantied for compatibility because I saw weird incompatibility issues that were reported before).

> The cleanest strategy is probably to move completely away from the current "monorepo" and have separate repos and releases (with inter-dependencies) for the different stand-alone components. But that's clearly a tall order, if even possible.

There was an another movement from different repos to the monorepo and I think it's good thing for the Tree-sitter project because this simplifies components **integrity** verification (and I hope I'll done with full automation soon). I'm against to add more burden on maintainers to verify everything cross repos. There is a lot of things in the project that require attention from experienced people who keep in mind a lot of details and there are not a lot of such people in the project.

**Comment by dundargoc** [comment]
Having different tags for different types of releases sounds like madness. I've still not understood what exactly makes the library suitable to be part of the tree-sitter repo. As I understand it is simply a binding like all the other bindings, except that it just happens to be in the main repo. Is there anything blocking us from simply extracting it into a new repo?

**Comment by amaanq** [comment]
Going forth we're going to keep the library and cli versions (and every crate/npm package for that matter) at the same version, does that help you as a packager?

**Comment by polyzen** [comment]
Cool, simplifies things a bit.

**Comment by amaanq** [comment]
Yeah the discontinuity there was a bit of a pain point all around the ecosystem, we're feeling better having the versions be upgraded together so nothing is left behind. Let me know if that's still causing problems though, but otherwise I'll close this out
