### ISSUE TITLE
difference between ts_node_edit and ts_tree_edit

### ISSUE THREAD

**Issue by clojj** [tree-sitter/tree-sitter#242]
this was also brought up in the initial question here
https://github.com/tree-sitter/tree-sitter/issues/210

what are the different usage-scenarios for ts_node_edit and ts_tree_edit ?
in tree-sitter's documentation only  ts_node_edit is mentioned

I guess my question also is: assuming  theres was only some editing inside one nodes range, what is the _minimally_ necessary edit-operation ?

```
       ts_tree_edit(tree, &edit);
       for (TSNode &node : nodes_before) {
         ts_node_edit(&node, &edit);
       }

```
This is the pattern I can see in the tests, is it supposed to be done this way ?

found here
https://github.com/tree-sitter/tree-sitter/blob/2169c45da99ac6c999c9b96ff470d0b5229e5248/test/runtime/node_test.cc#L636

**Comment by maxbrunsfeld** [comment]
Oh, I'm sorry. The docs were previously wrong. They showed the `ts_node_edit` function when they should have showed the much more important `ts_tree_edit` function. That was misleading.

I've updated the docs to show `ts_tree_edit`, and added a separate note about when to use `ts_node_edit`. TLDR - You may not need `ts_node_edit`. Atom needs it in order to handle the case where you keep a reference to a node while editing the tree.

**Comment by maxbrunsfeld** [comment]
To actually answer your questions:

> what is the minimally necessary edit-operation ?

Just call `ts_tree_edit`.

> is it supposed to be done this way ?

Yeah, you *only* need to use `ts_node_edit` if you *specifically* want to hold onto a reference to a `TSNode` instance across an edit operation.
