### ISSUE TITLE
[Question] outputting highlighted syntax

### ISSUE THREAD

**Issue by shaunlebron** [tree-sitter/tree-sitter#245]
Hi! 👋 I had trouble finding a simple example to create syntax-highlighted output (html) from some code using tree-sitter.  My motivation is to generate static html from the command line, since tree-sitter seems to work better than regex-based grammars.

I found a way to mix strings/whitespace into the s-expression format, so that each node could be directly replaced with a `<span>` tag.  Is this the best way to do it?

The gist is shown below, but the full code is here:
https://github.com/shaunlebron/highlight-tree-sitter

```
================================================================================
Code to parse (JavaScript)
================================================================================

function foo() {
  return 1;
}

================================================================================
Partial Tree
================================================================================

(program
  (function
    (identifier)
    (formal_parameters) 
    (statement_block (return_statement (number)))))

================================================================================
Full Tree (including whitespace)
================================================================================

(_root
  "\n"
  (program
    (function
      (_anon "function")
      " "
      (identifier "foo")
      (formal_parameters (_anon "(") (_anon ")"))
      " "
      (statement_block
        (_anon "{")
        "\n  "
        (return_statement (_anon "return") " " (number "1") (_anon ";"))
        "\n" 
        (_anon "}")))))

================================================================================
Output html
================================================================================

<pre><span class="_root">
<span class="program"><span class="function"><span class="_anon">function</span> <span class="identifier">foo</span><span class="formal_parameters"><span class="_anon">(</span><span class="_anon">)</span></span> <span class="statement_block"><span class="_anon">{</span>
  <span class="return_statement"><span class="_anon">return</span> <span class="number">1</span><span class="_anon">;</span></span>
<span class="_anon">}</span></span></span></span></span></pre>
```

**Comment by shaunlebron** [comment]
I got it working with Atom's scopes.  It's in the repo with examples, but gist below:

1. I first annotated nodes with the highlighting class names:

```
(_root
  "\n"
  (program.source.js
    (function
      (_anon.storage.type "function")
      " "
      (identifier.entity.name.function "foo")
      (formal_parameters
        (_anon.punctuation.definition.parameters.begin.bracket.round "(")
        (_anon.punctuation.definition.parameters.end.bracket.round ")"))
      " "
      (statement_block
        (_anon.punctuation.definition.function.body.begin.bracket.curly
          "{")
        "\n  "
        (return_statement
          (_anon.keyword.control "return")
          " "
          (number.constant.numeric "1")
          (_anon ";"))
        "\n"
        (_anon.punctuation.definition.function.body.end.bracket.curly
          "}")))))
```

2. Then I flatten all the unannotated nodes:

```
(_root
  "\n"
  (program.source.js
    (_anon.storage.type "function")
    " "
    (identifier.entity.name.function "foo")
    (_anon.punctuation.definition.parameters.begin.bracket.round "(")
    (_anon.punctuation.definition.parameters.end.bracket.round ")")
    " "
    (_anon.punctuation.definition.function.body.begin.bracket.curly "{")
    "\n  "
    (_anon.keyword.control "return")
    " "
    (number.constant.numeric "1")
    ";\n"
    (_anon.punctuation.definition.function.body.end.bracket.curly "}")))
```

3. Then i convert that tree directly to html

```
<span class="source js"><span class="storage type">function</span> <span class="entity name function">foo</span><span class="punctuation definition parameters begin bracket round">(</span><span class="punctuation definition parameters end bracket round">)</span> <span class="punctuation definition function body begin bracket curly">{</span>
  <span class="keyword control">return</span> <span class="constant numeric">1</span>;
<span class="punctuation definition function body end bracket curly">}</span></span>
```

**Comment by maxbrunsfeld** [comment]
👋 @shaunlebron sorry for not replying to this. I think I just didn't have a good answer at the time.

I've been doing some further work on syntax highlighting myself recently, and have made some improvements to the system that we originally built into Atom. A lot of it is open source, but not yet documented.

Relevant PRs:
* https://github.com/tree-sitter/tree-sitter/pull/204
* https://github.com/tree-sitter/tree-sitter/pull/283
* https://github.com/tree-sitter/tree-sitter/pull/293

In the new system I'm working on, you specify syntax highlighting using CSS files like these:
https://github.com/tree-sitter/tree-sitter-javascript/blob/master/properties/highlights.css

The `tree-sitter generate` command will pre-compile these CSS files into JSON state machines, which allow the CSS selectors to be matched in constant time while walking the tree. The JSON files look like this: https://github.com/tree-sitter/tree-sitter-python/blob/master/src/highlights.json

There's a Rust library that can read these JSON files and generate syntax highlighting, either via ANSI color codes in your terminal, or via HTML attributes/classes:
https://github.com/tree-sitter/tree-sitter/tree/master/highlight

You can run this code from the command line using the `tree-sitter highlight` command. It will try to pick the right language using information [in the parsers' package.json files](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/package.json#L27-L36).

You can configure the colors using a `~/.tree-sitter/config.json` which you can initialize with `tree-sitter init-config`.

It's all still in development and badly needs docs, but it works and is very fast, from my testing so far. I'm not sure if this is useful, but wanted to give you an update on where I'm at, since it seems like you put a fair amount of work into this.
