### ISSUE TITLE
clarify how to use dsl.d.ts

### ISSUE THREAD

**Issue by sigmaSd** [tree-sitter/tree-sitter#2505]
Following the tree sitter guide, I used `npm install --save-dev tree-sitter-cli` but the problem is the tsserver lsp don't know the types, I even created my own grammar.d.ts to fix this

But I now noticed that there is actually a dsl.d.ts, I' m adding this to grammar.js `/// <reference path="./node_modules/tree-sitter-cli/dsl.d.ts" />`

Is this how its intended to be used ?
Can we add this info to the tree siter web site in that case ?

**Comment by sigmaSd** [comment]
Just adding this triple slash reference to the grammar.js example https://tree-sitter.github.io/tree-sitter/creating-parsers#project-setup here would be enough to have a better experience for newcomers

**Comment by saud990** [comment]
> Following the tree sitter guide, I used `npm install --save-dev tree-sitter-cli` but the problem is the tsserver lsp don't know the types, I even created my own grammar.d.ts to fix this
> 
> But I now noticed that there is actually a dsl.d.ts, I' m adding this to grammar.js `/// <reference path="./node_modules/tree-sitter-cli/dsl.d.ts" />`
> 
> Is this how its intended to be used ? Can we add this info to the tree siter web site in that case ?

**Comment by mmu094** [comment]
[Skip to content](https://github.com/tree-sitter/tree-sitter/issues/2505#start-of-content)
https://github.com/tree-sitter
/
[tree-sitter](https://github.com/tree-sitter/tree-sitter)
Public
[Code](https://github.com/tree-sitter/tree-sitter)
Issues
350
Pull requests
88
[Discussions](https://github.com/tree-sitter/tree-sitter/discussions)
[Actions](https://github.com/tree-sitter/tree-sitter/actions)
[Wiki](https://github.com/tree-sitter/tree-sitter/wiki)
[Security](https://github.com/tree-sitter/tree-sitter/security)
[Insights](https://github.com/tree-sitter/tree-sitter/pulse)
[Jump to bottom](https://github.com/tree-sitter/tree-sitter/issues/2505#issue-comment-box)
clarify how to use dsl.d.ts #2505
Open
[sigmaSd](https://github.com/sigmaSd) opened this issue yesterday · 2 comments
Labels
[documentation](https://github.com/tree-sitter/tree-sitter/labels/documentation)
Comments
[sigmaSd](https://github.com/sigmaSd) commented [yesterday](https://github.com/tree-sitter/tree-sitter/issues/2505#issue-1852223490)
Following the tree sitter guide, I used npm install --save-dev tree-sitter-cli but the problem is the tsserver lsp don't know the types, I even created my own grammar.d.ts to fix this

But I now noticed that there is actually a dsl.d.ts, I' m adding this to grammar.js /// <reference path="./node_modules/tree-sitter-cli/dsl.d.ts" />

Is this how its intended to be used ?
Can we add this info to the tree siter web site in that case ?

[sigmaSd](https://github.com/sigmaSd) commented [yesterday](https://github.com/tree-sitter/tree-sitter/issues/2505#issuecomment-1679710996)
Just adding this triple slash reference to the grammar.js example https://tree-sitter.github.io/tree-sitter/creating-parsers#project-setup here would be enough to have a better experience for newcomers

@ahlinc ahlinc added the documentation label yesterday
ahlinc commented yesterday • 
Generation of the dsl.d.ts was added in PR #2438: #2438 (comment)
An example of its correct use: https://github.com/tree-sitter/tree-sitter/pull/2438/files#diff-b9b8dbe553f759cd13cf0ad6e141990d1d9b86f71e54cb8e27da1aa100335619R1-R2

@tree-sitter tree-sitter deleted a comment from saud990 3 hours ago


Leave a comment
Remember, contributions to this repository should follow its contributing guidelines.
Assignees
No one assigned
Labels
documentation
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

2 participants
@[ahlinc](https://github.com/ahlinc)
@sigmaSd
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
clarify how to use dsl.d.ts · Issue #2505 · https://github.com/tree-sitter/tree-sitter
continuous.contriburion

**Comment by mmu094** [comment]
@mmu094worldspatch12
@mmu094

**Comment by sigmaSd** [comment]
Also the doc should mention `npm install --save-dev @types/node` so newcomers have the complete working out of the box experience

**Comment by sigmaSd** [comment]
For people who later reads this, this is whats recommended to add `/// <reference types="tree-sitter-cli/dsl" />` (until https://github.com/tree-sitter/tree-sitter/pull/2438 lands which will have a default grammar.js template with correct typing)
