### ISSUE TITLE
Add `ts_parser_parse_interruptible` C API call

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#2541]
# Motivation

Currently Tree-sitter is able to interrupt its parsing process in several ways:
* By a cancellation flag.
* By a timeout.

But there may be other cases:
* Someone wants to interrupt early on a first error: #2289 
* Interrupt due to a decoding error in an input text _(that's a one of reasons for `TSParserInput` struct mentioned bellow)_.

All of such cases make sense but adding new and new API calls increases Tree-sitter's API surface and adds additional logic that triggers every time on an interruption requirement check point _(for now every 100 parser steps)_.

The `ts_parser_parse_interruptible` C API call would receive an additional callback parameter that would check any interruption condition implemented on _a caller side_.

If to add the `ts_parser_parse_interruptible` C API call it would be possible:
* To interrupt parsing on any condition that would be managed on the caller side.
* To deprecate the next C API calls because all of their functionality would be implementable externally in a check callback:
  * `ts_parser_cancellation_flag`
  * `ts_parser_set_cancellation_flag`
  * `ts_parser_timeout_micros`
  * `ts_parser_set_timeout_micros`
* To minimize a condition check logic inside of Tree-sitter's C core.
* To make Tree-sitter core [_optionally_ dependable](https://github.com/tree-sitter/tree-sitter/pull/2540#issue-1858123862) from:
  * The time `<time.h>` header.
  * The `clock_gettime` libc call [on Linux](https://github.com/tree-sitter/tree-sitter/pull/2515#issue-1854946650) and similar on other platforms.

To cover the #2289 case Tree-sitter would start to manage a struct `TSParserState` with some flags and pass it as a parameter to the callback received by the `ts_parser_parse_interruptible` API call. Such struct would be easily extendable in the future by adding more flags if it would be needed. Currently there would be a one field called an `error_count`.

```c
struct TSParserState {
  uint32_t error_count,
}
```
---
## Alternative

I'd even suggest to go further and implement a one universal `ts_parser_parse_ex` API call that would look like:
```c
TSTree *ts_parser_parse_ex(
  TSParser *self,
  const TSTree *old_tree,
  TSParserInput *input,
  TSParserConfig *config
);
```
The `config` parameter may be `NULL` what would lead to a default parser behavior.

The `TSParserInput` would be a new struct that supersedes `TSInput` struct but would improve a design of how input decoding works. _(Will be described separately)._

The `TSParserConfig` struct would look like:
```c
struct TSParserConfig {
  bool (*interrupt_check)(TSParserState *parser_state);
}
```

This would allow to have a one universal parsing call with an access to the parsing logic and all other simpler calls like `ts_parser_parse`, `ts_parser_parse_string` and `ts_parser_parse_string_encoding` would be just thin wrappers on top of it.

_If to go in this way then adding the  `ts_parser_parse_interruptible` API call wouldn't be needed because its functionality would be a part of `TSParserConfig` struct._

**Comment by maxbrunsfeld** [comment]
I like the idea of unifying the interruption capabilities. I also think it's reasonable to have an options struct, in case we want to add other optional parameters. Some  minor naming suggestions:

* Instead of `ts_parser_parse_ex`, I'd rather call it `ts_parser_parse_with_options`, just to favor whole words over abbreviations
* Instead of `TSParserConfig`, I'd call it `TSParseOptions`, since they apply only to one single parse invocation.

**Comment by Plentywolf** [comment]
Done really well

**Comment by criminosis** [comment]
Hi @amaanq ! I noticed this issue was closed following this [PR](https://github.com/tree-sitter/tree-sitter/pull/3843. This issue was considered superseding a PR I put up in https://github.com/tree-sitter/tree-sitter/pull/2289. 

I'll confess my C isn't the greatest, so please let me know if I missed it, but it didn't seem like there was a way to get indication if the parser had encountered a syntax error given its configured grammar.

It seemed like the state that gets passed back to the caller via `&self->parse_state` is only accommodating timeouts and decoder errors, at least based on the tests that seemed to accompany the change.

Is there any appetite for exposing additional parser state like [stack state](https://github.com/tree-sitter/tree-sitter/blob/473f0a1a4dfe26c22d8089b6e756de274210e189/lib/src/parser.c#L1522) which was the [basis of the early out PR](https://github.com/criminosis/tree-sitter/blob/0600ca19cda3e56ff924e8c36699a6d73315f832/lib/src/parser.c#L1466) I did?

**Comment by amaanq** [comment]
I'm not too sure on what a good API for that would look like, because currently, you *could* have a parser be in an error state, and then it recovers in a successful manner and produces a valid parse tree. I don't think you'd want to "early bail" on an error in this case, hence why I hadn't added that information to the PR

**Comment by criminosis** [comment]
What about a count of tree nodes in error (so far) that gets exposed to the callback?

Assuming that a node represents a completed attempt of parsing a segment of code that seems like it could be a more stable signal than exposing that the parser is in the midst of an instantaneous, possibly recoverable, error mid-node at an arbitrary moment when the operation countdown just happened to hit 0.

Since the completed tree can have nodes in error is there some point when the parser can definitively say its encountered a sub node in error before processing the rest of the tree? Or does that require viewing the entire tree and then marks nodes in error?

**Comment by criminosis** [comment]
@amaanq would that be viable? I can take a crack at the PR if that sounds palatable. Maybe even just reduce it to a boolean flag of a node marked as being in error somewhere since the last callback since the number of nodes isn't really important (at least for what I have in mind).

> you could have a parser be in an error state, and then it recovers in a successful manner and produces a valid parse tree.

Just to make sure I understand, is that describing an outcome of a parent node that parsed successfully but child / children nodes below it are flagged as being in error? So while the root to parent may have succeeded it encapsulates an erroneous region as being malformed and flags the node as in error, but still returns a valid tree to the caller.

At least in my use case if any node fails to parse I'm no longer interested in the tree at all. So if the callback could convey "since the last time the callback executed a node has been marked as being in error" then that'd be helpful to terminate processing and not waste any further compute time in a tree I don't want anymore.
