### ISSUE TITLE
The tree-sitter binary for linux x64 source hash is different from 0.20.8 tag

### ISSUE THREAD

**Issue by alaviss** [tree-sitter/tree-sitter#2618]
Right now https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter-linux-x64.gz (sha256: `90734a35cebd1aa4c0a5f7cbe81063724576f489951e5b55f88dcf073057d100`) reports:

```
$ ./tree-sitter-linux-x64 -V
tree-sitter 0.20.8 (d4c1bf7ce78051b7f4a381d1508d68928512ed5f)
```

But v0.20.8 is tagged on 0c49d6745b3fc4822ab02e0018770cd6383a779c

**Comment by ahlinc** [comment]
Thanks for the report, there was a mess up with a last release process due to totally broken CI, the CI was overhaul and rewritten from scratch. But there was an issue with libc version that affected a lot of people, it was fixed in #2272 and a one artifact was re-uploaded separately. Unfortunately it's not possible to move the tag without triggering a lot of other problems, so it was best workaround solution for now because CI doesn't ready yet for quick bugfix  releases without making mistakes. For the next release CI will be fully improved.
