### ISSUE TITLE
Makefile does not install `parser.h` but `npm install` and `cargo install` do

### ISSUE THREAD

**Issue by ProfDoof** [tree-sitter/tree-sitter#2677]
I was digging through the various install methods and the `Makefile` was recently changed so that it did not install `parser.h` but all the other install methods still include them in their various installs. So, for consistency those should probably be made to do the same.

**Comment by Codeup357** [comment]
`<ctrl+e>`

**Comment by ProfDoof** [comment]
Ok, so, I have no idea what's going on here with any of this. @afxo271, if you would, please stop commenting meaningless things on this issue as I am trying to raise what I view as a legitimate issue and I doubt spam is helping the case. 

And @Codeup357, what is that supposed to mean? Because I'll admit some confusion. 😂

**Comment by amaanq** [comment]
Those are spam bots, tree-sitter has been plagued with them, really wish GH did something about it but this seems to be one of the few repos affected by it

To answer your question, the Makefile does not install parser.h because each parser repo should use the generated parser included locally when the CLI command "tree-sitter generate" is invoked (hence why those include parser.h, to stick em in the repo)

This way, the generated parser.c will in fact work with the generated parser.h, to avoid ABI/version mismatches that can cause issues

**Comment by ProfDoof** [comment]
@amaanq I know that is the expected behavior. However, I was saying that the `npm install` and `cargo install` do still include the `parser.h` and that if the goal is to remain consistent, both of those implementations of the installation process should be updated to respect that.

**Comment by amaanq** [comment]
This has fixed now for a few days, sorry about the delay
