### ISSUE TITLE
Overflow uint32_t when parsing a large source file that exceeds a length of 4GB

### ISSUE THREAD

**Issue by ybbh** [tree-sitter/tree-sitter#2728]
# Description

The tree-sitter code uses uint32_t to store lengths.

Ex: [TSInput::read, api.h](https://github.com/tree-sitter/tree-sitter/blob/master/lib/include/tree_sitter/api.h#L74)

This implementation may result in an overflow bug when parsing large files, leading to parsing failures. While this is typically not an issue for most source code files, as they generally do not exceed 4GB in size.It can be problematic for formatted text files used for application input/output, such as JSON, XML, and DOT files. These files can sometimes be very large in size, which can lead to unexpected errors.

# How to reproduce

1. Use a parser

    ```
    git clone https://github.com/rydesun/tree-sitter-dot.git
    cd tree-sitter-dot
    cargo build
    ```

2. Utilize tree-sitter to parse a large .dot file(> 4GB)
      ```
      tree-sitter parse  [LARGE_DOT_FILE] -d
      ```
We hope to parse it without any issues for the .dot file is OK, but unfortunately, it is giving an error.

# How to fix it

A simple and quick fix could be achieved by [changing all length-related variables to uint64_t type](https://github.com/tree-sitter/tree-sitter/compare/master...scuptio:tree-sitter:master)(I haven't thoroughly tested all functionalities and verified whether they work correctly, but it does resolve the overflow issue).

**Comment by ahlinc** [comment]
We'll consider to add this as an optional feature controlled by a compile time flag. I'm not sure that we should to increase this by default, because of increased structures size and a lot of dependant binding libraries.
May be it makes sense to stop parsing at all with returning an error when such value overflowing happens.

**Comment by ObserverOfTime** [comment]
>  May be it makes sense to stop parsing at all with returning an error when such value overflowing happens.

This would definitely be easier than (conditionally) changing the size both in core and in all bindings.

**Comment by amaanq** [comment]
I don't think we want to support this, because the additional memory usage would be significant. Based on [this comment](https://github.com/tree-sitter/tree-sitter/issues/1609#issuecomment-1018816680) from Max, I don't think we're going to support parsing files larger than 4GB in size, sorry. You'd already be hitting *very* high memory usage with that large of a file anyways, so it's really not worth supporting.
