### ISSUE TITLE
Query does not capture nodes

### ISSUE THREAD

**Issue by juli1** [tree-sitter/tree-sitter#2732]
There is a case when we do not correctly catch all nodes in a query.

Take the following Java code in the playground

```java
class NotCompliant {
    public void myMethod() {
        Email email = new SimpleEmail();
        email.setHostName("smtp.servermail.com");
        email.setSmtpPort(465);
        email.setAuthenticator(new DefaultAuthenticator(username, password));
        email.setSSLOnConnect(true);
        email.setFrom("user@gmail.com");
        email.setSubject("TestMail");
        email.setMsg("This is a test mail ... :-)");
        email.addTo("foo@bar.com");
        email.send();
    }
}
```

and take the following query

```
(block
    (local_variable_declaration
        type: (type_identifier) @type
        declarator: (variable_declarator
            name: (identifier) @varname
            value: (object_creation_expression
                type: (type_identifier) @objecttype
            )
        )
        (#match? @type "^Email$|^SimpleEmail$")
        (#eq? @objecttype "SimpleEmail")
    ) @decl

    (expression_statement
        (method_invocation
            object: (identifier) @obj
            name: (identifier) @name
            arguments: (argument_list
                .
                (true)
                .
            )
            (#eq? @obj @varname)
            (#eq? @name "setSSLCheckServerIdentity")
        )
    )? @sslcheck
)
```

Nothing is captured and nothing matches.. If you remove or comment `email.setSSLOnConnect(true);`, the query matches.

The query should matches regardless of this statement being included.

![Screenshot 2023-10-30 at 3 19 09 PM](https://github.com/tree-sitter/tree-sitter/assets/993972/2bc22734-3ed0-4d5c-8a12-3905ab4f227a)
![Screenshot 2023-10-30 at 3 19 14 PM](https://github.com/tree-sitter/tree-sitter/assets/993972/cf65497a-528b-467a-a3d6-13dd80bd1932)

**Comment by ahlinc** [comment]
_Testing queries is a playground isn't informative in all cases. Maybe I'll consider to add an additional mode to the playground like CLI's behavior but for usual queries debugging for now I'd suggest to use Tree-sitter's CLI._

In the current Tree-sitter queries implementation predicates implemented as post query filtration step, so it doesn't matter where predicates defined they applied to the whole pattern, so the whole pattern with defined predicates would be matched or not. It may be to think about predicates behavior like the bubble up from their definition places to a top level of the whole pattern like the `var` variables in JS functions.

So your query is equivalent of this:
```lisp
(block
    (local_variable_declaration
        type: (type_identifier) @type
        declarator: (variable_declarator
            name: (identifier) @varname
            value: (object_creation_expression
                type: (type_identifier) @objecttype
            )
        )
    ) @decl

    (expression_statement
        (method_invocation
            object: (identifier) @obj
            name: (identifier) @name
            arguments: (argument_list
                .
                (true)
                .
            )
        )
    )? @sslcheck

    (#match? @type "^Email$|^SimpleEmail$")
    (#eq? @objecttype "SimpleEmail")
    (#eq? @obj @varname)
    (#eq? @name "setSSLCheckServerIdentity")
)
```
And it doesn't match because not all predicates match and the whole pattern match output is filtered out due to non matching of the last predicate.

If to comment the last predicate the output exists:


![Screenshot from 2023-11-03 04-51-56](https://github.com/tree-sitter/tree-sitter/assets/14666676/158437e1-4a7d-4f9e-b17e-bd6115aadd02)


With the current queries implementation it isn't possible to use predicates to control parts of a pattern only the whole pattern itself.
