### ISSUE TITLE
Donating Funds to Tree-Sitter

### ISSUE THREAD

**Issue by Lfada** [tree-sitter/tree-sitter#2743]
Hi Tree-Sitter maintainers, I'm Lucas, a core contributor to the Radworks project. https://radworks.org/

[[Radicle](http://www.radicle.xyz/)] has been using https://github.com/tree-sitter/tree-sitter. It's in fact one of our most critical dependencies!

All Radicle’s core-contributors really appreciate the work you all do and we want to ensure that you are all well-funded to keep doing it. For that reason, we have decided to donate some funds to your project through [[Drips](https://www.drips.network/)](an initiative that is coming out of our organization for funding FOSS).

Who can I talk to about it?

cc: @maxbrunsfeld @ahlinc @amaanq @patrickt

**Comment by maxbrunsfeld** [comment]
Hi, thanks for reaching out, @Lfada.

My funding situation is that I'm working on a startup, [Zed](https://zed.dev), that uses Tree-sitter. I do still work on Tree-sitter, and its languages, though my time is split with many other concerns. So I'm not really in a position to accept any donations for work on Tree-sitter itself.

@ahlinc and @amaanq have been doing a lot of other important work on Tree-sitter, and I'm not sure what their employment and financial situation is. I'll let the two of them chime in about whether they are in a position to accept donations to support work on Tree-sitter.

**Comment by amaanq** [comment]
I'm currently in school wrapping up my undergrad and am okay financially but of course would appreciate any donations -it would definitely make me prioritize adding any languages/features or fixing stuff in any of the repos that would be beneficial towards Radworks.

That being said, I would rather defer any funds I might receive to @ahlinc, he's been with tree-sitter longer and is (imo) more deserving and potentially in need of it, however he'd like to split it up between himself and me would be okay with me

On that note a tree-sitter related chat where we could talk about stuff like this would be nice, especially regarding bug fixes, feature updates, and releases - @maxbrunsfeld would it be possible to get on a platform like Matrix and have a group chat between us 3 maintainers to better coordinate development of tree-sitter? e.g. it'd be nice to have a new release since downstream is way behind, the npm library users and consumers are hurting from that

**Comment by Lfada** [comment]
I really like the camaraderie going on here. 

The way Drips works, is that you can split to "dependencies". This means that you all can decide where the incoming funds are going. Parts of it could go to @amaanq @ahlinc or anyone else (that's your decision) and also parts of it could go to other  FOSS dependencies. 

My suggestion is that you work together to decide how you want to use these funds. The total amounts streamed over the period of a year [will be around $22k](https://www.drips.network/app/projects/github/tree-sitter/tree-sitter), which is sizeable in my opinion. 

Before or after you have this conversation, I would encourage some or all of you to jump on a call with us. First, to ask any questions you have, and second to share feedback or ideas. We are in learn mode, and want to create the best experience for FOSS maintaners and projects to receive recurring donations.

**Comment by jdorfman** [comment]
@maxbrunsfeld you have a balance growing on `thanks.dev` from Sourcegraph and I'm sure others...=)
