### ISSUE TITLE
Is there a way to distinguish between EOF and the \0 character in external scanners?

### ISSUE THREAD

**Issue by Kerl13** [tree-sitter/tree-sitter#280]
I am trying to parse strings potentially containing the null character `\0` in an external scanner.
But as far as I understand, the standard way to detect the end of the file is to test if `lexer->lookahead` is `\0`.

Am I missing something? Is there a way to decide whether `\0` stands for EOF or just a null character in the source file while scanning?

---

#### Minimum example
So far the best I could find to match anything until the end of the file is the following

```C
bool scan(TSLexer *lexer) {
  while (lexer->lookahead != 0) {
    lexer->advance(lexer, false);
  }
  return true;
```

which stops too early on [test.txt](https://github.com/tree-sitter/tree-sitter/files/2872323/test.txt)

**Comment by maxbrunsfeld** [comment]
Your language can contain the null character in the source code? Unfortunately, there is currently no way to distinguish this from EOF. I'm open to suggestions on this. The main challenge is that changing the ABI that Tree-sitter expects from compiled parsers can be disruptive, so I try to make changes additive when possible.

**Comment by Kerl13** [comment]
Yes [menhir](https://github.com/Kerl13/tree-sitter-menhir) code can contain the null character, certainly because OCaml code can too. But actually, since the null character can occur in a file without having a special meaning a priori, I think it should not be treated differently from any other character.

Sure, I understand that you don't wan't to break the API. I would suggest:

- for know, adding a method `lexer->is_at_eof()` 

- and a more cosmetic change: you could define a constant `eof` (or `tree_sitter_eof`). This would make current code clearer, for instance: 
  ```C
  while (lexer->lookahead != eof) { ... }
  ```
  And this would also allow you to change the value of that constant to something like `-1` in the future if you decide to make a non-backward compatible release.

What do you think?

**Comment by 314eter** [comment]
In theory, OCaml strings can contain null characters, but I don't think anyone actually does this. Do you have an example?

You can parse null characters in external scanners by checking if `lexer->get_column(lexer)` increases. At EOF, it stays 0. This works for multiple consecutive null characters too.

In [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml), null characters are not supported in strings because the content of strings is not parsed by an external scanner, and tree-sitter treats null as eof. Maybe that can be fixed with an external scanner, but I don't think it's worth the effort as long as there are no real world examples.

**Comment by Kerl13** [comment]
I encountered null characters in menhir's [test suite](https://gitlab.inria.fr/fpottier/menhir/tree/master/test/good) while testing my parser. The relevant files are:

```
good/boomerang.1.1.0-bparser.mly
good/ldap.2.4.0-ldap_filterparser.mly
good/dns.1.0.1-zone_parser.mly
```
And they seem to be real life parsers.

Oh thanks for the trick, I didn't think of that!
I should follow tree-sitter-ocaml more closely. Your rule for strings is much cleaner than my external scanner.

I agree that in most cases, like in OCaml source code, it's fine if null characters are not supported. But since tree-sitter is a generic parser generator and `\0` is a regular ASCII character, I still think it would be better not to treat it as eof.

**Comment by 314eter** [comment]
In that case I think the real issue is not that null and eof can't be distinguished in external parsers (because they can be with a hack), but that tree-sitter does not support null characters in normal rules. The consequence is that in Atom the syntax highlighting stops on the first null character.

**Comment by Kerl13** [comment]
Agreed, maybe I should open a new issue/rename this issue to clarify this?

**Comment by 314eter** [comment]
It is possible to parse null characters in normal rules by explicitly allowing them (see tree-sitter/tree-sitter-ocaml#24).

The null characters that you found in the Menhir test suite were [incorrectly imported](https://gitlab.inria.fr/fpottier/menhir/issues/18).

**Comment by maxbrunsfeld** [comment]
Indicating EOF by setting `lexer->lookahead` to zero was a mistake; I should have either had `advance` return a boolean or added a separate `is_eof` function. It'd be easy to change, but updating all of the existing external scanners would be time consuming and cause disruption for other people.

I'll keep this change in mind as something to include alongside any other breaking change that I need to make.

**Comment by maxbrunsfeld** [comment]
Ok, in the next release of the CLI, v0.15.13, you'll have the option of generating parsers that use a new API which indicates EOF without relying on setting `lookahead` to `'\0'`. It's going to be behind a flag for the time being, so that by default, the generated parsers will be compatible with old versions of the library.

**Comment by Kerl13** [comment]
Great news! Thanks for the update :slightly_smiling_face:
