### ISSUE TITLE
Prebuilt linux binary doesn't work on CentOS/RHEL/Oracle Linux 7

### ISSUE THREAD

**Issue by fcurts** [tree-sitter/tree-sitter#282]
Running tree-sitter on Oracle Linux 7 gives:

```
/code/node_modules/tree-sitter-cli/tree-sitter: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /code/node_modules/tree-sitter-cli/tree-sitter)
```

CentOS 7, RHEL 7, and Oracle Linux 7 are all based on glibc 2.17 instead of 2.18.

CentOS/RHEL 8 will arrive in summer at the earliest. Can tree-sitter be made to work with glibc 2.17?

**Comment by maxbrunsfeld** [comment]
Ah, that makes sense. I publish the pre-built binaries from Travis CI. I’m not sure if there’s a way to avoid the glibc 2.18 dependency using Travis. Do you know? I’d be glad to accept a PR that reconfigures the CI build somehow.

In the meantime, tree-sitter is also pretty straightforward to build from source. You just need compiler toolchains for Rust and C.

**Comment by fcurts** [comment]
I think it's a matter of choosing a Linux image that's based on glibc 2.17. In any case, I managed to solve my immediate problem by switching to a Fedora 27 based Docker image, which is based on glibc 2.18.

**Comment by maxbrunsfeld** [comment]
It looks like for the moment, Travis still allows you to opt into using Ubuntu Precise. I might try that.

**Comment by maxbrunsfeld** [comment]
I'm going to close this one out, because I don't think I plan to maintain pre-built binaries for other versions of linux that aren't compatible with the glibc version found on Trusty. If anyone else wants to maintain them, the instructions for building from source are documented: http://tree-sitter.github.io/tree-sitter/contributing#building.

**Comment by abhijeetbodas2001** [comment]
Hello @maxbrunsfeld, since this thread is a few years old, I wanted to ask if the lastest source code for tree-sitter can be built on RHEL 7 (glibc v2.18)? If so, could you give an idea about the effort involved in maintaining such a pre-built binary?

**Comment by ahlinc** [comment]
> goal is to definitely get rid of any libc dependencies

This is unrelated for the Tree-sitter's CLI, it will be an option for Tree-sitter core.

---

Linux distros and related docker images with the such ancient glibc version aren't work out of the box anymore. A one easiest option that I see is to build the needed glibc version [from source](https://stackoverflow.com/a/52454681) and use `cargo build --release` with tuned env variables to properly link against custom glibc. _But compile without an `rpath` linking so that the compiled binary can run in the target environment._

Or try to install the rust toolchain with `rustup` on an existing RHEL7 machine and use there the `cargo build --release` to build Tree-sitter's CLI from source.
