### ISSUE TITLE
No error recovery?

### ISSUE THREAD

**Issue by fcurts** [tree-sitter/tree-sitter#285]
We recently switched the Atom package for an in-house language from a TextMate grammar to a tree-sitter grammar. Everything works fine except that there doesn't seem to be any error recovery - the moment a file contains a single syntax error, the remainder of the file is not highlighted anymore.

Is this is a known (and temporary) limitation of tree-sitter, or does this indicate a problem with our grammar? Highlighting correct code seems to work just fine. We didn't have this problem with the TextMate grammar.

**Comment by Aerijo** [comment]
One of Tree-sitter’s selling points is great error recovery, so I'd guess an issue with your grammar. Is it available for others to see?

**Comment by fcurts** [comment]
No it's proprietary software.

**Comment by maxbrunsfeld** [comment]
It sounds like a problem with your grammar. Atom uses tree-sitter by default for several languages. You can test out those to get an idea of how error recovery should work.

Do you have an external scanner? There is a rough edge of the external scanner API regarding error recovery: immediately after an error, your scanner will get called, and all of the elements of the ‘valid_symbols’ array will be set to true, because the parser is looking for any token it can find, in order to begin recovery.

If your external scanner is used to match tokens that are pretty nondestinct (i.e. pretty permissive about what characters they match) you may need to add a conditional to detect that error recovery is taking place and avoid matching those tokens.

I wish I had added an explicit parameter to indicate this, but I’ve been reluctant to make a breaking ABI change just for this, so right now you just have to detect that the valid tokens are all set to true.

This may not have to do with your problem, it’s just my first guess. I would investigate by running ‘tree-sitter parse’ in your file with an error. You can use the ‘-d’ flag to dump info about what tokens are being matched, and the ‘-D’ flag to render a visual graph of the parsing process, including error recovery. You need graphviz for that.

**Comment by fcurts** [comment]
> Do you have an external scanner? There is a rough edge of the external scanner API regarding error recovery

That was it! The first token our external scanner tries to recognize is "multiline string content". After disabling this and similar tokens in error recovery mode, error recovery now works fine.

**Comment by maxbrunsfeld** [comment]
Great! Happy to hear it was solved.
