### ISSUE TITLE
Officially support `@injection.shebang`

### ISSUE THREAD

**Issue by tgross35** [tree-sitter/tree-sitter#2851]
Helix provides an `@injection.shebang` that allows the editor to handle shebang parsing to determine the language. This is a useful fallback in cases where a specified injection is not available, and correctly extracting shebangs within the parser can be quite difficult.

At its most basic, this could be the regex `#!\S*bin\S*[/ ](?P<lang>[^-'"]\S*)` to extract the last argument of a `/a/b/c` path, or the first non-command argument after it. More involved would be making use of the `first-line-regex` specified in `package.json`.

I opened an issue for NeoVim to support this as well: https://github.com/neovim/neovim/issues/26939

Docs for Helix's implementation: https://docs.helix-editor.com/guides/injection.html#capture-types

**Comment by amaanq** [comment]
I'm not convinced this makes sense to have upstream, mainly because of inconsistencies between compiler/interpreter executable names from the language itself (python3, py3, or py for python, node, deno, or bun for javascript, etc), formats used (e.g. using /usr/bin/env instead of the bin name itself), and other problems. It would only benefit a select few cases for a select few languages, which is just not worth it I think.

**Comment by tgross35** [comment]
Yeah, it is indeed a pretty niche use case. I suppose it would be better to have a regex replacement option, like nvim’s gsub.
