### ISSUE TITLE
`prec()` doesn't work

### ISSUE THREAD

**Issue by RedCMD** [tree-sitter/tree-sitter#2866]
When trying to match against the text `(*CALLOUTS)`
the following grammar will parse it as a `capture_group` rather than `callout`
I've tried to use `prec()` everywhere to tell treesitter to prioritize `callout` over `capture_group`, but it seems to be bugged

the only thing that has worked is changing `'*'` to `/\*/` at the bottom (the comment)
which doesn't make any sense as https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-3-creating-parsers.md#conflicting-tokens clearly states that if rule 4 fails, it will fall back to rule 5. which in my case `callout` has priority over `capture_group`
so rule 5 also seems to be broken aswell

```js
module.exports = grammar({
	name: "regex",
	conflicts: $ => [
		[$.callout, $.capture_group]
	],
	precedences: $ => [
		[$.callout, $.capture_group]
	],
	rules: {
		regex: $ => repeat($._expression),
		_expression: $ => choice(
			prec(5, $.callout),
			prec(-5, $.capture_group),
			$.literal,
		),
		literal: $ => prec(-9,
			repeat1(/[^?+*]/),
		),
		callout: $ => prec(5,
			seq(
				'(',
				prec(5, '*'),
				/[A-Za-z_]/,
				repeat(/\w/),
				')',
			),
		),
		capture_group: $ => prec(-5,
			seq(
				'(',
				prec(-5,
					optional(
						field(
							'ERROR',
							$.quantifier,
						),
					),
				),
				repeat($._expression),
				')',
			),
		),
		quantifier: $ => prec(-5,
			repeat1(
				choice(
					'?',
					'+',
					prec(-5, '*'),
					// /\*/,
				),
			),
		),
	}
});
```

**Comment by tgross35** [comment]
I have something like this too, in trying to prefer a more complex rule over a simple rule.

```js
    shebang: ($) => seq("#!", choice($._shebang_with_lang, $._blank_shebang)),

    _shebang_with_lang: ($) =>
      seq(
        /.*\//,
        optional(seq("env ", repeat(SHEBANG_ENV_FLAG))),
        alias($.identifier, $.language),
        /.*/,
      ),

    _blank_shebang: ($) => /.+/,
```

I expect it to match `_shebang_with_lang` wherever possible. But even when giving `_shebang_with_lang` a positive precedence and `_blank_shebang` a negative precedence, it always matches the simpler `_blank_shebang`. There is no issue with `_shebang_with_lang`, since removing `$._blank_shebang` from the `choice` parses it correctly.

I have tried setting `prec` on its own and with `left` and `right`, as well as `prec.dynamic` with the `conflicts` list set. I would have expected the dynamic rule to work since this is technically a conflict, but unfortunately there is no difference.

**Comment by tgross35** [comment]
This does seem like a case for `prec.dynamic` (based on the excellent explanation at https://github.com/tree-sitter/tree-sitter/issues/678#issuecomment-656243453), but that doesn't seem to change my case at all.

**Comment by tgross35** [comment]
Nor does setting `precedences` work here, `precedences: ($) => [[$.shebang_with_lang, $.blank_shebang,]]` makes no difference

**Comment by mingodad** [comment]
For comparison using a `LARL(1)` parser here https://mingodad.github.io/parsertl-playground/playground/ an `Yacc/Lex` compatible online editor/tester (copy and paste the grammar shown bellow on the `Grammar` editor and the input shown bellow in the `Input source` editor then click `Parse` to see the parse tree).

**Notice that the `literal` token needed to be extended.**

It doesn't require any precedence and `tree-sitter` shouldn't need then too.
```
%token literal callout

%%

regex :
	expression*
	;
	
expression :
	callout
	| capture_group
	| literal
	;
	
capture_group :
	'(' quantifier? expression* ')'
	;
	
quantifier :
	'?'
	| '+'
	| '*'
	;
	
%%

%%

[ \t\n\r]+	skip()

"?"	'?'
"+"	'+'
"*"	'*'
"(" '('
")" ')'
"(*"[A-Za-z_]\w+")" 	callout
[^?+*() \t\n\r]+	literal

%%
```
With this input:
```
(*CALLOUTS)
(*one two)
```
Produces this parse tree:
```
regex
 |regex_1
 | |expression
 | | |callout -> (*CALLOUTS)
 | |expression
 | | |capture_group
 | | | |'(' -> (
 | | | |capture_group_1
 | | | | |'*' -> *
 | | | |capture_group_2
 | | | | |expression
 | | | | | |literal -> one
 | | | | |expression
 | | | | | |literal -> two
 | | | |')' -> )
```

**Comment by rabbiveesh** [comment]
@RedCMD the issue with your grammar is that after TS lexes the `*`, it then looks ahead to the NEXT token, which, by rule 5 will match `literal` rather than the callout's ID_First, b/c the two patterns match the same length, and `literal` is defined earlier.

Nothing that you're trying is working b/c you aren't using precedence correctly. If you want to force the `*` to be the callout token, then you'd want to do any of the following:
1. change the first token of callout from `(` to `(*` so it matches by longest wins
2. define callout's `*` as `token(prec(2, '*'))` in order to do what you want to do
3. move the definition of `literal` lower down in the grammar

Nothing is working other than expected.
I would recommend taking a look at the debug output instead of bashing your head against your grammar and peppering it with random garbage. You can get a nice graphical output with `tree-sitter parse YOUR-FILE -D --open-log` (at least with the ts 0.21 and on, otherwise you needa open the output `log.html` by yourself)

**Comment by tgross35** [comment]
For what it's worth, here is the graph output of my example. It doesn't seem to even try `_shebang_with_lang`.

<img width="754" alt="image" src="https://github.com/tree-sitter/tree-sitter/assets/13724985/6900ced1-6577-4b3f-ac0b-516736206276">

**Comment by RedCMD** [comment]
Thank you @rabbiveesh for the great insights
all 3 of those options worked
I guess I need to look at the order a lot closer
I didn't realise there was a debug output. 

and I guess as soon as TS finds a difference in 2 identical paths, it ends up sticking with the chosen path. even when errors arise

**Comment by rabbiveesh** [comment]
Yes, that's part of the fact there's a separate Lexington and parsing phase. 
In order to backtrack on errors, you need to make sure all tokens are the same, and then you can go GLR by adding a conflict
