### ISSUE TITLE
0-indexed line numbers in CLI output

### ISSUE THREAD

**Issue by jmitchell** [tree-sitter/tree-sitter#287]
Parser output and error messages refer to rows in the input using 0-indexed values, but editors and many other tools conventionally using 1-indexing for row numbers.

Has switching to 1-indexing been considered? I don't necessarily think it's a good idea to change the internal representation in the generated C code, but it may be less surprising for users if all output and errors were 1-indexed instead.

**Comment by Aerijo** [comment]
I'd like a flag to specify this. Keep it the way it is by default, but allow users to request adjusted numbers for when they're doing it by eye in an editor.

**Comment by maxbrunsfeld** [comment]
I'm ambivalent on this. I think that it's good for the API to be zero-based, because most other APIs are zero-based. But I agree that the vast majority of *UIs* are one-based, for line numbers: text editors, tools like `grep`, `ripgrep`, GitHub.com, etc.

We probably should have made the UI one-based from the start, to match other tools, even though the API is zero-based. Honestly, I'd be ok with just changing it.

@Aerijo What kinds of problems do you foresee with changing it entirely?

**Comment by Aerijo** [comment]
I’m not sure what to expect. I’m fine with totally changing, but thought a flag would still allow some choice.

**Comment by Arcanemagus** [comment]
Maybe they did the same thing I did and only read the body... which sounds like a request to change the API, not just the CLI output since that bit of information is only in the title.

I'd say user visible stuff like the CLI output should be 1-based, but the API _definitely_ shouldn't be.

**Comment by maxbrunsfeld** [comment]
Alright, I think let’s change the CLI output. @jmitchell Interested in opening a PR?

**Comment by jmitchell** [comment]
Sure, I'll get on that soon.
