### ISSUE TITLE
wasm-tree-sitter

### ISSUE THREAD

**Issue by drom** [tree-sitter/tree-sitter#291]
Any plans on creating WebAssembly bindings to the `tree-sitter`?
That would allow running any `tree-sitter` parser grammar in the browser.

**Comment by drom** [comment]
I have found this repo: https://github.com/stereobooster/tree-sitter-wasm
Anybody tried?

**Comment by maxbrunsfeld** [comment]
I think this is a duplicate of https://github.com/tree-sitter/tree-sitter/issues/252. I am interested in creating WebAssembly bindings. I think they will unfortunately be a bit limited compared to `node-tree-sitter`, because of some current limitations of WASM, but it still seems worthwhile to enable use on the web.
