### ISSUE TITLE
Syntax rely on regex assertions

### ISSUE THREAD

**Issue by lwshang** [tree-sitter/tree-sitter#296]
I'm trying to create a q (KDB+) grammar for tree-sitter. It has some special syntax which make the same set of characters can have different meaning whether the code is at the beginning of a lone or not.

For example, the syntax rule of comments in this language is:

> As first and only non-whitespace char on a line:
> * `/` starts a multiline comment
> * `\` terminates a multiline comment or, if not in a comment, comments to end of script

```q
/
    Oh what a beautiful morning
    Oh what a wonderful day
\
a:42
\
ignore this and what follows
the restroom at the end of the universe
```

I want to match the `/` or `\` shows at the beginning of a line and the rest of the line only contains whitespace characters. So I come up with a regex like `/^\/\s*$/`. Unfortunately, tree-sitter doesn't support assertion like `^` and `$`.

Is it possible to support for regex assertion? Or is there some other tricks to implement such syntax rule? Do I have to write an external scanner?

**Comment by maxbrunsfeld** [comment]
Someday, I'd like to add support for the `^` and `$` assertions, but I don't personally have plans to work on that feature soon.

I think that currently, you'll have to write an external scanner. Those are documented here: http://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners.

Also, even once we add the `^` assertion, you might *still* want to use an external scanner: the `/` can occur after spaces on the same line, and ideally, these spaces would be treated as whitespace, rather than being part of the comment token, right? If you used the `^` assertion in your `comment` rule, you would have to match any preceding spaces as *part* of the comment.

**Comment by travis-leith** [comment]
@lwshang did you end up creating a q grammar for tree-sitter? I need one for a very speculative idea I want to try out. If someone else has put one together great. Otherwise I will give it a go, but never tried something like this before.
