### ISSUE TITLE
Rationale for token-content-targeting highlight rules

### ISSUE THREAD

**Issue by marijnh** [tree-sitter/tree-sitter#298]
(Again, I am on the whole highly impressed by the design of this system.)

But one thing irks me a bit—why do you, for example in the JavaScript grammar, so heavily use highlighting rules that dispatch on a token's content, rather than encoding that something is a keyword or operator or similar in the grammar itself? It seems this doubles the string-matching work that has to be done—the grammar already recognized the token as a keyword, but you're making the highlighter match it to a list of keywords again. And worse, it's somewhat error prone. When you write such a highlight rule, you have to be very certain that your grammar doesn't allow that string to occur in another role. This necessitates the use of the `property_identifier` token in the JavaScript grammar to prevent property names from being highlighted as keywords, for example. So if you've already got such a mechanism to encode information about the token in the grammar, why not always do it there? You could, in your `grammar.js`, define a function like `kw("for")` (or even `` kw`for` ``), that allows you to do the tagging with little syntactic overhead.

Is there something I'm missing?

**Comment by maxbrunsfeld** [comment]
> so heavily use highlighting rules that dispatch on a token's content, rather than encoding that something is a keyword or operator or similar in the grammar itself? It seems this doubles the string-matching work that has to be done

We almost never dispatch on a token's content. Instead, we dispatch on a token's type, which has both an integer representation and a string representation. It's probably not really obvious from the API that it works that way...

In a property sheet, when you target a named rule like this:

```css
call_expression > identifier {
  scope: 'function';
}
```

the state transitions for that selector get represented by objects like [this](https://github.com/tree-sitter/tree-sitter-javascript/blob/bce66637e5b45aa36217bc56c11a10b58182b392/src/highlights.json#L247-L251):

```json
{
  "type": "call_expression",
  "named": true,
  "state_id": 5
},
```

and when you target an *anonymous* node like this:

```css
[token="for"] {
  scope: 'keyword';
}
```

the state transition gets represented in a similar way:

```json
{
  "type": "for",
  "named": false,
  "state_id": 4
},
```

So the JSON files themselves refer to all node types by their string representation. But then [when *loading* these files](https://github.com/tree-sitter/tree-sitter/blob/db953312b8ab8064943883d4f1d14c1aa52741e9/lib/binding/lib.rs#L787-L788), we use the `TSLanguage` object to look up the single integer representation of each node, so the `type` and `named` fields are no longer needed. Then, when walking the Tree, we can select the appropriate state transitions by [a simple integer lookup](https://github.com/tree-sitter/tree-sitter/blob/db953312b8ab8064943883d4f1d14c1aa52741e9/lib/binding/lib.rs#L689-L691).

**Comment by maxbrunsfeld** [comment]
In certain places, we do match on a tokens' textual content in order to highlight things like built-ins, which aren't recognized by the grammar itself. For example, [there's a rule](https://github.com/tree-sitter/tree-sitter-javascript/blob/bce66637e5b45aa36217bc56c11a10b58182b392/properties/highlights.css#L41-L43) to highlight `require` differently from other functions:

```css
call_expression > identifier {
  &[text='^require$'] {
    scope: 'function.builtin';
  }
}
```

The `text` attribute gets compiled to a special optional `text` attribute on the state transition. At runtime, [we match these state transitions](https://github.com/tree-sitter/tree-sitter/blob/db953312b8ab8064943883d4f1d14c1aa52741e9/lib/binding/lib.rs#L694-L702) by actually retrieving the node's text and doing a regex match.

This kind of stuff *could* be handled by the grammar, but it would bloat the parser binary and make it take longer to compile, so I prefer to handle this at the syntax-highlighting layer.

**Comment by marijnh** [comment]
> Instead, we dispatch on a token's type, which has both an integer representation and a string representation.

Ahh, I did indeed not get that and assumed token= was a generic content string match. That makes a lot more sense than what I thought it was doing. Thanks once again for explaining!

**Comment by maxbrunsfeld** [comment]
Yeah, `[token="function"]` might not be the best API for this. I just need some way of selecting the "anonymous" nodes that's separate from the normal syntax for selecting named nodes. Because the anonymous nodes are specified in the grammar using string literals, some kind of quoted string syntax seemed useful.

Originally, I let you use string literals directly in the selectors, like

```css
"for", "if" {
  scope: 'keyword';
}
```

But most CSS parsers don't allow that, so I switched to that `[token]` attribute. It's not ideal that it *looks* so much like the `[text]` attribute, even though it works very differently.
