### ISSUE TITLE
parsers with duplicate symbols?

### ISSUE THREAD

**Issue by bfredl** [tree-sitter/tree-sitter#318]
I'm currently working on implementing property sets and highlighting for nvim. When debugging some missing missing highlights I noticed that some parsers might have duplicate symbols, which my code assumed wasn't possible. For instance the master version of the javascript parser has both symbols 1 and 45 being `"identifier"` (both of type `TSSymbolTypeRegular`). Is this intentional or a bug? 

The parser contains the line `[sym_jsx_identifier] = "identifier",` but all other jsx_ symbols seems to be exported with jsx_ names. Though it would be a policy desicion of tree-sitter itself if such duplicate symbols is considered allowed.

**Comment by maxbrunsfeld** [comment]
Yeah, this is not ideal, but it is currently the expected behavior: more than one numeric `TSSymbol` value can map to the same conceptual node type.

The reason it occurs is because of a certain optimization I added to reduce the size of the parser binaries. The optimization has to do with certain usages of the `alias` function in grammars, and is described in #197. Basically, certain kinds of aliases are implemented by just changing the `ts_symbol_names` entry for the aliased symbol, which can introduce duplicate names.

The reason that it occurs in this case is because in the JavaScript grammar, [the `jsx_identifier` Rule is always aliased](https://github.com/tree-sitter/tree-sitter-javascript/blob/d4f8134060a4e35e1376c30a5a951ebd79fa9978/grammar.js#L468) as `identifier`. The idea behind this aliasing is that, even though identifiers have different matching rules within JSX tags, we want them to still *appear* as normal `identifier` nodes in the tree, as opposed to having a separate node type just for JSX identifiers.

I'd *like* to avoid having duplicate symbols mapping to the same name and type, but I'm not sure how to do it without either:
1. Losing the improvement that #197 gained in parser binary sizes
2. Changing the parser ABI and introducing complexity

Thus far, it hasn't been to hard to work around the fact that multiple `TSSymbol` values can map to the same string, so I've just been leaving it as is.

**Comment by bfredl** [comment]
> Thus far, it hasn't been to hard to work around the fact that multiple TSSymbol values can map to the same string, so I've just been leaving it as is.

Yeah it wasn't so hard to fix either in nvim, I just need to map symbols to an array of numeric ids instead to a single id.
