### ISSUE TITLE
Provide a mode that produce *all* possible parse trees for ambiguous grammars

### ISSUE THREAD

**Issue by yanok** [tree-sitter/tree-sitter#3219]
### Problem

Tree-sitter generates GLR parsers, that can parse truly ambiguous languages. Yet, at the moment, I think tree-sitter uses some heuristics to pick a single parse tree. I totally understand that for most practical applications that's what people usually want, but would it be possible to provide an extra API that would return *all* possible parse trees? Or, at least, return a flag indicating that the returned tree is not the only possible one?

**Comment by WarpspeedSCP** [comment]
I'm just passing by here, but this could very easily result in a combinatorial explosion of possible parse trees depending on size and ambiguity.

**Comment by yanok** [comment]
Sure, if a grammar is wildly ambiguous, there is a chance of combinatorial explosion. Even though I don't think that's going to be an issue in practice, but yeah, then maybe just returning a flag indicating "we had to guess, another parse trees are possible" would be better performance wise.

**Comment by ObserverOfTime** [comment]
Printing a warning when running `tree-sitter generate` (or `tree-sitter parse`?) might be the best option.

**Comment by amaanq** [comment]
During parsing, the max # of stack versions tree-sitter will retain is 6, and any excess ones are discarded based on the error cost of the stack. Also, occasionally during parsing, tree-sitter "condenses" the stack by discarding versions that are clearly worse than others (error cost and dynamic precedence come into play here). I don't think we want to support an API that returns all possible valid trees, due to the increased complexity, memory usage, and potential combinatorial explosion this entails (though this can be limited). At the end of parsing, if there *are* multiple valid trees with the same error cost and dynamic precedence, the heuristic used to pick one tree over another is by selecting the "smaller" or "earlier" tree, which is a combination of checking the symbol and child counts of the two trees using a DFS.

I hope that answer helps you, but to summarize, I don't think it's feasible to introduce a mode that returns every possible parse tree.
