### ISSUE TITLE
How to find performance problems

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#324]
Hey there, I'm at a point where I don't know what else I can do.

Tests for my implementation work fine https://github.com/Razzeee/tree-sitter-elm/blob/master/script/parse-examples
on ci and on my manjaro linux.

But if I use 'node-tree-sitter' to interface with it or use `npx tree-sitter parse -q examples/elm-browser/src/Debugger/Expando.elm` to test something, my linux pc starts hanging and I don't think it will complete. I have been restarting or ctrl+c stopping it.

It seems to be connected with file sizes as that's one of the first big files I tried to feed via 'node-tree-sitter'. 

So is there something obvious wrong with my parser? (I'm not using `word`, just looked at it, would need two nodes for that) How would I even find where this is coming from? Or do I need to load such files async?

**Comment by maxbrunsfeld** [comment]
It probably isn't caused by file size. Your parser is probably getting into an infinite loop. The way to debug it is to:

1. Find a file that reproduces the problem (it looks like you're already done that)
2. Run `tree-sitter parse --debug` on the file
3. Terminate the program (`ctrl-c` or something) when you see the output start to repeat itself.
4. (optional) Try to reduce the size of the file while still triggering the bug
5. Determine what is repeating.

The most likely causes of an infinite loop are:

* You're creating zero-length tokens somewhere
* Your external scanner is infinitely looping

**Comment by Razzeee** [comment]
I'm confused why that would only show when run under certain circumstances.

But you seem to be right, getting this repeating all over:
```
process version:0, version_count:1, state:1064, row:171, col:11
shift_extra
process version:0, version_count:1, state:1064, row:171, col:11
shift_extra
process version:0, version_count:1, state:1064, row:171, col:11
shift_extra
process version:0, version_count:1, state:1064, row:171, col:11
shift_extra
process version:0, version_count:1, state:1064, row:171, col:11
shift_extra
process version:0, version_count:1, state:1064, row:171, col:11
shift_extra
process version:0, version_count:1, state:1064, row:171, col:11
shift_extra
process version:0, version_count:1, state:1064, row:171, col:11
```

`shift_extra` seems to be something internal? Not sure what to do, guidance welcome :)

**Comment by Razzeee** [comment]
I was able to fix it with this comment https://github.com/Razzeee/tree-sitter-elm/commit/c88f9bf686a35c77b937540e6741421a240092ba
Not sure how to parse it better, but it seems to work with the test suite.

So the real question left would be, why does this happen on some ways you can execute the parser (bash directly, node bindings) and not when run via ci (which also runs stuff via bash, as you can see)
