### ISSUE TITLE
Parsing newline issue after updating from 0.13.x to 0.14.x

### ISSUE THREAD

**Issue by edmundito** [tree-sitter/tree-sitter#329]
Hi, I'm having an issue with my C-like grammar after attempting to update from 0.13.23 to 0.14.7 where my parser is now running over another line and parsing it as an argument. Maybe someone could help? I have not been able to identify the problem yet.

Rules:
```js
    preproc_def: $ =>
      seq(
        preprocessor('define'),
        $._preproc_identifier,
        optional($.preproc_arg),
        '\n'
      ),

    preproc_error: $ => seq(preprocessor('error'), $.preproc_arg, '\n'),
```

You can see the current version of the grammar at:
https://github.com/edmundito/tree-sitter-ags-script/blob/3369ac910307530e4441edfbfb81b95e21f6fdf9/grammar.js

Example:
```
int main() {
  #define TEST
  #error TEST
}
```

Expected:
```
(script
  (function_definition
    (primitive_type)
    (function_declarator (identifier) (parameter_list))
    (compound_statement
      (preproc_def (preproc_identifier))
      (preproc_error (preproc_arg)))))
```

Actual: It parses into the next line and sees error as a preproc_arg.
```
(script
  (function_definition
    (primitive_type)
    (function_declarator (identifier) (parameter_list))
    (compound_statement
      (preproc_def (preproc_identifier) (preproc_arg)))))
```

**Comment by maxbrunsfeld** [comment]
This seems similar to rules in [the C grammar](https://github.com/tree-sitter/tree-sitter-c). Can you investigate how your grammar differs from that one? In particular, is there any difference between your `preproc_arg` rule and the one from the C grammar?

I'm going to close this one out since that's all the information I can provide without seeing the `preproc_arg` rule. Let me know if you get any further with debugging this. Thanks!
