### ISSUE TITLE
`ts_node_is_missing()` fails if missing node wraps hidden rules

### ISSUE THREAD

**Issue by DavisVaughan** [tree-sitter/tree-sitter#3332]
### Problem

This is my attempt to bring https://github.com/tree-sitter/tree-sitter/issues/1043 back to the forefront, but with a more convincing example to prove that this is a bug in tree-sitter core, and not just the cli (as it was tagged there), so hopefully a fix can get in the next release 🤞 .

Consider tree-sitter-julia's `identifier` rule `identifier: $ => $._word_identifier`:
https://github.com/tree-sitter/tree-sitter-julia/blob/acd5ca12cc278df7960629c2429a096c7ac4bbea/grammar.js#L975

For some reason unknown to me, `identifier` rules seem to be used as the nodes that get inserted as `MISSING` for pretty much all grammars. All good there.

However, in this particular grammar the `identifier` rule points to a hidden rule, `_word_identifier`. That somehow prevents `ts_node_is_missing()` from detecting that the inserted `MISSING` `identifier` node is actually missing, rendering that function pretty much useless for the julia grammar.

I have come up with a failing test for this to prove it, and I have pushed this to GitHub if that is easier for you to pull from:
https://github.com/DavisVaughan/tree-sitter/commit/34c5ffc267efb0695a84381116c8d62e454ba5b2

Note that I had to add Julia to the list of fixtures to fetch from, as I could not find an example of an existing fixture grammar where the `identifier` node points to a hidden rule like `_word_identifier` (which is probably why you all haven't really noticed this issue before).

```rust
#[test]
fn test_node_is_missing() {
    let mut parser = Parser::new();
    parser.set_language(&get_language("julia")).unwrap();
    let source = "x =";

    let tree = parser.parse(source, None).unwrap();

    let node = tree.root_node().child(0).unwrap();
    assert_eq!(node.kind(), "assignment");

    // The `x`
    let child = node.child(0).unwrap();
    assert_eq!(child.kind(), "identifier");

    // The `=`
    let child = node.child(1).unwrap();
    assert_eq!(child.kind(), "operator");

    // This is a MISSING node!
    let child = node.child(2).unwrap();
    assert_eq!(child.kind(), "identifier");

    // See, it is 0 width and everything (this passes)
    assert_eq!(
        child.range(), 
        Range {
            start_byte: 3, 
            end_byte: 3, 
            start_point: Point { row: 0, column: 3 }, 
            end_point: Point { row: 0, column: 3 }
        }
    );

    // But it isn't declared as missing here.
    // This should pass, but does not!
    assert!(child.is_missing());
}
```

### Steps to reproduce

Check out the commit from above and run the tests

### Expected behavior

`ts_node_is_missing()` should detect the missing node, even if it wraps a hidden rule like that

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.5

### Operating system/version

macOS 13.6.5

**Comment by amaanq** [comment]
After looking this through, I wouldn't say this is a bug but rather a subtle gotcha of tree-sitter - IMO, `_word_identifier` in Julia shouldn't even exist, since you can't actually access it as it's a hidden node (prepended with underscore). The node `identifier` was not the terminal node that tree-sitter recovered from an error with, but rather the `_word_identifier` node, which reduces to an `identifier`. The `identifier` node *itself* is not a missing node, but rather is comprised of one, that being the `_word_identifier` node. *This* node itself would have `is_missing` return true if it was not a hidden node and could be accessed on the Rust side. I think the proper solution for this would be to *not* use hidden terminals in general (meaning `_word_identifier` wouldn't exist, and instead `identifier` would be the terminal), but another solution for this could be to add a `has_missing` API function, though that seems a little overkill to remedy this edge case.

@maxbrunsfeld what do you think?

**Comment by DavisVaughan** [comment]
`_word_identifier` seems useful for wrapping up a regex that is used in 2 separate places - what would you do instead? Maybe a named function that is used in `word:` and `identifier:` rather than a hidden node?

I had the same kind of use case here: https://github.com/r-lib/tree-sitter-r/pull/112/files#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbR515
- `_identifier` was used in two places
- It's nice to be able to read `identifier: $ => choice($._identifier, $._quoted_identifier)` over the fully inlined thing

---

Slightly adjacent question - How do grammar authors know which node is going to be picked as the one associated with `MISSING`? Is it always `identifier`?
