### ISSUE TITLE
`generate --no-bindings` still generates `package.json`

### ISSUE THREAD

**Issue by maloewe-ona** [tree-sitter/tree-sitter#3528]
### Problem

When using `tree-sitter generate --no-bindings` it still generates the `package.json` file.
This is a bit unexpected because:
- `package.json` does not seem needed when you want to compile the `src/` files manually by hand
- `package.json` contains multiple entries which refer to the bindings (and are therefore non-functional):
    ```json
    "main": "bindings/node",
    "types": "bindings/node",
    "files": [
      "binding.gyp",
      "bindings/node/*",
    ],
    "scripts": {
      "install": "node-gyp-build",
      "test": "node --test bindings/node/*_test.js"
    },
    ```

Is that intentional?

### Steps to reproduce

1. Create an arbitrary `grammar.js`, for example:
    ```javascript
    module.exports = grammar({
      name: 'YOUR_LANGUAGE_NAME',

      rules: {
        source_file: $ => 'hello'
      }
    });
    ```
2. Run
    ```sh
    tree-sitter generate --no-bindings
    ```

### Expected behavior

- Only `src/` is generated
- No `package.json` is generated

### Tree-sitter version (tree-sitter --version)

- 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263)
- _master_ (4f97cf850535a7b23e648aba6e355caed1f10231) (binary from https://github.com/tree-sitter/tree-sitter/actions/runs/10316621028)

### Operating system/version

Windows 10

**Comment by sogaiu** [comment]
IIRC, if you have an en existing `package.json` file, it may not get modified.

I believe a small amount of info in `package.json` gets used in some places [1] so I tend to keep a very minimal one around, e.g. like [this](https://github.com/sogaiu/tree-sitter-janet-simple/blob/ea842cb57a90865c8f50bcb4499de1a94860f3a4/package.json).

I've found it seems to work out better to give in and just go the minimal way instead of trying to eliminate it altogether.

Just my two local currency units :)

---

[1] For example, among some other subcommands, I think the `dump-languages` subcommand will use it.

**Comment by amaanq** [comment]
`package.json` has a `tree-sitter` field that the runtime uses to detect language/filetype info, as well as the injection regex + queries. It's unlike the other bindings files so this is intentional - in the future we'll move to a dedicated `tree-sitter.json` file.
