### ISSUE TITLE
Tree traversing degradation on nodes with an enormous amount of children (follow-up #1356)

### ISSUE THREAD

**Issue by gregnis** [tree-sitter/tree-sitter#3558]
### Problem

Follow up to #1356

Using the same test file (https://github.com/miks1965/tree-sitter-pascalabcnet/blob/master/src/parser.c) as in the referenced issue, parsing takes 8-9 seconds, and applying highlights - another 8-9 seconds. I tried the same file in Zed editor, and it has a similar lag before the code is highlighted.

### Steps to reproduce

See the description

### Expected behavior

See the description

### Tree-sitter version (tree-sitter --version)

0.23.0

### Operating system/version

Windows 10

**Comment by amaanq** [comment]
I don't want to entirely rule out that performance can be improved here, but I really don't think there's much that we can do - the file is around 1 million LOC, and on my machine parsing speed seems similar to that of files of much smaller sizes, so that doesn't seem to be an issue. For me, I'm seeing around 17-18k bytes/ms (which translates to 17m bytes/s, and your given file is ~26m bytes, so that comes out to be ~1.5s). On smaller files, I'm seeing anywhere from 13-20k bytes/ms, so the parsing speed for the large file seems to be well within the expected range. 

Then, querying with the upstream C highlights file takes around 1.38x the parse time (around 2s for me), which isn't that much far off from other smaller C files I've tested on (ranging from 0.9x-1.3x the parsing time). 

The best way to avoid any lag, if you're experiencing any in your own application or Zed, is to not let parsing block your code by leveraging the timeout functionality, but I'm guessing Zed already does that anyway. As for actual parsing and highlighting speed, well, your hardware is the limit in theory.
