### ISSUE TITLE
Issue with highlighting in atom

### ISSUE THREAD

**Issue by ncurtislinkeng** [tree-sitter/tree-sitter#378]
I'm trying to integrate a custom language into Atom using Tree Sitter. In certain cases, keywords of my language are not having the highlighting style applied to them. For example, in my CSON file I have:

  '"pack_1"': 'storage.modifier'
  '"pack_2"': 'storage.modifier'
  '"pack_4"': 'storage.modifier'

but none of these words appear styled in source files of my language.....

**Comment by ncurtislinkeng** [comment]
@maxbrunsfeld Any ideas?

**Comment by maxbrunsfeld** [comment]
If Tree-sitter is generating the correct parse tree (which you can examine either via the `tree-sitter parse` command or by manually inspecting it in the `node` console), then this is an Atom issue.
Can you open this issue on the Atom repo, instead of here?

You'll need to share more details about the grammar / syntax tree that you're working with.  First question is, are you sure that there is a node in your tree that matches? Check that you can find a node in your tree such that `node.type === "pack_1" && !node.isNamed`.
