### ISSUE TITLE
Fuzzing a tree sitter parser

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#388]
Has anybody done work on fuzz testing their language parser?
This aims at tree-sitter itself, I suppose? https://github.com/tree-sitter/tree-sitter/blob/master/test/fuzz/README.md

I think it would be useful to be able to fuzz an implementation, especially if there is an external scanner included.

**Comment by maxbrunsfeld** [comment]
That script fuzzes several of the common parsers, so if you're interested in using `libfuzzer`, you'll probably want to do almost exactly the same thing as that script.

Closing this out since there are already some docs, and an example to use as a starting point. I don't think Tree-sitter should present any significant challenges for fuzzing compared to any other small C library, so I don't think this requires work on the Tree-sitter side to make possible.

**Comment by Razzeee** [comment]
Fuzzing is not run as part of any pipeline is it?

**Comment by theHamsta** [comment]
https://github.com/ikatyang/tree-sitter-markdown/issues/14 maybe this helps on how to use it.

**Comment by Razzeee** [comment]
I'm trying to hunt down a `memory access out of bounds` error, which I can't reproduce, but a contributor seems to get from time to time. Your MR is helping, I still failed to get this going. I resorted to use a ubuntu vm to be able to use your instructions, struggled some more. As your instructions assume, that I've had run `make` already.

Also is the `python2` thing still true? Might be worth to change the script to call `python2` instead then?

Running the fuzzing now, let's see :)

**Comment by Razzeee** [comment]
Will the fuzzer show problems with incremental tree updates?
