### ISSUE TITLE
What are the relationships between is_missing, is_error, has_error in the Rust binding?

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#396]
[api.h](https://github.com/tree-sitter/tree-sitter/blob/master/lib/include/tree_sitter/api.h#L406) says that "Missing nodes are inserted by the parser in order to recover from certain kinds of syntax errors.", while `has_error` is "Check if the node is a syntax error or contains any syntax errors".

Does that mean that `is_missing = not has_error` (since it already recovered)?

What about `is_error`? It's defined as `self.kind_id() == u16::MAX`, and doesn't seem to have an equivalent in the C API.

**Comment by maxbrunsfeld** [comment]
* `is_error` means the node is an "error" node. it contains content that does not match the grammar, and which needed to be "skipped" in order to create a valid syntax tree.
* `is_missing` means that the node needed to be *inserted* in order to create a valid syntax tree
* `has_error` means the node *contains* an error or a missing node somewhere inside of it.

**Comment by maxbrunsfeld** [comment]
I finally published a version of the crate that has decent docs. https://docs.rs/crate/tree-sitter
