### ISSUE TITLE
Comparing a node text causes heavy cpu load

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#404]
I'm experiencing this problem after updating to wasm.

Here is an js SSCCE to replicate it https://github.com/Razzeee/tree-sitter-bounds-error/tree/cpu-compare

The things that seem important, is that the tree must have been updated and that we compare a string with our SyntaxNode.text

I tried to remove as much as possible from the example.

**Comment by maxbrunsfeld** [comment]
Thanks for the example; that helped to explain what had happened. It looks like you re-parsed a tree after making the text shorter, but did not call `edit` on the old tree to make it consistent with the changed text. So the new syntax tree was in an inconsistent state with its text.

Previously, there was a bug where this inconsistency would cause an infinite loop when computing the text. I have a fix for this now. It's impossible to give the "right" text in this situation, but we can just truncate the text so that it doesn't infinite loop.

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/tree-sitter/tree-sitter/commit/9848ceb3e27254250faccbc080dd5be572fb9983.

**Comment by Razzeee** [comment]
this wasn't a problem with the non-wasm version. Did it do what you fixed?
I'm only calling edit before parse in some cases https://github.com/elm-tooling/elm-language-server/blob/master/src/providers/astProvider.ts#L51 
Do I need to address that?
