### ISSUE TITLE
Optimize file size for WASM language builds

### ISSUE THREAD

**Issue by curran** [tree-sitter/tree-sitter#410]
The WASM build I get for JavaScript is currently 616kB, after following the [build instructions](https://www.npmjs.com/package/web-tree-sitter#generate-wasm-language-files).

My hypothesis is that the build is somehow unnecessarily bloated, since the WASM build of tree-sitter itself is only 252kB. Perhaps the size of the language builds could be reduced by using the same technique described in https://github.com/tree-sitter/tree-sitter/pull/321 , namely

>whitelisting the functions that emscripten should export

Thoughts?

**Comment by maxbrunsfeld** [comment]
The parser binaries are large for a different reason - there are a few constant data structures that are just large, partly due to some naive decisions that I made in tree-sitter itself, and partly due to the way that some of the grammars are written.

PR https://github.com/tree-sitter/tree-sitter/pull/334 will make a significant difference. It’s done, but because of some binary compatibility concerns with Atom, I’m waiting a little bit to merge it.

There will probably be more code size improvements after that. But none of them are trivial configuration changes like the one that I mentioned for the WASM build of the library itself.

**Comment by curran** [comment]
Thanks for your thoughts here!

**Comment by maxbrunsfeld** [comment]
Alright, some optimizations have landed in the past month. If you load [the playground](http://tree-sitter.github.io/tree-sitter/playground) with a clean cache, you can see that things have improved to some degree:

![Screen Shot 2019-08-30 at 9 32 48 PM](https://user-images.githubusercontent.com/326587/64059274-f099dd00-cb6d-11e9-8e04-29d88b5a60ae.png)

Those are gzipped sizes, but that's what really matters anyway.

Note that these `.wasm` parsers have been generated in a newer mode which is still experimental (and is not on the `master` branch of the language repos). The new mode is available via the `tree-sitter generate --next-abi` command.

I think there is still room for some optimization, especially of specific grammars (like the Rust grammar), but the sizes are much more reasonable than they were. I'm going to close this one out for now; let me know if you have other ideas or questions.
