### ISSUE TITLE
rust bindings: Linking fails on Windows

### ISSUE THREAD

**Issue by Gregoor** [tree-sitter/tree-sitter#431]
Heya,

thanks for this great (and massive) effort. I've started playing with the code, but now I'm getting a linking error on Windows, namely:
```
error: linking with `link.exe` failed: exit code: 1120
[...]
 = note: soy-5887ba1481306f75.fsjeiyhceh6stil.rcgu.o : error LNK2019: unresolved external symbol tree_sitter_javascript referenced in function _ZN3soy4main17ha672dca11a9d0e4bE
          C:\Users\grego\code\soy\target\debug\deps\soy-5887ba1481306f75.exe : fatal error LNK1120: 1 unresolved externals
```

The code is basically the one from the README example:
```
extern "C" { fn tree_sitter_javascript() -> Language; }
```

Now I've never worked with Rust calling C functions before, so I suppose I'm doing something wrong here. Would I need to add a build file to build & link the parser for the lang I'm interested in (and if so, might there already be an example of that somewhere?)?

**Comment by maxbrunsfeld** [comment]
> Would I need to add a build file to build & link the parser for the lang I'm interested in

Yes, exactly. You should include a `build.rs` file that uses the [`cc-rs`](https://github.com/alexcrichton/cc-rs) crate to compile `tree-sitter-javascript`.

For JavaScript, there are two C source files that need to be compiled: the generated parser [src/parser.c](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/src/parser.c) and the external scanner, [src/scanner.c](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/src/scanner.c). For some languages (like [`tree-sitter-python`](https://github.com/tree-sitter/tree-sitter-python)) the external scanner is written in C++ and is called `scanner.cc` instead. Other languages (like [`tree-sitter-java`](https://github.com/tree-sitter/tree-sitter-java)) do not have external scanners at all.

> might there already be an example of that somewhere?

I wish I had a better example. The `tree-sitter` CLI does use `cc-rs` internally, for dynamically compiling and loading parsers when you run `tree-sitter parse` or `tree-sitter test`, but it uses the crate in a somewhat non-standard (and more complex way). It [starts by using the normal API](https://github.com/tree-sitter/tree-sitter/blob/aace0970d8a7f6d0eb56e9ba19e4eb7b141f7e77/cli/src/loader.rs#L267-L273), but then it performs some platform specific code in order to generate a dynamic library instead of a static one.

There's also this project: https://github.com/mozilla/rust-code-analysis. I don't know anything about it, but I noticed that @calixteman (who has made big contributions to various Tree-sitter languages) had created it  it, and it uses Tree-sitter from Rust and has a `build.rs` that statically compiles in a number of Tree-sitter languages.

**Comment by Gregoor** [comment]
Great, thanks for the detailed response! That should be enough to get me started. Once I've set it up for myself, should I add a short summary of it to the README or is this obvious to proficient rust-c users anyway?

**Comment by rfdonnelly** [comment]
It wasn't obvious for me either.  I wrote "[Using Tree-sitter Parsers in Rust](https://rfdonnelly.github.io/posts/using-tree-sitter-parsers-in-rust/)" based on what I learned.

I also found this minimal example helpful: [fkohlgrueber/tree-sitter-example-rust](https://github.com/fkohlgrueber/tree-sitter-example-rust)
