### ISSUE TITLE
ts_tree_edit: Can I use only bytes and not TSPosition?

### ISSUE THREAD

**Issue by DLehenbauer** [tree-sitter/tree-sitter#445]
I was wondering if it is possible to edit the tree specifying only the byte offsets of the changed ranges (i.e., the opposite question of #210).

For example, would anything bad happen if I always specify a column of 0 and pass the byte offset for the row?

I ask because in my scenario the input source is a steam of character-oriented insert/remove messages.

**Comment by maxbrunsfeld** [comment]
I'm not 100% sure what will happen. I *think* that it will work, because byte offsets are what Tree-sitter uses internally, whereas `row`/`column` information is only maintained so that it can be used via the public API. Obviously, this will cause `row`/`column` information to be inconsistent and worthless.

I would say give it a try and let me know how it goes.

**Comment by casouri** [comment]
AFAICT, this works, and this is what I'm doing in Emacs. Emacs uses a gap buffer and doesn't keep track of row and column information. So I just pass tree-sitter functions the byte offset and a dummy TSPoint. It would be even better if you can make sure not to break this in the future :-)
