### ISSUE TITLE
Generated node-types.json files are incorrect when repeating regexps

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter#458]
`tree-sitter-json` has this rule:

```javascript
    string_content: $ => repeat1(choice(
      token.immediate(/[^\\"\n]/),
      $.escape_sequence
    )),
```

which results in this entry in `node-types.json`:

```json
  {
    "type": "string_content",
    "named": true,
    "fields": {},
    "children": {
      "multiple": true,
      "required": true,
      "types": [
        {
          "type": "escape_sequence",
          "named": true
        }
      ]
    }
  },
```

Note that says that string content must be a non-empty list of escape sequences, which is clearly incorrect; it should actually be a non-empty list of escape sequences or non-escape sequence characters, but the latter are elided.

Furthermore, I can’t figure out how to make them included without pulling the non-escape-sequence character out into a new rule, which I’m not sure is actually a good solution for this problem.

Either way, if these characters are elided then really the contents should be an optional list of escape sequences, with the textual contents being any interleaved bytes.

**Comment by maxbrunsfeld** [comment]
Alright, I believe this was fixed by https://github.com/tree-sitter/tree-sitter/commit/dc7997fdbb942fdcaf79abe8f0dec446de6c1b3b. [Here's](https://github.com/tree-sitter/tree-sitter-json/commit/065aab9aaf9cbc1597bcf49d86c24f64cc7aa446#diff-a71f4863f815bc706675d50525bd296fL132-R132) the change to `tree-sitter-json` after regenerating it.
