### ISSUE TITLE
Serialize tree to JSON object

### ISSUE THREAD

**Issue by ediardo** [tree-sitter/tree-sitter#528]
Hi,

is there any existing function for serializing the tree (starting from the `rootNode`) to a JSON object?

**Comment by maxbrunsfeld** [comment]
No, Tree-sitter doesn't provide that because there are so many ways you might want to format a tree as JSON, depending on what data you're interested in. It's pretty easy to implement this yourself. If you're going to be walking the entire tree, you should probably use a [`TreeCursor`](http://tree-sitter.github.io/tree-sitter/using-parsers#walking-trees-with-tree-cursors).
