### ISSUE TITLE
Generate a parser.cs (c#)

### ISSUE THREAD

**Issue by ericoporto** [tree-sitter/tree-sitter#540]
Can the tree sitter parser generator be modified to generate the parser in C# instead of C? Where should I look into the code if I wanted to add this functionality?

I tried to simply generate C# bindings using SWIG for parser.c and it kinda works.

**Comment by maxbrunsfeld** [comment]
I think that for C# support, we would go the route of creating bindings to the C library, rather than generating C# code. The reason is that the parsers do not operate by themselves, there is also a non-trivial C library that they rely on, and porting that to C# would be complex.

Are you running into specific problems with the binding?

**Comment by ericoporto** [comment]
Nope, no problems, I generated using swig. :)
