### ISSUE TITLE
Feature request: Generate tmLanguage (and possibly other highlighting formats) from tree-sitter grammar.

### ISSUE THREAD

**Issue by back2dos** [tree-sitter/tree-sitter#563]
Something similar has been proposed [the other way around](https://github.com/tree-sitter/tree-sitter/issues/139) - which is the wrong way around. I'd love to write tree-sitter grammar and instead of a parser, get a tmLanguage file. I'm asking specifically due to VSCode, because it supports only tmLanguage and it's not clear if/when that'll change ... ¯\\\_(ツ)_/¯

Given tree-sitter's expressiveness, I think it would make for a great candidate as a single source of truth across common syntax formats. Could be tmLanguage, or pygments lexers or sublime syntax or whatever. I have limited formal knowledge of grammars at best, but it seems to me that if tree-sitter holds enough information to fully parse a language, than that should suffice for producing formats that concern themselves merely with highlighting it ... right? Is that correct(-ish) or total nonsense?

**Comment by Arcanemagus** [comment]
TextMate simply can't parse the same things that Tree-sitter can, it's _impossible_ for that engine to do so. This means it is impossible to generate a tmLanguage file from a Tree-sitter grammar.

The major limitations of TextMate was one of the reasons Tree-sitter was created in the first place 😉.

**Comment by maxbrunsfeld** [comment]
I think that it's possible that you could generate something that matches *some* parts of the behavior of the Tree-sitter parser; like maybe just matching the same set of keywords. Sublime's grammars are definitely the closest in terms of functionality, because you can write an entire state machine by hand in those YAML files.

But I think that like @Arcanemagus said, there wouldn't be an exact translation; it would always be some kind of "best-effort" approximation.

I think it could be interesting, but not something that I would want to do as part of Tree-sitter. The grammars are machine-readable (via the generated `grammar.json` files), so someone could do it as an external tool. I'm going to close this out since it's not something we'd tackle as part of Tree-sitter itself, but thanks for the suggestion!

**Comment by Razzeee** [comment]
I'm not actually sure the tmLanguage in vscode will be mandatory going forward, as semantic tokens seem to land soonish.
https://code.visualstudio.com/updates/v1_42#_semantic-highlighting-for-typescript-javascript
