### ISSUE TITLE
Highlighter questions and usability problems

### ISSUE THREAD

**Issue by fcurts** [tree-sitter/tree-sitter#572]
While developing a highlighter for my tree-sitter grammar, I came across the following questions and usability problems. I'd appreciate any thoughts.

1. "Failed to load queries" error messages don't provide file path
    Instead of directory path and file number, they should provide file path and file number.
1. "Invalid node type" error messages don't always provide node name
    Sometimes I get "Invalid node type foo", and at other times just "Invalid node type".
1. Line numbers in error messages are wrong
    When I get "Query error on line x" for my _highlights.scm_, the correct line number is (x - 45). My impression is that _highlights.scm_, _locals.scm_, and _injections.scm_ are treated as a single file, which would also explain (1).
1. Provide config as CLI arguments
    Many (most?) usages of _tree-sitter-highlight_ will be scripted rather than interactive. In those cases, it would be much preferable to provide config as CLI arguments (_--parser \<dir>_, _--theme \<file>_, etc.) with sensible defaults (e.g., current working dir) rather than in _~/.tree-sitter/config.json_.
1. Are _@keyword_ patterns special?
The pattern `"false" @keyword` is accepted, but `"false" @constant.builtin` is rejected with "Query error on line x. Invalid node type false". Instead I have to use `(falseLiteral) @constant.builtin`. What's the explanation for this? (There is a grammar rule `falseLiteral: $ => "false"`.)
1. Are predicates only allowed at the outermost level?
    Predicates at deeper levels seem to cause "invalid syntax" errors.
1. Are there any themes available on GitHub or elsewhere?
    So far the only theme I found is that generated by _tree-sitter init-config_.
1. Same language for grammars and queries
    Are there any plans to support writing grammars and queries in the same language, rather than writing grammars in JS and queries in (something like) Scheme? Not critical, just a thought.

Tested with tree-sitter 0.16.5 (e259af6a4e9bdda3f762746af8f53109589e0fdc).

**Comment by maxbrunsfeld** [comment]
Thanks for taking the time to write this up.

> 1. "Failed to load queries" error messages don't provide file path
Instead of directory path and file number, they should provide file path and file number.

> 3. Line numbers in error messages are wrong
When I get "Query error on line x" for my highlights.scm, the correct line number is (x - 45). My impression is that highlights.scm, locals.scm, and injections.scm are treated as a single file, which would also explain (1).

Yes, queries are composed by simple source concatenation. So the core library is doing the right thing here, but the CLI should probably do some post-processing on the error message to determine and report the original file name.

> 2. "Invalid node type" error messages don't always provide node name
Sometimes I get "Invalid node type foo", and at other times just "Invalid node type".

I don't think I've seen this, and it definitely seems like a problem. Could you open an issue with a reproduction for it?

> 4. Provide config as CLI arguments
Many (most?) usages of tree-sitter-highlight will be scripted rather than interactive.

That's reasonable. I hadn't foreseen much use for the CLI outside of the development/testing workflows for parsers, but I'm glad to hear that you might find it useful in non-interactive contexts; I'm definitely open to adding those kinds of flags. Are you interested in opening a PR?

> 5. Are `@Keyword` patterns special?

No. There's a difference between `(foo)` and `"foo"` in a query though: the first one matches [*named  nodes*](https://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes), and the second one matches *anonymous* nodes. A given node type will only match one or the other, not both.

> 6. Are predicates only allowed at the outermost level?

Yes.  They are associated with an entire pattern (top-level S-expression), not an arbitrary node within a pattern.

> 7. Are there any themes available on GitHub or elsewhere?

Not that I know of. If you're interested in sharing any, or working on conversions to/from other formats, that would be cool.

> 8. Same language for grammars and queries
Are there any plans to support writing grammars and queries in the same language, rather than writing grammars in JS and queries in (something like) Scheme? 

No, I think they're solving different problems. The grammar language needs to be pretty powerful and it's helpful to rely on a well-known widely-distributed language like JavaScript, whereas the query language is intentionally very limited and specialized, and it is nice that it can be parsed and compiled in a few hundred lines of C code.

**Comment by fcurts** [comment]
Thanks for getting back to me!

> Yes, queries are composed by simple source concatenation. So the core library is doing the right thing here, but the CLI should probably do some post-processing on the error message to determine and report the original file name.

Most importantly, line numbers should be adjusted, especially for _highlights.scm_.

> There's a difference between (foo) and "foo" in a query though: the first one matches named nodes, and the second one matches anonymous nodes. A given node type will only match one or the other, not both.

Given the grammar rule `falseLiteral: $ => "false"`, does it matter whether to match `(falseLiteral)` or `"false"` for highlighting?
In any case, I don't understand why `"false" @keyword` is accepted but `"false" @constant.builtin` fails with "Invalid node type".

> I hadn't foreseen much use for the CLI outside of the development/testing workflows for parsers, but I'm glad to hear that you might find it useful in non-interactive contexts; I'm definitely open to adding those kinds of flags.

My current goal is to plug the highlighter into [Antora](https://antora.org)/Asciidoc, which are written in Node.js. Calling out to `tree-sitter highlight` seems more attractive than writing my own Rust driver. (If tree-sitter-highlight offered a Node API, that would be even better.)

**Comment by maxbrunsfeld** [comment]
> In any case, I don't understand why `"false" @keyword` is accepted but `"false" @constant.builtin` fails with "Invalid node type".

Yeah, that is very surprising to me. Could you post a reproducible langauge/query where that happens?

**Comment by maxbrunsfeld** [comment]
> does it matter whether to match (falseLiteral) or "false" for highlighting?

Yeah, it should be `(falseLiteral)`, not `"false"`. Unless the string "false" is also used elsewhere in the grammar. In that case, there will likely be nodes for both `(falseLiteral)` and `"false"`.

**Comment by maxbrunsfeld** [comment]
> Most importantly, line numbers should be adjusted, especially for highlights.scm.

This week and next I think I'm finally going to get around to working on this.

**Comment by maxbrunsfeld** [comment]
I believe this point is fixed in https://github.com/tree-sitter/tree-sitter/commit/518916f2211373658cf148c9618e588396bd0a12.

I think the last thing to address in this issue is point 4, about explicit CLI flags.

**Comment by fcurts** [comment]
Closing because largely answered/obsolete. I'm still very interested in a way to use the syntax highlighter that doesn't involve writing Rust code.
