### ISSUE TITLE
Unresolved conflict for symbol sequence even as interpretations have different precedence

### ISSUE THREAD

**Issue by jonhue** [tree-sitter/tree-sitter#580]
Hey, I am getting the following error when generating a parser:

```
Unresolved conflict for symbol sequence:

  _expression  '+'  _expression  •  '/'  …

Possible interpretations:

  1:  (infix_application  _expression  '+'  _expression)  •  '/'  …                  (precedence: 9, associativity: Left)   
  2:  _expression  '+'  (infix_application  _expression  •  '/'  _expression)        (precedence: 10, associativity: Left)  
  3:  _expression  '+'  (infix_application  _expression  •  _operator  _expression)  (precedence: 2, associativity: Left)   

Possible resolutions:

  1:  Add a conflict for these rules: `infix_application`
```

This made me curious why this is interpreted as a conflict in the first place when all possible interpretations have different precedence. Or phrased differently, why doesn't the parser use the interpretation with the highest precedence in this case? Is this intended? 🙂

**Comment by maxbrunsfeld** [comment]
Maybe the error message could be improved.

The issue is that the precedences are 'split'. Option 1 requires one action (reduce) because the rule is finished. Options 2 and 3 require the other action (shift) because the rule is *not* finished.

Which action should it choose? The first action, reduce, has precedence 9. The second action, shift, has precedence 2 *and* precedence 10.

**Comment by jonhue** [comment]
Ah, I see. That makes sense, thanks!
