### ISSUE TITLE
Generate Checking

### ISSUE THREAD

**Issue by jussij** [tree-sitter/tree-sitter#600]
This is just a question regarding the _tree-sitter generate_ process.

Would it be possible for that generate step to check for these two cases:

1. Defining the same rule twice.
2. Defining a rule that is never used.

In playing around with creating a grammar.js file from scratch I've notice I've made both of these *user errors*.

**Comment by maxbrunsfeld** [comment]
Defining the same rule twice is not easily detectable, since that is allowed in JavaScript (it just overrides the key). You could set up your own JavaScript linter for `grammar.js`, but I don't think I want Tree-sitter to be responsible for that.

I don't think I want to forbid unused rules, because sometimes that may happen intentionally if you extend a grammar (e.g. creating a C++ grammar based on a C grammar), and want to remove a rule.

**Comment by stephe-ada-guru** [comment]
Max Brunsfeld <notifications@github.com> writes:

> Defining the same rule twice is not easily detectable, since that is
> allowed in JavaScript (it just overrides the key). You could set up
> your own JavaScript linter for `grammar.js`, but I don't think I want
> Tree-sitter to be responsible for that.
>
> I don't think I want to forbid unused rules, because sometimes that
> may happen intentionally if you extend a grammar (e.g. creating a C++
> grammar based on a C grammar), and want to remove a rule.

Perhaps a warning for an unused rule, and a command line flag that
treats warnings as errors?

Then you'd need a way to suppress the warning for an intentional unused
rule.

-- 
-- Stephe
