### ISSUE TITLE
TS sometimes swallows conflicts and ignores priorites

### ISSUE THREAD

**Issue by Heimdell** [tree-sitter/tree-sitter#614]
## What happens

In the language I'm modelling, I have following rules:
```
    string: $ =>
      choice(
        $.singleString,
        $.interpolatedString,
      ),

    singleString: $ => /\"([^\\\"]|\\.)*\"/,

    interpolatedString: $ =>
      prec.left(1,
        seq(
    //      '#',
          $.interpolatedStart,
          sepBy($.interpolatedCenter, $._expr),
          $.interpolatedEnd,
        ),
      ),

    interpolatedStart:  $ => /\"([^\\\"\{]|\\.)*\{/,
    interpolatedEnd:    $ => /\}([^\\\"\{]|\\.)*\"/,
    interpolatedCenter: $ => /\}([^\\\"\{]|\\.)*\{/,
```
In this case, TS will parse `"hello {world}"` as `$.singleString`, despite `$.interpolatedString` having bigger priority.

I've tried to disable `$.singleString`, then it does parse it as `$.interpolatedString` w/o any issues.

Maybe that's because `$.simpleString` is a regex - but AFAIK regices and other rules are all melted down to one big one-character-level automata.

If I uncomment `#` at the start of the `$.interpolatedString` rule, TS _will_ accept it. However, in the language I'm currently modelling there can be a `#` operator. And yep, `x #"foo {bar}"` moves us to square one - its an application of operator `#` to `x` and a `$.simpleString`.

If I then remove `#` from list of operator symbols, all goes to normal.

## What I expect to happen instead

1) TS should report a conflict between `$.interpolatedString` and `$.simpleString`.
2) TS should *not* ignore higher precedence.
3) TS should report a conflict between `$.interpolatedString` and ~`$.opCall`~ whatever is an offender here.

Here is the full version of my grammar and exaple file to play with:
- [language.tar.gz](https://github.com/tree-sitter/tree-sitter/files/4606070/language.tar.gz)

**Comment by maxbrunsfeld** [comment]
The conflict that you're describing is happening at the token level (within the character-level automata, as you mentioned), as opposed to at the syntactic level. Since that type of conflict occurs constantly in programming languages, and is generally not accidental, Tree-sitter does not consider that to be an error, like it does for grammatical conflicts. Instead, it generally applies the 'longest-match' criteria at runtime.

You can override the longest-match criteria by applying a character-level precedence with `token(prec(1, /my-regex/))` (calling the `prec` function inside of a call to the `token` function). For more detailed information about the order of conflict-resolution criteria, see [the lexical conflict docs](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens).

Feel free to reopen in you're still having problems. There might be something that I'm missing.
