### ISSUE TITLE
Feature Request: Adding support for lisps.

### ISSUE THREAD

**Issue by kolharsam** [tree-sitter/tree-sitter#618]
I see that a number of languages are currently supported and that is lovely! But it would be nice if you'd add for certain popular lisps like `Clojure`, `Common Lisp` & `Scheme` to this extensive list.

I'd love to help build it for any of the languages mentioned above?

**Comment by maxbrunsfeld** [comment]
I am aware of [a Clojure grammar](https://github.com/oakmac/tree-sitter-clojure) that has been developed for a while.

@oakmac Nice work on `tree-sitter-clojure`. Would you say that it works well enough for us to recommend that people use it, by adding it to [the Tree-sitter docs](https://tree-sitter.github.io/tree-sitter/#available-parsers)? It looks pretty good to me, from an initial scan.

**Comment by kolharsam** [comment]
At a glance, I thought there are still somethings to be accounted for. Like `let` bindings (might be wrong about this) and some other forms are also present on the issues section. But yes, it does seem to cover for most cases. 👏(@oakmac)

It might probably help to look at the source of the `clojure/tools.reader` or an interpreter like [sci](https://github.com/borkdude/sci) and see what they are doing to optimize reading Clojure forms.

What do you think?

And what about support for other lisps I mentioned?

**Comment by maxbrunsfeld** [comment]
I don't personally have plans to develop grammars for those languages, but anyone can develop a grammar. If you're interested, check out [the docs](https://tree-sitter.github.io/tree-sitter/creating-parsers) or some of the existing grammars.

**Comment by oakmac** [comment]
> Would you say that it works well enough for us to recommend that people use it, by adding it to the Tree-sitter docs?

I believe so :)

There is also this [tree-sitter-clojure](https://github.com/sogaiu/tree-sitter-clojure) package from @sogaiu - I believe it may be more recent than my package. Probably worth checking out if you are curious about Clojure tree-sitter prior efforts :)

**Comment by sogaiu** [comment]
FWIW, there are also grammars in various forms for Carp, Fennel, and Janet.

@GrayJack made grammars for Carp and Janet.

I've made attempts at Clojure, Fennel, and Janet (though I recommend GrayJack's attempt here).

In general I struggled a lot to get the lisp-with-macros things to fit well with tree-sitter.

For example, I failed to figure out a way to unambiguously recognize  definitions.  With a macro system it is easy to have things that look like definitions but are not.  In clojure, there is `case`, but it can have pieces that look like `(def a 1)` as clauses which also look like defs.

Even if the language proper things could somehow be worked around, the macro system allows any developer to define constructs that would not be things one could distinguish from actual definitions from a tree-sitter grammar's perspective (at least as far I understand its capabilities currently).

For my clojure attempt, I have so far decided against trying to recognize definitions.

I encountered more issues and am happy to discuss, but let me stop here for the moment :)

**Comment by GrayJack** [comment]
Also note that [tree-sitter-carp](https://github.com/GrayJack/tree-sitter-carp) and [tree-sitter-janet](https://github.com/GrayJack/tree-sitter-janet), doesn't have very well developed highlights query (contributions are welcome :smile: ), so if you gonna use for highlight outside Atom, it's is non-existent or incomplete.

Add those are the next step, and I'm still trying to get a environment to work on that front

**Comment by kolharsam** [comment]
@sogaiu aren't macro's supported within rust and c too? I mean, I'd like to know how they are different from macros that are available within Clojure? 

And yes, you could shed more light on the issues that you faced.

@GrayJack, could you please let me know how I could perhaps help you?

**Comment by sogaiu** [comment]
@kolharsam I'm not too familiar with Rust macros, however, C macros and Lisp macros are significantly different IIUC.  Having said that, I suppose it's possible that in the context of tree-sitter, they are similar enough.  I'm not sure as I haven't worked with the C or Rust grammars.

On a side note, I think I heard @maxbrunsfeld mention that C-type of macros are handled not-so-perfectly, but "well-enough" in one of his nice talks (or may be it was in some written material?) -- I'm not sure which one it is was.  May be he can comment on this further or point out where he touches on this point.

To elaborate a bit on the macros and definitions issue in Lisps-with-Macros a bit, one can typically define a macro that has within it a form that is mean to eventually define some function that is yet-to-be-named.  That inner form is not a definition, but it can look like one.  I didn't succeed in expressing in tree-sitter a reliable way of making a suitable distinction -- that is, "not recognizing" these inner forms as definitions.

For the purposes of syntax-highlighting (or say some editor functionality that wants to enumerate function definitions for an outline view, for example), that doesn't work out so well in my experience if you want to have function definitions be highlighted in a specific fashion by relying on what tree-sitter tells you directly.

In the Janet grammar (at least the last I checked) there is a work-around for recognizing `set`.  It turns out that's a special form, but it also gets used in the PEG grammar support of the language meaning something completely different.  A developer is free to express a form like `(set ...)` in the context of macros to mean other things too...so this sort of thing doesn't make things easy.

May be one can say that context can really matter for lisps-with-macros?

The Clojure and Fennel tree-sitter grammars I worked on do about as minimal job as they can in recognizing basic constructs.  Fennel is a simpler language grammatically so there is less to look at.  It has:

* the atomic things like symbols, numbers, etc.
* compound things like lists and tables
* quoting and unquoting

The Clojure one is similar in having those types of things but more involved with additional things like:

* discard forms
* pervasive support for metadata
* tagged literals
* reader conditionals

Just getting these (and other) pieces to fit together was tricky.  Though may be someone else could do better :)

I tested the Clojure grammar against a significant quantity (over 100,000) of Clojure files fetched from https://clojars.org/ and the latter against as many Fennel repositories as I could find.

They both work pretty well as far as not erroneously recognizing things is concerned.  When I start to add definitions and higher level constructs, things don't go so well for recognition, but the grammar gets harder to keep working (as I'm sure other tree-sitter grammar writers will tell you that the more you add the harder it gets).

**Comment by GrayJack** [comment]
@kolharsam If you understand the highlight query of tree-sitter-highlighter, or you have more free time than I to jump into this to learn the highlight query properly, writing the highlight queries for those packages would be a great help.

**Comment by sogaiu** [comment]
BTW, if folks are interested in doing testing for their own Clojure grammar attempts, there is this tool that should work for files, directories, and jar files: https://github.com/sogaiu/a-tsclj-checker

The tool just checks for whether there was an error: https://github.com/sogaiu/a-tsclj-checker/blob/master/src/main.rs#L18

I recommend retrieving sample data from Clojars because it is close to an append-only store of information.  Clojars content arrives in the form of .jar files though so this tool can be helpful.
