### ISSUE TITLE
Thought on XDG convention

### ISSUE THREAD

**Issue by azzamsa** [tree-sitter/tree-sitter#628]
tree-sitter puts the config in `~/.tree-sitter/config.json`. Would it be better if fit in better with the [XDG conventions](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Supported)?

**Comment by dcreager** [comment]
I like this idea, and we can leave `~/.tree-sitter/config.json` as a legacy fallback location.

@maxbrunsfeld Is the config file ever needed by the C library, or is it only used by the Rust CLI tool?  If we need this from C, there is some code we could lift from [libcork](https://libcork.io/) that both defines the XDG locations and implements a "look for a file in this list of paths" search. [[docs](https://libcork.io/0.15.0/files.html#standard-paths)] [[code](https://github.com/dcreager/libcork/blob/master/src/libcork/posix/files.c#L764-L891)]

**Comment by dcreager** [comment]
(and if it's only needed from Rust there's the [xdg](https://docs.rs/xdg/) crate)

**Comment by patrickt** [comment]
I’m +1 on this too, viz. how Emacs looks in `.emacs.d` and `.config/emacs`.

**Comment by maxbrunsfeld** [comment]
Yeah, I'd be open to this. The config file is specific to the CLI, so there's not much cost to changing it.

**Comment by gwerbin** [comment]
+1 to these! To recap, the "XDG way" would be something like this (in Bash-like syntax):

Config file: `${XDG_CONFIG_HOME:-$HOME/.config}/tree-sitter/config.json`, using `~/.tree-sitter/config.json` if that doesn't exist.

Parsers: `${XDG_CONFIG_HOME:-$HOME/.local/share}/tree-sitter/parsers/*` as the first default in the config file, above the other ones that are already listed.

**Comment by Julian** [comment]
+1, but it's also nice to have an explicit environment variable (e.g. `TREE_SITTER_HOME`) to decide where the directory goes (if such an envvar existed someone who wanted this behavior could have had it already without waiting for specific XDG support)

**Comment by gwerbin** [comment]
> +1, but it's also nice to have an explicit environment variable (e.g. `TREE_SITTER_HOME`) to decide where the directory goes (if such an envvar existed someone who wanted this behavior could have had it already without waiting for specific XDG support)

Note that the idea of a single "HOME" directory is somewhat incompatible with the XDG base directory setup, because in the  XDG system you have *two* directories: one in `XDG_CONFIG_HOME` and the other in `XDG_DATA_HOME`.

A long time ago I implemented a patch for the Ruby Bundler tool that had some complicated fallback logic for this kind of thing: https://github.com/rubygems/bundler/pull/6024

I propose the following for Tree Sitter:

* If `TREE_SITTER_HOME` is set, look in `$TREE_SITTER_HOME/config.json` and `$TREE_SITTER_HOME/parsers/*`.
* If `TREE_SITTER_HOME` is not set, look for Tree Sitter config files in `$XDG_CONFIG_HOME/tree-sitter/config.json` and parsers in `$XDG_DATA_HOME/tree-sitter/parsers/*`.

**Comment by p13nty** [comment]
For anyone trying to move out `.tree-sitter` directory from `$HOME`:

It [turns out](https://github.com/tree-sitter/tree-sitter/blob/b5ec720696d329656ed1e472fb188e4df4a477a2/cli/src/config.rs#L21) tree-sitter cli supports `$TREE_SITTER_DIR`. 

Here is my config:
```bash
export TREE_SITTER_DIR="${XDG_CONFIG_HOME}/tree-sitter"
```

**Comment by ahlinc** [comment]
@maxbrunsfeld this issue was successfully resolved by awesome @dcreager rework of CLI with extraction of config loading logic to a separate crate. So this issue can be closed.
