### ISSUE TITLE
.captures method returns fewer results than .matches when query cursor has range restriction

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#634]
I'm using `.captures` with range restriction for syntax highlighting. Sometimes it doesn't return nodes that `.matches` would otherwise return. It works correctly if the query cursor is not restricted to a range.

![matches-vs-captures](https://user-images.githubusercontent.com/198359/83652103-6e4eb580-a5e4-11ea-9bab-0dcc99815c4f.png)

This is the JSON file: https://github.com/ubolonton/emacs-tree-sitter/blob/matches-vs-captures/lisp/test-files/matches-vs-captures.json#L57-L60.

This is the highlight query: https://github.com/ubolonton/emacs-tree-sitter/blob/matches-vs-captures/langs/queries/json/highlights.scm.

Here's the output of [the code that reproduces the issue](https://github.com/ubolonton/emacs-tree-sitter/blob/matches-vs-captures/src/matches_vs_captures.rs):
```
.matches
  501 . 509 : "fields"
  519 . 528 : "keyword"
  540 . 546 : "type"
  567 . 581 : "ignore_above"
  608 . 624 : "abc_def_ghk_04"
  632 . 638 : "type"
  652 . 660 : "fields"
  670 . 679 : "keyword"
  691 . 697 : "type"
  718 . 732 : "ignore_above"
  759 . 775 : "abc_def_ghk_05"
  783 . 789 : "type"
  803 . 811 : "fields"
  821 . 830 : "keyword"
  842 . 848 : "type"
  869 . 883 : "ignore_above"
  910 . 926 : "abc_def_ghk_06"
  934 . 940 : "type"
  954 . 962 : "fields"
  972 . 981 : "keyword"
  993 . 999 : "type"
.captures
  501 . 509 : "fields"
  519 . 528 : "keyword"
  540 . 546 : "type"
  567 . 581 : "ignore_above"
  608 . 624 : "abc_def_ghk_04"
  632 . 638 : "type"
  652 . 660 : "fields"
  670 . 679 : "keyword"
  691 . 697 : "type"
  718 . 732 : "ignore_above"
  759 . 775 : "abc_def_ghk_05"
  783 . 789 : "type"
  803 . 811 : "fields"
  821 . 830 : "keyword"
  842 . 848 : "type"
  869 . 883 : "ignore_above"
  910 . 926 : "abc_def_ghk_06"
```

**Comment by maxbrunsfeld** [comment]
Working on this, but it is not a trivial change.

For context, in order for the `captures()` method to return the captures in order, it must internally buffer some matches instead of returning them immediately. In order to maintain stable performance, there is a hard limit on the number of buffered matches that are allowed.

Currently, in order to process a pattern like this:

```clj
(object
  "{" @foo
  (_)
  "}" @bar)
```

we need to avoid returning the `{` capture until we can verify that the match is complete by seeing  the `}` node. In the meantime, there may be many other captures from other patterns *inside* the object literal. But in order to preserve the ordering, we cannot return those captures yet.

The solution is going to require adding a new internal calculation when we construct a `TSQuery`, which determines whether certain parts of a pattern are "inevitable". For example, in this case, as soon as we see an `object` node with at least one key-value pair, we can tell that ☝️ this pattern is going to match; there's no need to wait until we have seen *all* of the child nodes. This would allow us to return the `{` capture *before* seeing the `}` capture, avoiding the need to buffer all of the object's contents internally.

I have partly planned out how to implement this. I think that once complete, it will mean that it takes slightly longer to construct a `TSQuery` instance, but it will make the queries run *faster*, and it will prevent this type of problem from happening in 99% of cases.

**Comment by maxbrunsfeld** [comment]
Regarding https://github.com/tree-sitter/tree-sitter-typescript/issues/79, there is a similar problem with our handling of this pattern:

```clj
(jsx_opening_element
 "<" @operator
 ">" @operator)
```

We must buffer the `<` capture (and any subsequent captures) until seeing the `>` token.

This will similarly be fixed by calculating that the `>` is *always* part of a `jsx_opening_element`.

**Comment by maxbrunsfeld** [comment]
Ok, closing this one out because the fix is implemented on master. But note that the fix won't take effect until we regenerate the parsers with the newest Tree-sitter CLI. I might hold off on this for a few days at least, in case we discover any bugs or limitations in the new data structures added to the generated parsers in #644. I'd like to avoid doing more than *one* parser ABI version bump.
