### ISSUE TITLE
How is total dynamic precedence calculated?

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#678]
I'm working on [improving the Scala grammar](https://github.com/tree-sitter/tree-sitter-scala/compare/master...ubolonton:69c2c60#diff-95fc33185b7215010b60f43469000a7aR423). I use dynamic precedence to resolve the conflicts between `tuple_type` and `parameter_types`. It works, and I expect a parse error when omitting `prec.dynamic`. However, the parser still chooses a branch, and gives an undesirable result sometimes. How does it make that decision?

This is the test case:

```scala
object Main {
  type A = (B, C) => D

  type A = (B, C) => (D, E)
}
```

With `prec.dynamic`:

```clojure
(compilation_unit
 (object_definition
  (identifier)
  (template_body
   (type_definition
    (type_identifier)
    (function_type (parameter_types (type_identifier) (type_identifier))
                   (type_identifier)))
   (type_definition
    (type_identifier)
    (function_type (parameter_types (type_identifier) (type_identifier))
                   (tuple_type (type_identifier) (type_identifier)))))))
```

Without `prec.dynamic`:

```clojure
(compilation_unit
 (object_definition
  (identifier)
  (template_body
   (type_definition
    (type_identifier)
    (function_type (parameter_types (type_identifier) (type_identifier))
                   (type_identifier)))
   (type_definition
    (type_identifier)
    (infix_type (tuple_type (type_identifier) (type_identifier))
                (operator_identifier)
                (tuple_type (type_identifier) (type_identifier)))))))
```

**Comment by maxbrunsfeld** [comment]
First, I just want to make sure I understand the current situation. Is this right?

* When `prec.dynamic` is used, everything works as expected. A type of the form `(T, U) => V` is always interpreted as a `function_type`, rather than an `infix_type`.
* Without `prec.dynamic`, things works *inconsistently*. Types of this form are *sometimes* parsed as `function_type`, and sometimes as `infix_type`.

---

As for your actual questions:

> How is total dynamic precedence calculated?

Dynamic precedence is a signed integer that's associated with every syntax node at parse time. A syntax node's dynamic precedence is the **sum** of:
* The greatest (absolute-valued) `prec.dynamic` value in the grammar rule that matched the node
* The dynamic precedence values of each of the node's children

In this way, dynamic precedence values propagate up the tree.

> the parser still chooses a branch, and gives an undesirable result sometimes. How does it make that decision?

Tree-sitter only uses dynamic precedence to resolve true *ambiguities* - cases when there are multiple valid sequences of subtrees that match a span of code, and each sequence of subtrees brings the parser to the same parse state. So in your case, it would happen at the end of parsing the containing `_type`, there are two valid subtrees.

When multiple matching subtrees have the **same** dynamic precedence (e.g. zero), then Tree-sitter needs to pick one arbitrarily. There aren't really meant to be any guarantees about which one it will choose. Currently, the procedure is to perform a depth first traversal of both trees, find the first differing node type, and pick the one whose differing node type occurred *earlier* in the grammar. But this isn't really meant to be relied on.

---

Some of this should probably go into the parser-creation documentation. So far I've found that section a bit hard to write, because it's a somewhat complex thing to explain.

**Comment by maxbrunsfeld** [comment]
By the way, if you run `tree-sitter parse test.scala -D`, Tree-sitter will create and open a "graphical log file" (rendered via graphviz), which illustrates the parsing process step-by-step. This might be helpful for tracking the decisions that the parser makes.

**Comment by ubolonton** [comment]
> First, I just want to make sure I understand the current situation. Is this right?
>
>     * When `prec.dynamic` is used, everything works as expected. A type of the form `(T, U) => V` is always interpreted as a `function_type`, rather than an `infix_type`.
>
>     * Without `prec.dynamic`, things works _inconsistently_. Types of this form are _sometimes_ parsed as `function_type`, and sometimes as `infix_type`.
>

Yeah.

> Currently, the procedure is to perform a depth first traversal of both trees, find the first differing node type, and pick the one whose differing node type occurred _earlier_ in the grammar. But this isn't really meant to be relied on.
>

Thanks, this clears up my confusion. I thought there was hidden dynamic precedence somewhere.

> By the way, if you run `tree-sitter parse test.scala -D`, Tree-sitter will create and open a "graphical log file" (rendered via graphviz), which illustrates the parsing process step-by-step. This might be helpful for tracking the decisions that the parser makes.
>

This is pretty nice!
