### ISSUE TITLE
Program for viewing debug graph.

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#686]
Right now I use web browser to open the generated debug graph (the log.html file). However, I have realized that I am not able to zoom the graph. No matter what is the current zoom value, the graph size always remains the same. I have tried with chromium and Firefox. What program do you use to view the debug graph?

**Comment by maxbrunsfeld** [comment]
I just use chrome. I think the behavior you're seeing is caused by this CSS: https://github.com/tree-sitter/tree-sitter/blob/32bb2e5add854bad243030adb9d9452104d884a4/cli/src/util.rs#L14

I find that full-width graph display useful, because I don't want to zoom, I just want to scroll up and down through a consistently-sized sequence of graphs. But maybe you'd want to remove that styling.
