### ISSUE TITLE
presence of conflict causes bogus lexer error

### ISSUE THREAD

**Issue by stephe-ada-guru** [tree-sitter/tree-sitter#690]
In the attached, the directories debug_good and debug_bad contain grammars that differ only in the presence of the generic_instantiation rule, which causes a conflict.

debug_bad/grammar.parse shows lexer errors. The cause seems to be that the lexer is in the wrong state after parsing 'is'; the lexer error recovery then puts it in the correct state.

[debug.tar.gz](https://github.com/tree-sitter/tree-sitter/files/4913984/debug.tar.gz)

**Comment by maxbrunsfeld** [comment]
I can't reproduce this. With `tree-sitter-cli`, in the `debug_bad` directory, I get this output:

```sh
tree-sitter generate
tree-sitter parse ../debug.input 
```

```
(compilation_unit_list [0, 0] - [5, 0]
  (compilation_unit [0, 0] - [2, 4]
    (subprogram_body [0, 0] - [2, 4]
      (subprogram_specification [0, 0] - [0, 17]
        (procedure_specification [0, 0] - [0, 17]
          (name [0, 10] - [0, 17]
            (IDENTIFIER [0, 10] - [0, 17]))))
      (declarative_part [1, 3] - [1, 15]
        (declaration [1, 3] - [1, 15]
          (object_declaration [1, 3] - [1, 15]
            (IDENTIFIER [1, 3] - [1, 4])
            (IDENTIFIER [1, 7] - [1, 14])))))))
```

**Comment by stephe-ada-guru** [comment]
Max Brunsfeld <notifications@github.com> writes:

> I can't reproduce this. With `tree-sitter-cli`, in the `debug_bad` directory, I get this output:
>
> ```sh
> tree-sitter generate
> tree-sitter parse ../debug.input 
> ```
>
> ```
> (compilation_unit_list [0, 0] - [5, 0]
>   (compilation_unit [0, 0] - [2, 4]
>     (subprogram_body [0, 0] - [2, 4]
>       (subprogram_specification [0, 0] - [0, 17]
>         (procedure_specification [0, 0] - [0, 17]
>           (name [0, 10] - [0, 17]
>             (IDENTIFIER [0, 10] - [0, 17]))))
>       (declarative_part [1, 3] - [1, 15]
>         (declaration [1, 3] - [1, 15]
>           (object_declaration [1, 3] - [1, 15]
>             (IDENTIFIER [1, 3] - [1, 4])
>             (IDENTIFIER [1, 7] - [1, 14])))))))
> ```

Sorry, I should have been clearer.

run 'tree-sitter parse -d'; you'll get:

lexed_lookahead sym:ERROR, size:5, character:'A'
detect_error

etc. No errors show in the syntax table. The file grammar.parse in each
directory is the log of my run with -d.

I'm using a checkout from github main branch, eariler today, rev 0c2dc4c1e9ff86b2adf15968f082792b61263274

-- 
-- Stephe

**Comment by maxbrunsfeld** [comment]
Yeah, I think you're seeing the expected behavior. A conflict occurs, which requires the parser to attempt two possible parses. On one of the branches, an error occurs (there is no `new` keyword, but the `A` identifier instead), so the parser aborts that branch, and pursues the other one (creating a `procedure_specification`).

**Comment by stephe-ada-guru** [comment]
Ah, that makes sense. My wisitoken parser does the same thing, but it's reported by the parser, not the lexer. I gather the tree-sitter lexer is made aware of the parser state; that's what lex-modes is for? Is there a document on the lexer/parser integration?

Also, is there a tree-sitter API function to report all the parser errors? or at least the ones that were encountered and corrected by the successful parse. At the very least, I'd like to have my test executable return an error status if the parse fails.

**Comment by maxbrunsfeld** [comment]
> I gather the tree-sitter lexer is made aware of the parser state; that's what lex-modes is for?

Yeah, exactly. The lexer tries to only return tokens that would be valid in the current parse state.

> Is there a document on the lexer/parser integration?

There isn't. I'd like to write something up about it, but it's unclear to me where it should go. I try to avoid having the docs be overwhelming.

**Comment by maxbrunsfeld** [comment]
> Also, is there a tree-sitter API function to report all the parser errors? or at least the ones that were encountered and corrected by the successful parse. At the very least, I'd like to have my test executable return an error status if the parse fails.

There isn't anything perfectly suited to this.

You can check if a syntax node contains any errors using [`ts_node_has_error`](https://github.com/tree-sitter/tree-sitter/blob/0c2dc4c1e9ff86b2adf15968f082792b61263274/lib/include/tree_sitter/api.h#L473-L476), and you can find those errors either using a [Tree Query](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) for `(ERROR)` or by manually walking the tree with a `TreeCursor` and checking each node's type (looking for `ERROR`), and also checking `ts_node_is_missing`.

There is an issue (https://github.com/tree-sitter/tree-sitter/issues/255) for adding APIs suited toward user-facing error messages. It's something I'd love to see added, but don't have a lot of time to work on because it isn't needed for any of GitHub's use cases so far.
