### ISSUE TITLE
Parser performance in context of rules simply pointing to other rules

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#694]
Right now I have some rules that add nothing new, they just point to other rules. Example:
```javascript
    _signal_mode_indication: $ => $._mode_indication,

    signal_name: $ => $._name,

    variable_name: $ => $._name,

    file_name: $ => $._name,
```
The advantage of such approach is better reflection of the standard. However, I wonder if this has any impact on the generated parser performance? I have realized, that it has impact on the generation time, however this one is negligible.

**Comment by maxbrunsfeld** [comment]
It does increase the size of the binary and it has a runtime cost, because more syntax nodes need to be constructed.

If you want to differentiate between different kinds of names, a common approach is to do use `alias` for that:

```js
alias($.name, $.variable_name)
```

That will have a smaller runtime cost, and it will *probably* decrease the size of the generated parser as well.
