### ISSUE TITLE
console.log() in module causes some cryptic error

### ISSUE THREAD

**Issue by Xeyler** [tree-sitter/tree-sitter#703]
Hey, folks! First of all, I apologize for my ignorance... My guess is that this bug is happening because I'm a NodeJS noob. This is literally my first NodeJS project(and I've loved it so far!).

Anyways, the deets: I'm creating a tree-sitter for this language I use at work. We have a file which contains all the valid "instructions" and their arguments(very similar to functions). In my grammar.js, I've described the language very generally and I've required a module which parses this file containing all the instructions.

In the required module, I've been trying to use console.log() to debug and send some useful messages to the user as they're compiling the tree-sitter grammar, but console.log() appears to break the program.

Here's the output with console.log() in the required module:
`expected value at line 1 column 1`

And the output when I instead use console.error():
`Using CRBasic DEF file at /home/xeyler/crbasic-defs/CR6.DEF`

Naturally, the console.error() output is the output I'd expect when using console.log().

Any clue what could be causing this? Thanks!

**Comment by antoniodejesusochoasolano** [comment]
I ran into the same problem. I switched to using `console.warn` for debugging and didn't run into errors. I assumed that Tree-sitter was probably parsing the output from grammar.js and custom `console.log` messages were messing it up.

I don't know the Tree-sitter internals but hopefully no one minds me taking a crack at the answer 😄. 

It looks like part of the call stack that processes our grammar looks like this:

1. We export our grammar in grammar.js: `module.exports = grammar({name: "mylang", ...});`
2. `cli/src/generate/dsl.js` converts our grammar object into JSON and [prints it to stdout](https://github.com/tree-sitter/tree-sitter/blob/af655547e5817efbdf350935555b4aaf2642c618/cli/src/generate/dsl.js#L397-L398).
3. `load_js_grammar_file` [reads](https://github.com/tree-sitter/tree-sitter/blob/af655547e5817efbdf350935555b4aaf2642c618/cli/src/generate/mod.rs#L209-L216) and [returns](https://github.com/tree-sitter/tree-sitter/blob/af655547e5817efbdf350935555b4aaf2642c618/cli/src/generate/mod.rs#L223-L225) stdout from `cli/src/generate/dsl.js`.
4. `parse_grammar` [parses the output](https://github.com/tree-sitter/tree-sitter/blob/af655547e5817efbdf350935555b4aaf2642c618/cli/src/generate/mod.rs#L64-L77) of `load_js_grammar_file` (via `load_grammar_file`) and it looks like `parse_grammar` expects a JSON string based on the [variable name](https://github.com/tree-sitter/tree-sitter/blob/af655547e5817efbdf350935555b4aaf2642c618/cli/src/generate/mod.rs#L77) (`grammar_json`) and [parameter type](https://github.com/tree-sitter/tree-sitter/blob/af655547e5817efbdf350935555b4aaf2642c618/cli/src/generate/parse_grammar.rs#L78) (`&str`).

💡 I think this means calls to `console.log` from `dsl.js` or `grammar.js` will passed to and break `parse_grammar` because we're no longer passing a valid JSON string.

```
// grammar.js

console.log("Hello this is a debug message!");
module.exports = grammar({name: "mylang", ...});

// mod.rs (pseudo code)

let grammar_json = exec("dsl.js").stdout;

// 💀 Eeek! This doesn't look like JSON! 
parse_grammar(grammar_json: "
    Hello this is a debug message!
    {
        "name": "mylang"
    }
");
```

The Tree-sitter maintainers know best, but maybe disabling `console.log` while we import `grammar.js` and enabling it after would help grammar writers out? Something like:

```
const log = console.log, info = console.info;
console.log = console.info = () => throw new Error("Very good error message");

const result = require(process.env.TREE_SITTER_GRAMMAR_PATH);

console.log = log, console.info = info;

console.log(JSON.stringify(result, null, 2));
```

**Comment by Xeyler** [comment]
Looking at the call stack you traced, it's obvious now that you're right: We can't use `console.log()` because we're already depending on stdout to pass the grammar json.

Frankly, I'm surprised that this issue hasn't been reported before. The ["creating parsers"](https://tree-sitter.github.io/tree-sitter/creating-parsers) section of the documentation makes no note of `console.log()` causing errors. In light of this, we can choose one of several options to overcome the issue:

- Make `console.log()` unavailable from inside the grammar module and perhaps document this behavior (though throwing an error with a descriptive message would probably be just as good as documenting it).
- Write the grammar json result to a file from within `dsl.js`, then read that file from within `mod.rs`'s load_js_grammar_file function, bypassing the need for piping between processes and allowing `grammar.js` to use stdout for whatever.
- Ignore the issue and make a note about not calling `console.log()` in the documentation somewhere.

I'd be excited to set up a local development environment and submit a pull request for this one! My preference would be to implement a solution that would trigger a descriptive error when calling `console.log()`, but do the maintainers have a different preference?

Thanks, you're all awesome! And that was one impressive response, Antonio!

**Comment by winston0410** [comment]
Just bumped into the same error. I guess this need to be documented.
