### ISSUE TITLE
TypeScript .d.ts file generator

### ISSUE THREAD

**Issue by asgerf** [tree-sitter/tree-sitter#707]
Hi 👋 

I wrote a mapping from `node-types.json` to TypeScript `.d.ts` files here https://github.com/asgerf/dts-tree-sitter.

I was wondering if you'd want to have a tool like that in the tree-sitter org, or as part of the `node-tree-sitter` bindings, maybe?

**Comment by jmbockhorst** [comment]
This tool is really helpful and I agree that it should be a part of tree-sitter, as it makes working with TypeScript much better.

**Comment by DanielFlaum** [comment]
I would like this badly enough to investigate building and contributing it. But most of my experience is with writing my own code, not getting familiar with other people's.

If people are willing to answer some dumb questions from me I might be able to pull it off.

I guess my first questions are these:

* Would we want declaration files to be generated by default as part of the CLI's `generate` command, generated only when a flag is added to the `generate` command (i.e. `tree-sitter generate --ts-declarations`), or generated with a separate command (i.e. `tree-sitter build-ts`?
* If this generation takes places as part of the `generate` command, then I'd be doing the meat of my work in `tree-sitter/cli/src/generate`, right? (I ask because, again, I have little experience reading codebases I didn't write, and I don't have confidence yet in my ability to find the right place to start.)

Thanks!

**Comment by dundargoc** [comment]
We accept contributions, PRs welcome.

No maintainer has indicated they actually want this (or not want this), so can't really comment on that. The best way to get a reaction is to usually threaten them with a PR.
