### ISSUE TITLE
How to extract [Python, Java, Go, …] methods/function metadata?

### ISSUE THREAD

**Issue by Ceceu** [tree-sitter/tree-sitter#725]
Using the following code snippet as an example:

```python
def sum(a, b):
    """ Calculates and returns the sum of two integers."""
        c = a + b
        
        # result 
        return c
```

how could someone extract the following metadata:

```python
metadata = {
            "identifier": "sum",
            "parameters": "['a', 'b']",
            "return_statement": "c",
            "docstring": "Calculates and returns the sum of two integers"
            "code_only": "def sum(a, b):\n    c = a + b\n    return c"
           }
```

**Comment by patrickt** [comment]
The recommended way to do this is to use the [node child access](https://tree-sitter.github.io/tree-sitter/using-parsers#node-field-names) API, using the field names defined [in the grammar](https://github.com/tree-sitter/tree-sitter-python/blob/master/grammar.js#L310), perhaps in combination with the [cursor API](https://tree-sitter.github.io/tree-sitter/using-parsers#walking-trees-with-tree-cursors). You may also be able to use the [query API](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries). Your needed code would therefore be a combination of whatever JSON library you’re using and access to the fields named `name`, `parameters`, etc.

Since we have an API for this, I’m going to close this, but feel free to leave comments in the thread if you have any questions.

**Comment by Ceceu** [comment]
I am using [py-tree-sitter](https://pypi.org/project/tree-sitter/) to extract metadata from code in different languages (Python, Java, Go, etc.) and I will try to use the directions you have pointed out. Thank you very much.

**Comment by patrickt** [comment]
Great! Looks like the APIs you’ll need are instance variables in the `Node` type, like `children` and `type`.

**Comment by Ceceu** [comment]
Is there any documentation explaining how these methods work as well as listing the other methods available?
Some examples would be extremely useful as well.

**Comment by patrickt** [comment]
There’s pretty extensive documentation on the site: https://tree-sitter.github.io/tree-sitter/using-parsers#node-field-names
Also check the test suite: https://github.com/tree-sitter/py-tree-sitter/blob/master/tests/test_tree_sitter.py

**Comment by sogaiu** [comment]
@Ceceu Coincidentally, I started using py-tree-sitter to use hypothesis to test a grammar.  Perhaps you'll find some of this sample code to be of some use: https://gist.github.com/sogaiu/45684afcbc37818b4651bcc550616ee9

**Comment by Ceceu** [comment]
Thank you very much. This really contributes to what I am developing.

**Comment by viniciusarruda** [comment]
Hi @celsofransa, how did you solve it? Could you please share your solution?
