### ISSUE TITLE
npm distributions

### ISSUE THREAD

**Issue by char0n** [tree-sitter/tree-sitter#740]
This is more a question than anything. 

I can see that last published npm version of tree-sitter is [tree-sitter@0.16.2](https://www.npmjs.com/package/tree-sitter/v/0.16.2). After that releases stopped. Tree-sitter [github repo](https://github.com/tree-sitter/tree-sitter/releases) is currently at [v0.16.9](https://github.com/tree-sitter/tree-sitter/releases/tag/0.16.9).

[tree-sitter-cli](https://www.npmjs.com/package/tree-sitter-cli/v/0.16.9) seems to be reflecting the tree-sitter github releases and is currently at [0.16.9](https://www.npmjs.com/package/tree-sitter-cli/v/0.16.9) version which is the same as last GitHub release. 

[web-tree-sitter](https://www.npmjs.com/package/web-tree-sitter) is at version [0.16.4](https://www.npmjs.com/package/web-tree-sitter/v/0.16.4).

I suppose that those npm package versions reflect the [Github releases](https://github.com/tree-sitter/tree-sitter/releases) of tree-sitter and ideally their version should be same for all the packages when used inside one project. Would it be possibly to release latest version of `tree-sitter`, `tree-sitter-cli` and `web-tree-sitter` packages?

Thanks you

**Comment by maxbrunsfeld** [comment]
We already to publish everything to npm. There are three modules on npm:
* `tree-sitter-cli` - the command line tool, implemented in the `cli` directory of this repo
* `web-tree-sitter` - the WASM binding - implemented in the `lib/binding_web` directory of this repo
* `tree-sitter` - The original Node.js binding using native extension - implemented in the `node-tree-sitter` repo

They generally are going to have different versions, because they are different code. But we do generally keep their *minor* version numbers (and the minor version numbers of the generated parsers) in sync.

**Comment by char0n** [comment]
@maxbrunsfeld thanks for releasing npm packages and additional explanation about them.
