### ISSUE TITLE
RGB color on tree-sitter highlight

### ISSUE THREAD

**Issue by alemuller** [tree-sitter/tree-sitter#758]
```json
{
  "parser-directories": [
    "/home/alemuller/git"
  ],
  "theme": {
      "number": "#FF0000"
  }
}
```

When calling `tree-sitter highlight file.ext` the following error is produced:
```
thread 'main' panicked at 'Unsupported color type', cli/src/highlight.rs:271:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
When color is a number or an ANSI name it works.

**Comment by lazytype** [comment]
@maxbrunsfeld are you accepting PRs? seems like this could be a fairly focused change in `cli/src/highlight.rs`

**Comment by maxbrunsfeld** [comment]
Right now, the RGB ones only work with ‘—html’. Do many terminals support RGB colors? I’m not familiar with that. But if there’s a way that makes sense to render it to the terminal, and isn’t too complicated, I’m open to it.

**Comment by lazytype** [comment]
I looked at what some terminal coloring crates do to support RGB and it seems like they just approximate it. Here's a crate https://crates.io/crates/ansi_colours, and here's one implementation I found that's only a few lines long https://github.com/ChrisB9/terminal_color_builder/blob/main/src/color.rs#L146-L152

**Comment by maxbrunsfeld** [comment]
> only a few lines long

oh yeah, that level of complexity is totally fine by me 👍 . That seems reasonable for this purpose.

**Comment by ahlinc** [comment]
@maxbrunsfeld As I know last several years there happen wide adoption of 24bit true colors in plenty of terminals.
There is a gist page https://gist.github.com/XVilka/8346728 were the adoption progress is tracked.
On the gist there is a description how to detect truecolors support in terminals and in case of no support a fallback to 256 ansi_colors through mentioned crate would be a good option.
It seems there is better crate https://crates.io/crates/colored that have 24bit true colors support.

**Comment by lazytype** [comment]
It seems like the `colored` crate does not yet try to approximate the closest color if true colors is not supported. There's an open PR for this here https://github.com/mackwic/colored/pull/90.

But it also turns out that the crate that tree-sitter is currently using, `ansi_term` also supports true colors https://github.com/ogham/rust-ansi-term/pull/13/files, I modified my local clone of tree-sitter to use it and verified that it works in iterm2. In the default macOS Terminal app, the color will just be rendered as a gray. So I could send a PR for the local changes I have or also add support for approximating the color in ANSI.
