### ISSUE TITLE
Allow matching on node type with out specifing the complete subtree

### ISSUE THREAD

**Issue by theHamsta** [tree-sitter/tree-sitter#759]
Currently, you can match complete subtrees using the alternate syntax `[ ]` e.g.

```
[(parameter_declaration
        (identifier))
(binary_expression
        (identifier))]
```
but it's not possible to specify multiple node types as parents for a common subtree (except supertype)
```scheme
([parameter_declaration binary_expression]
        (identifier)) ; here we have the ambiguity whether we have two matches (one alternative, one normal) 
```
or
```scheme

[parameter_declaration binary_expression
        (identifier)] ; there is an ambiguity whether (identifier) is a child or one of the alternatives
```

which would be interpreted as alternate expression with children. There is currently no good way to express this with the query syntax.

**Comment by maxbrunsfeld** [comment]
Yeah, I think that I'd like to avoid making the syntax too complicated, so I would probably suggest just writing out the complete subtrees. There's a bit of duplication, but I think that's ok; this is a simple language.

If we did add a feature for this, we couldn't use the `[` syntax for this (as you rightly point out) because this means something pretty different, and it would introduce ambiguity with the other valid uses of `(` and `[`.
