### ISSUE TITLE
Docs explaining significance/mechanics of parser state

### ISSUE THREAD

**Issue by smackesey** [tree-sitter/tree-sitter#769]
This post is really more of a question, but since I don't see it explained in the docs, I also think it merits an issue request for documentation.

I'm writing a parser that uses an external scanner. I just debugged a situation in which I seemed to be experiencing non-deterministic parsing. That is, parsing the same string would sometimes work and sometimes produce an error. I was able to eliminate this problem by always using a fresh parser object (if it matters, I'm using `node-tree-sitter`). This tells me that the operative factor was something in the state of the `Parser`.

However, I'm having a hard time trying to understand the problem. The docs don't provide much information.

The `Using Parsers` section just says: "A TSParser is a stateful object that can be assigned a TSLanguage and used to produce a TSTree based on some source code." The nature of this state is not elaborated on.

The `Creating Parsers` section is more helpful. It describes the functions you must write for your external scanner, but it says that the buffer "will ultimately be stored in the syntax tree". I read this as the parser state defined in serialize/deserialize only being important for applying edits to the same tree. But my experience above suggests this is not the case-- that is, the parser state somehow affects a fresh parse of a string with no existing tree.

So a  few questions that I think the docs could benefit from answering (and that I would appreciate some help on here):

- When exactly are `serialize`/`deserialize` called? The docs say that `serialize` is called after each token is resolved. Is `deserialize` called *before* attempting to resolve each token? And, if the serialized data is stored in a syntax tree, then what happens when you call `parse` on two different strings (there being no defined tree for the second string).
- Is there best practice for when to create a new Parser object and when to reuse an existing one? Are there significant performance implications to creating lots of Parser objects? My application is a language server and, as a result of my debug session, I am now creating a different parser object for each managed document. But I don't know if that is really necessary.

**Comment by maxbrunsfeld** [comment]
> Is there best practice for when to create a new Parser object and when to reuse an existing one? 

You shouldn't ever need to create a new `Parser` object, unless you need to perform more than one parse at the same time, using multiple threads. The parser does carry some state that you explicitly set on it, via methods like like `setLanguage`, `setTimeoutMicros`, `setLogger`, but that is it. Also notably, the parser does store an instance of your external scanner.

> When exactly are serialize/deserialize called? The docs say that serialize is called after each token is resolved. Is `deserialize` called before attempting to resolve each token?

Yeah, it is. And, if the serialized data is stored in a syntax tree, then what happens when you call parse on two different strings (there being no defined tree for the second string).

In all cases, the `deserialize` method is called with the state that was serialized after the previous external token in the same parse.

It sounds like your `serialize`  and `deserialize` methods may not be correctly encoding and recreating your scanner's state?
