### ISSUE TITLE
/usr/lib64/libtree-sitter.so.0.0 calls exit@GLIBC_2.2.5

### ISSUE THREAD

**Issue by mcepl** [tree-sitter/tree-sitter#805]
rpmlint complaints:
```
[  116s] libtree-sitter0.x86_64: W: shared-lib-calls-exit /usr/lib64/libtree-sitter.so.0.0 exit@GLIBC_2.2.5
[  116s] This library package calls exit() or _exit(), probably in a non-fork()
[  116s] context. Doing so from a library is strongly discouraged - when a library
[  116s] function calls exit(), it prevents the calling program from handling the
[  116s] error, reporting it to the user, closing files properly, and cleaning up any
[  116s] state that the program has. It is preferred for the library to return an
[  116s] actual error code and let the calling program decide how to handle the
[  116s] situation.
```

**Comment by maxbrunsfeld** [comment]
Currently, `exit` is called when a memory allocation routine like `malloc` fails. AFAIK, this error is already not possible to handle gracefully on Linux with the default OS configuration, because of memory overcommit. The library used to try to handle malloc failure, but I actually think that the amount of complexity this added make the library more secure, not less. I don't foresee changing the current behavior of aborting on allocation failure.

Do you have any suggestion of how to improve this?

**Comment by dcreager** [comment]
If we switch this to use `abort(3)` instead of `exit(3)` will that satisfy rpmlint?  I think `abort` is the preferred way to kill the process in these cases anyway.  That's what I do [in libcork](https://github.com/dcreager/libcork/blob/a89596ce224438c136ef0336a81c51262cad9cd3/src/libcork/core/allocator.c#L42-L50).

**Comment by mcepl** [comment]
1. Yes, it would probably silence rpmlint.

2. Why not to do what’s suggest in the error message: just to return with error?

**Comment by maxbrunsfeld** [comment]
Oh, nice. Let’s switch it to abort. I’m Not sure why it’s using exit now.

@mcepl As I said, it’s pretty complex to check every memory allocation in the library for failure and propagate the error correctly back to the public API, while avoiding memory leaks or invariant breakage. Tree-sitter used to try to do it, but it is not a good practice for this kind of library IMO.
