### ISSUE TITLE
Consider disallowing rules with identical names

### ISSUE THREAD

**Issue by ammkrn** [tree-sitter/tree-sitter#818]
The tree-sitter-cli currently allows users to create multiple rules that have the exact same name, and it seems to silently choose the one that appears last. For example, this grammar generates a parser which recognizes alpha as [a-z][0-9]:

```
  rules: {
    source_file: $ => repeat($.string),

    alpha: $ => choice(
      /[a-z]/,
      /[A-Z]/,
    ),

    alpha: $ => choice(
      /[a-z]/,
      /[0-9]/,
    ),

    string: $ => prec.left(1, repeat1($.alpha)),
  }
```

I think a name collision like this is almost always going to be indicative of user error, so it might be preferable to make this situation a hard error.

**Comment by ammkrn** [comment]
Whoops, this is a duplicate of #689 (why do I always find the duplicate issues when its too late?)

Did #658 open up any options for alleviating this?

**Comment by maxbrunsfeld** [comment]
As mentioned in #689, this isn't under Tree-sitter's control, because the JavaScript language allows this. I think the solution would be to separately run some kind of JavaScript linter which looks for stylistic mistakes like this, but I don't want to incorporate that responsibility into Tree-sitter itself.
