### ISSUE TITLE
Support a test-promote cycle

### ISSUE THREAD

**Issue by ostera** [tree-sitter/tree-sitter#828]
Hi! First of all thanks a million for `tree-sitter`. Super happy it exists and its a ton of fun to work with 🙏🏼  &mdash; I'm currently migrating my Erlang [Menhir parser](https://github.com/AbstractMachinesLab/caramel/blob/main/erlang/src/erl_parser.mly) to tree-sitter here: [tree-sitter-erlang](https://github.com/AbstractMachinesLab/tree-sitter-erlang).

I'd like to contribute a flag to the `tree-sitter test` subcommand, to promote corpuses with new expectations.

The reason is that as my grammars have been changing a lot, the update process has been rather painful.

In short, I've been removing all the expected s-expressions and copy-pasting the new ones, which can be pretty time consuming and because the test outputs are not pretty printed, means that most of my corpus slowly become less readable 🙈 

### The test-promote cycle

Coming from the OCaml world, where working with s-expressions is commonplace for testing too, the `dune` build tool has a similar testing cycle where you essentially diff expected vs generated sexp trees.

If they are off but you know they need to be updated, you _promote_ the new outcome. Your immediate next run of the same test will pass, since the expectations have been updated.

The cycle looks like the picture below. Here I have updated my Erlang menhir parser and the new output is expected, but I haven't updated it in my corpus yet.

![Screenshot from 2020-12-03 14-16-47](https://user-images.githubusercontent.com/854222/101022836-35cb6c80-3572-11eb-8bb8-fbc311fdc6b0.png)

---

I'd like to implement this but could use some mentoring 🤓, and of course if this isn't something that you'd like to have as a part of `tree-sitter`, I could look into building a tool _around_ it instead.

**Comment by maxbrunsfeld** [comment]
This reminds me that @ikatyang already worked on this problem in https://github.com/tree-sitter/tree-sitter/pull/442.

That PR actually looks very good. It looks like it will now parse and pretty-format the S-expression in the expectation, which is a great behavior. At the time, I never remembered to go back and re-read the diff after your rewrite @ikatyang, and it fell of our team's radar. I apologize for that. I just merged master into it so we should be able to get it merged.

@ostera Since you have experience with this type of testing workflow, you may want to review that PR as well. But if you don't get around to it right away, we can still make changes after it is merged. I will merge it fairly soon, as I feel bad about letting it linger.

**Comment by ostera** [comment]
Brilliant! ✨ 

I'm giving this a shot now and will let you know how it goes 🙌🏼

**Comment by ostera** [comment]
@maxbrunsfeld @ikatyang the flow works well! I'll submit a PR with some small change suggestions sometime today.

As another improvement I've got a tree-sitter based sexp parser/pretty printer that we can use to go from outputs like this:

```clojure
(source_file
  (expression
    (function_call
      (qualified_function_name
        (expression
          (term
            (atom
              (unquoted_atom))))
        (atom
          (unquoted_atom)))
      (expression
        (term
          (integer)))
      (expression
        (function_call
          (qualified_function_name
            (expression
              (term
                (atom
                  (unquoted_atom))))
            (atom
              (unquoted_atom)))
          (expression
            (term
              (integer)))
          (expression
            (term
              (integer)))
          (expression
            (term
              (integer))))))))
```

to something like this:

```clojure
(source_file                                                      
  (expression                                                                    
    (function_call                                                               
      (qualified_function_name                                                   
        (expression (term (atom (unquoted_atom))))                               
        (atom (unquoted_atom)))                                                  
      (expression (term (integer)))                                              
      (expression                                                                
        (function_call                                                           
          (qualified_function_name                                               
            (expression (term (atom (unquoted_atom))))                           
            (atom (unquoted_atom)))                                              
          (expression (term (integer)))                                          
          (expression (term (integer)))                                          
          (expression (term (integer))))))))
```

@maxbrunsfeld would you be okay with the CLI depending on a tree-sitter parser? I'd happily transfer the repo to this org so you have full control over it.

**Comment by maxbrunsfeld** [comment]
I don't have a strong opinion the formatting, but your proposal (no line break for nodes with only one child) looks nice.

I think I'd actually prefer to keep using a hand-written parser for this purpose, since the format is so simple, and it avoid a circular dependency. That dependency would add some complexity because, when bumping the Tree-sitter parser ABI version, we'd need to regenerate the S-expression parser with the new ABI (but using an existing CLI), then build the new CLI with the newly generated parser.

That workflow is definitely doable (and commonplace for bootstrapped compilers), but it seems like overkill to me for this purpose, since right now, `format_sexp` is just a 50-line rust function.

**Comment by ostera** [comment]
I understand :) -- my first take was to handroll an S-expr parser, into an enum, so I could pretty print it nicely again, but the actual parsing code ended up being ~150-200 lines of Rust. Sort of like this one: 

Writing the tree-sitter grammar took 20 minutes and it was a lot more fun anyway! Here it is if you think it can be useful, it also includes some rust bindings: https://github.com/AbstractMachinesLab/tree-sitter-sexp

So using it from the Cli would be a matter of

```rust
let actual = Sexp::of_str(actual)?.to_string();
let expected = Sexp::of_str(expected)?.to_string();
```

**Comment by ostera** [comment]
Re: the ABI updates, wouldn't consuming this library as a crate solve this? 🤔

**Comment by maxbrunsfeld** [comment]
Consuming the library as a crate wouldn't remove the complexity that I'm talking about with the ABI. For a backwards-incompatible ABI change, I think you'd need to:

* Make changes to the parser generation code, bump the generated ABI version number.
* Recompile the CLI.
* At this point, the `tree-sitter test --update` would be broken, because of a failure to load the old S-expression parser.
* Using this new, partially-working build of the CLI, regenerate the S-expression parser
* Push up a new version of the S-expression parser that depends on an in-progress version of the CLI.
* Update the CLI's `Cargo.toml` to point to the new S-expression parser.
* Recompile the CLI again with the new S-expression parser.

It's not that bad, but I think it'd be easier to to just keep the S-expression parser as a hand-coded function.

**Comment by ostera** [comment]
Hm, trying to wrap my head around this. Wouldn't that be necessary only if we added the tree-sitter-sexp _sources_ as part of the `build.rs` of the cli crate?

Otherwise yes, I agree with you that that'd be a lot more work than just shipping a hand-coded parser+pretty-printer functions.

My impression was that once the tree-sitter-sexp crate is built, the cli crate consumes it without really knowing anything about how it was built, eg., just linking to it as with any other library. So newer versions of the cli would still carry around a possibly outdated tree-sitter version that is coming with the tree-sitter-sexp crate.

Either way, I can split the PR out so the smaller changes could make it in, and work out the parser/pretty-printer separately.

**Comment by maxbrunsfeld** [comment]
Oh, do you mean that the crate would include its own copy of the Tree-sitter runtime library? That would avoid the ABI versioning problem, but I don't know if you can do that with crates that have C dependencies, because the C symbols would collide.

**Comment by ostera** [comment]
Yeah, that's what I thought would happen 🤔 -- but I don't do a lot of dealing with C symbols on a daily basis, so I don't know if that's workable long-term.

**Comment by Razzeee** [comment]
Can we talk about 

```
(source_file                                                      
  (expression                                                                    
    (function_call                                                               
      (qualified_function_name                                                   
        (expression (term (atom (unquoted_atom))))                               
        (atom (unquoted_atom)))                                                  
      (expression (term (integer)))                                              
      (expression                                                                
        (function_call                                                           
          (qualified_function_name                                               
            (expression (term (atom (unquoted_atom))))                           
            (atom (unquoted_atom)))                                              
          (expression (term (integer)))                                          
          (expression (term (integer)))                                          
          (expression (term (integer))))))))
```

vs

```
(source_file                                                      
  (expression                                                                    
    (function_call                                                               
      (qualified_function_name                                                   
        (expression (term (atom (unquoted_atom))))                               
        (atom (unquoted_atom))
	   )                                                  
      (expression (term (integer)))                                              
      (expression                                                                
        (function_call                                                           
          (qualified_function_name                                               
            (expression (term (atom (unquoted_atom))))                           
            (atom (unquoted_atom))
		   )                                              
          (expression (term (integer)))                                          
          (expression (term (integer)))                                          
          (expression (term (integer)))
		 )
	   )
	 )
  )
)
```

Or is that not an option?
