### ISSUE TITLE
Possible to implement DoubleEndedIterator for Node::children?

### ISSUE THREAD

**Issue by darinmorrison** [tree-sitter/tree-sitter#862]
I have some use cases where it would be more convenient to be able to process items from `Node::children` in reverse. Unfortunately it's not possible to do this without a `.collect` first because what `Node::children` doesn't returns doesn't implement `DoubleEndedIterator`.

Is it possible to change this?

I took a quick look through the source and it seems feasible by implementing a `ts_tree_cursor_child_iterator_prev` (corresponding to `ts_tree_cursor_child_iterator_next`) and building upon this. Probably `Node::children` would need to be changed to return a `Children` struct with the appropriate impls.

But I don't entirely understand how the cursor code works without digging further so I first just wanted to ask if there is some reason why this wouldn't work out.

**Comment by maxbrunsfeld** [comment]
I might be wrong, but I think it's not feasible to do efficiently.

Internally, nodes don't store their positions (only their own *extents*), so positions are computed as each node is retrieved. I believe that because of the way that row/column extents are represented, the row/column positions can't be calculated when traversing the tree backwards.

**Comment by darinmorrison** [comment]
Thanks for the response.

Luckily it turns out I probably don't need this after coming up with a different algorithm for the situation that prompted the question.  I'll go ahead and close this.
