### ISSUE TITLE
Performance optimizations when only parsing a file once?

### ISSUE THREAD

**Issue by invrainbow** [tree-sitter/tree-sitter#995]
If I just want to parse a file *once* (e.g. doing a single pass through large directories of code), can I turn off all the incremental parsing stuff to make tree-sitter go faster?

I assume currently not, so follow-up, would this be fairly simple to do, a quick wrap-in-an-if-block sort of thing? Or is the incremental parsing stuff too tightly integrated?

**Comment by patrickt** [comment]
As far as I understand it from my brief glances at the incremental analysis papers, incrementality is pretty fundamental to the tree-sitter parsing flow and the data structures that it uses. If initial parsing of a file is too slow, that’s probably best addressed by grammar changes.

**Comment by maxbrunsfeld** [comment]
No, there isn't any incremental-specific logic that can be turned off. For the most part, on the initial parse, Tree-sitter is just doing regular LR/GLR parsing. To make incremental parsing possible, the library does store a small amount of extra data on each subtree, and it represents repetitions in a more memory-intensive way (a balanced binary tree instead of a simple array). But those are the only notable costs of incremental parsing.

I think if you're trying to speed things up, the best things that I know of that you can do are:
* use a good memory allocator
* make sure the grammar doesn't create unnecessary "wrapper" nodes

Also, if you want to dig into profiling Tree-sitter and can find some ways to speed things up in general, that would be great.
